# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle

from sklearn.metrics import balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/X_train_stacking_layer_three.parquet')
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_three.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.999778,0.000212,0.000009,0.999787,0.000174,0.000040,0.999864,0.000121,0.000016,0.999733,0.000264,2.459617e-06,0.999775,0.000225,2.616556e-08,0.998912,0.000955,0.000133
1,0.994627,0.000176,0.005197,0.995247,0.000365,0.004388,0.992235,0.000199,0.007566,0.973059,0.000137,2.680453e-02,0.994737,0.000047,5.216709e-03,0.976808,0.000850,0.022342
2,0.000048,0.999944,0.000008,0.000483,0.999485,0.000032,0.000169,0.999822,0.000009,0.000015,0.999984,1.319155e-06,0.000011,0.999989,9.836632e-08,0.000068,0.999897,0.000035
3,0.999915,0.000081,0.000005,0.999745,0.000217,0.000039,0.999858,0.000127,0.000014,0.999960,0.000040,6.602657e-07,0.999793,0.000207,3.828407e-08,0.998919,0.000947,0.000134
4,0.998164,0.001812,0.000024,0.998143,0.001764,0.000093,0.998504,0.001459,0.000037,0.986426,0.013556,1.806930e-05,0.998227,0.001769,3.566911e-06,0.994430,0.005248,0.000322

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.998177,0.001784,0.000039,0.997654,0.002153,0.000193,0.998108,0.001843,0.000049,0.997980,0.002008,0.000012,0.998183,0.001800,0.000017,0.993598,0.005832,0.000569
1,0.997269,0.002710,0.000021,0.997945,0.001978,0.000077,0.997185,0.002778,0.000037,0.994660,0.005324,0.000015,0.997905,0.002092,0.000003,0.993669,0.005970,0.000361
2,0.996089,0.000609,0.003303,0.997698,0.000711,0.001592,0.997502,0.000382,0.002115,0.997295,0.001499,0.001207,0.997506,0.000715,0.001780,0.988872,0.002584,0.008544
3,0.000643,0.000107,0.999250,0.001658,0.000165,0.998177,0.000730,0.000132,0.999138,0.000139,0.000020,0.999841,0.000541,0.000023,0.999436,0.000378,0.000214,0.999409
4,0.999631,0.000357,0.000012,0.999578,0.000365,0.000058,0.999737,0.000245,0.000018,0.999526,0.000469,0.000005,0.999785,0.000205,0.000010,0.998670,0.001116,0.000214

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx, :]
        X_valid_fold = X.iloc[valid_idx, :]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        model = LogisticRegression(
            solver=trial.suggest_categorical("solver", ["saga"]),
            C=trial.suggest_float("C", 1e-5, 100, log=True),
            l1_ratio=trial.suggest_float("l1_ratio", 0.0, 1.0),
            class_weight=trial.suggest_categorical("class_weight", [None, "balanced"]),
            fit_intercept=trial.suggest_categorical("fit_intercept", [True, False]),
            tol=trial.suggest_float("tol", 1e-6, 1e-2, log=True),
            max_iter=trial.suggest_int("max_iter", 2000, 5000),
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)

        w0 = trial.suggest_float('weight_class_0', 0.1, 100.0)
        w1 = trial.suggest_float('weight_class_1', 0.1, 100.0)
        w2 = trial.suggest_float('weight_class_2', 0.1, 100.0)

        weights = np.array([w0, w1, w2])
        weighted_probas = proba * weights

        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=30, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-18 10:22:38,915] A new study created in memory with name: no-name-c8d4e97e-abe1-4feb-941d-cd25a65fefa6
Best trial: 4. Best value: 0.96369:   3%|████▋                                                                                                                                       | 1/30 [00:36<17:42, 36.64s/it]

[I 2026-06-18 10:23:15,546] Trial 4 finished with value: 0.9636904475990885 and parameters: {'solver': 'saga', 'C': 0.025116306458195778, 'l1_ratio': 0.13447175935836297, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00031867477614607576, 'max_iter': 3077, 'weight_class_0': 64.64507909318253, 'weight_class_1': 24.005777859025873, 'weight_class_2': 19.53246691220257}. Best is trial 4 with value: 0.9636904475990885.

Best trial: 4. Best value: 0.96369:   7%|█████████▎                                                                                                                                  | 2/30 [00:38<07:36, 16.31s/it]

[I 2026-06-18 10:23:17,597] Trial 2 finished with value: 0.962637073111356 and parameters: {'solver': 'saga', 'C': 0.00036814457985981424, 'l1_ratio': 0.89773753118166, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010326173696425072, 'max_iter': 3343, 'weight_class_0': 74.78742218585307, 'weight_class_1': 45.66362965735184, 'weight_class_2': 22.23358930906439}. Best is trial 4 with value: 0.9636904475990885.

Best trial: 4. Best value: 0.96369:  10%|██████████████                                                                                                                              | 3/30 [00:39<04:10,  9.26s/it]

[I 2026-06-18 10:23:18,507] Trial 3 finished with value: 0.9561843964583042 and parameters: {'solver': 'saga', 'C': 0.00026245845541655747, 'l1_ratio': 0.7900334682951099, 'class_weight': None, 'fit_intercept': False, 'tol': 7.51799532990405e-05, 'max_iter': 4827, 'weight_class_0': 36.237639895357056, 'weight_class_1': 35.29367426473953, 'weight_class_2': 23.530843970872844}. Best is trial 4 with value: 0.9636904475990885.

Best trial: 4. Best value: 0.96369:  13%|██████████████████▋                                                                                                                         | 4/30 [00:41<02:48,  6.49s/it]

[I 2026-06-18 10:23:20,754] Trial 8 finished with value: 0.9631151745569188 and parameters: {'solver': 'saga', 'C': 0.0013351339693101513, 'l1_ratio': 0.724388128349282, 'class_weight': None, 'fit_intercept': True, 'tol': 5.249264927436737e-05, 'max_iter': 3496, 'weight_class_0': 35.537425488620265, 'weight_class_1': 43.47985633981834, 'weight_class_2': 89.46991923025196}. Best is trial 4 with value: 0.9636904475990885.

Best trial: 1. Best value: 0.965962:  17%|███████████████████████▏                                                                                                                   | 5/30 [00:45<02:12,  5.31s/it]

[I 2026-06-18 10:23:23,953] Trial 1 finished with value: 0.9659623761771361 and parameters: {'solver': 'saga', 'C': 0.006982302698634619, 'l1_ratio': 0.6589326312406164, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.6233430577399016e-05, 'max_iter': 4737, 'weight_class_0': 97.78979990787576, 'weight_class_1': 93.49749401807742, 'weight_class_2': 89.68208914812311}. Best is trial 1 with value: 0.9659623761771361.
[I 2026-06-18 10:23:23,987] Trial 0 pruned.

Best trial: 1. Best value: 0.965962:  23%|████████████████████████████████▍                                                                                                          | 7/30 [00:49<01:25,  3.72s/it]

[I 2026-06-18 10:23:28,323] Trial 9 pruned.

Best trial: 1. Best value: 0.965962:  27%|█████████████████████████████████████                                                                                                      | 8/30 [00:49<01:01,  2.79s/it]

[I 2026-06-18 10:23:28,547] Trial 7 pruned.

Best trial: 1. Best value: 0.965962:  33%|██████████████████████████████████████████████                                                                                            | 10/30 [00:51<00:36,  1.84s/it]

[I 2026-06-18 10:23:30,253] Trial 6 pruned.
[I 2026-06-18 10:23:30,456] Trial 11 finished with value: 0.9648324355736102 and parameters: {'solver': 'saga', 'C': 0.06340578506658613, 'l1_ratio': 0.36454820082648787, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.0453513139879098e-05, 'max_iter': 3858, 'weight_class_0': 40.48843503369315, 'weight_class_1': 57.104925380349236, 'weight_class_2': 16.453843226769884}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 1. Best value: 0.965962:  37%|██████████████████████████████████████████████████▌                                                                                       | 11/30 [00:58<01:04,  3.40s/it]

[I 2026-06-18 10:23:37,701] Trial 13 pruned.

Best trial: 1. Best value: 0.965962:  40%|███████████████████████████████████████████████████████▏                                                                                  | 12/30 [01:00<00:50,  2.78s/it]

[I 2026-06-18 10:23:38,985] Trial 17 pruned.

Best trial: 1. Best value: 0.965962:  43%|███████████████████████████████████████████████████████████▊                                                                              | 13/30 [01:09<01:18,  4.61s/it]

[I 2026-06-18 10:23:48,005] Trial 14 finished with value: 0.9654668558306085 and parameters: {'solver': 'saga', 'C': 0.011518170210529326, 'l1_ratio': 0.3048579642357968, 'class_weight': None, 'fit_intercept': False, 'tol': 0.001326608919545842, 'max_iter': 4173, 'weight_class_0': 2.701746880195356, 'weight_class_1': 94.78380308525902, 'weight_class_2': 67.03538048549241}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 1. Best value: 0.965962:  47%|████████████████████████████████████████████████████████████████▍                                                                         | 14/30 [01:11<01:04,  4.05s/it]

[I 2026-06-18 10:23:50,712] Trial 15 finished with value: 0.9650909545144355 and parameters: {'solver': 'saga', 'C': 0.0033310230143060305, 'l1_ratio': 0.9071050837119411, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0009666223615967812, 'max_iter': 4020, 'weight_class_0': 13.769154816889856, 'weight_class_1': 75.15693341377118, 'weight_class_2': 47.18035417997331}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 1. Best value: 0.965962:  50%|█████████████████████████████████████████████████████████████████████                                                                     | 15/30 [01:12<00:43,  2.92s/it]

[I 2026-06-18 10:23:50,941] Trial 20 finished with value: 0.9655740833188771 and parameters: {'solver': 'saga', 'C': 0.0004782675032463548, 'l1_ratio': 0.3872488919585977, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0034299523350091966, 'max_iter': 2727, 'weight_class_0': 34.5231137397048, 'weight_class_1': 95.05830676247153, 'weight_class_2': 37.67071527651884}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 1. Best value: 0.965962:  53%|█████████████████████████████████████████████████████████████████████████▌                                                                | 16/30 [01:16<00:48,  3.44s/it]

[I 2026-06-18 10:23:55,614] Trial 16 pruned.

Best trial: 1. Best value: 0.965962:  57%|██████████████████████████████████████████████████████████████████████████████▏                                                           | 17/30 [01:18<00:37,  2.91s/it]

[I 2026-06-18 10:23:57,267] Trial 12 finished with value: 0.9655869392471021 and parameters: {'solver': 'saga', 'C': 7.318611508875556, 'l1_ratio': 0.030135757521379314, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0042384285038921995, 'max_iter': 4658, 'weight_class_0': 97.55038831820686, 'weight_class_1': 44.26285447558072, 'weight_class_2': 59.536955244273756}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 1. Best value: 0.965962:  60%|██████████████████████████████████████████████████████████████████████████████████▊                                                       | 18/30 [01:19<00:27,  2.31s/it]

[I 2026-06-18 10:23:58,174] Trial 21 pruned.

Best trial: 1. Best value: 0.965962:  63%|███████████████████████████████████████████████████████████████████████████████████████▍                                                  | 19/30 [01:36<01:15,  6.88s/it]

[I 2026-06-18 10:24:15,772] Trial 26 pruned.

Best trial: 1. Best value: 0.965962:  67%|████████████████████████████████████████████████████████████████████████████████████████████                                              | 20/30 [01:39<00:57,  5.70s/it]

[I 2026-06-18 10:24:18,702] Trial 25 pruned.

Best trial: 1. Best value: 0.965962:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 22/30 [01:44<00:31,  3.88s/it]

[I 2026-06-18 10:24:23,660] Trial 19 pruned.
[I 2026-06-18 10:24:23,823] Trial 5 pruned.

Best trial: 1. Best value: 0.965962:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 23/30 [01:50<00:30,  4.41s/it]

[I 2026-06-18 10:24:29,433] Trial 22 finished with value: 0.9657668215678197 and parameters: {'solver': 'saga', 'C': 1.7972291806004403, 'l1_ratio': 0.5413017816899062, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003115012507830542, 'max_iter': 4188, 'weight_class_0': 99.55043533927778, 'weight_class_1': 62.86736091460059, 'weight_class_2': 62.96217467527411}. Best is trial 1 with value: 0.9659623761771361.

Best trial: 27. Best value: 0.966384:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 24/30 [01:55<00:26,  4.44s/it]

[I 2026-06-18 10:24:33,977] Trial 27 finished with value: 0.966384056041312 and parameters: {'solver': 'saga', 'C': 2.6336088899421295, 'l1_ratio': 0.5567252200901791, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005507757703013647, 'max_iter': 2275, 'weight_class_0': 86.92317027715983, 'weight_class_1': 97.87994073895375, 'weight_class_2': 97.27761584260433}. Best is trial 27 with value: 0.966384056041312.

Best trial: 27. Best value: 0.966384:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 25/30 [02:00<00:24,  4.89s/it]

[I 2026-06-18 10:24:39,913] Trial 24 finished with value: 0.9651025872383723 and parameters: {'solver': 'saga', 'C': 3.39257566814265, 'l1_ratio': 0.5774878702089088, 'class_weight': None, 'fit_intercept': False, 'tol': 0.005030969030396056, 'max_iter': 4288, 'weight_class_0': 2.3594452414690625, 'weight_class_1': 99.05323879446006, 'weight_class_2': 67.43425886856429}. Best is trial 27 with value: 0.966384056041312.

Best trial: 27. Best value: 0.966384:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 26/30 [02:13<00:28,  7.20s/it]

[I 2026-06-18 10:24:52,512] Trial 29 finished with value: 0.9662657812495512 and parameters: {'solver': 'saga', 'C': 2.4114257363902207, 'l1_ratio': 0.9958302451744027, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.009855663375352342, 'max_iter': 4533, 'weight_class_0': 85.23071076552075, 'weight_class_1': 60.50924767782192, 'weight_class_2': 96.03179978814244}. Best is trial 27 with value: 0.966384056041312.

Best trial: 27. Best value: 0.966384:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 27/30 [03:34<01:27, 29.32s/it]

[I 2026-06-18 10:26:13,452] Trial 28 pruned.

Best trial: 27. Best value: 0.966384:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 28/30 [05:10<01:38, 49.22s/it]

[I 2026-06-18 10:27:49,103] Trial 18 pruned.

Best trial: 27. Best value: 0.966384:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 29/30 [05:55<00:47, 47.96s/it]

[I 2026-06-18 10:28:34,127] Trial 23 pruned.

Best trial: 27. Best value: 0.966384: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [12:58<00:00, 25.94s/it]

[I 2026-06-18 10:35:37,183] Trial 10 pruned.
Best trial score:
0.966384056041312

Best params:
{'solver': 'saga', 'C': 2.6336088899421295, 'l1_ratio': 0.5567252200901791, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005507757703013647, 'max_iter': 2275, 'weight_class_0': 86.92317027715983, 'weight_class_1': 97.87994073895375, 'weight_class_2': 97.27761584260433}

In [18]:
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=30, n_jobs=-1, show_progress_bar=True)

Best trial: 59. Best value: 0.966501:   3%|████▌                                                                                                                                     | 1/30 [00:18<09:05, 18.81s/it]

[I 2026-06-18 10:55:52,024] Trial 60 pruned.

Best trial: 59. Best value: 0.966501:   7%|█████████▏                                                                                                                                | 2/30 [00:19<03:46,  8.09s/it]

[I 2026-06-18 10:55:52,600] Trial 61 pruned.

Best trial: 59. Best value: 0.966501:  13%|██████████████████▍                                                                                                                       | 4/30 [00:20<01:14,  2.88s/it]

[I 2026-06-18 10:55:53,173] Trial 66 pruned.
[I 2026-06-18 10:55:53,337] Trial 62 pruned.

Best trial: 59. Best value: 0.966501:  17%|███████████████████████                                                                                                                   | 5/30 [00:20<00:52,  2.12s/it]

[I 2026-06-18 10:55:54,102] Trial 65 pruned.

Best trial: 59. Best value: 0.966501:  20%|███████████████████████████▌                                                                                                              | 6/30 [00:21<00:35,  1.49s/it]

[I 2026-06-18 10:55:54,379] Trial 67 pruned.

Best trial: 59. Best value: 0.966501:  23%|████████████████████████████████▏                                                                                                         | 7/30 [00:21<00:26,  1.17s/it]

[I 2026-06-18 10:55:54,890] Trial 63 pruned.

Best trial: 59. Best value: 0.966501:  27%|████████████████████████████████████▊                                                                                                     | 8/30 [00:22<00:26,  1.21s/it]

[I 2026-06-18 10:55:56,199] Trial 69 pruned.

Best trial: 59. Best value: 0.966501:  30%|█████████████████████████████████████████▍                                                                                                | 9/30 [00:23<00:20,  1.03it/s]

[I 2026-06-18 10:55:56,623] Trial 71 pruned.

Best trial: 59. Best value: 0.966501:  33%|█████████████████████████████████████████████▋                                                                                           | 10/30 [00:23<00:15,  1.27it/s]

[I 2026-06-18 10:55:57,007] Trial 64 pruned.

Best trial: 59. Best value: 0.966501:  37%|██████████████████████████████████████████████████▏                                                                                      | 11/30 [00:24<00:12,  1.58it/s]

[I 2026-06-18 10:55:57,293] Trial 68 pruned.

Best trial: 59. Best value: 0.966501:  40%|██████████████████████████████████████████████████████▊                                                                                  | 12/30 [00:24<00:10,  1.72it/s]

[I 2026-06-18 10:55:57,756] Trial 70 pruned.

Best trial: 59. Best value: 0.966501:  43%|███████████████████████████████████████████████████████████▎                                                                             | 13/30 [00:52<02:31,  8.92s/it]

[I 2026-06-18 10:56:25,840] Trial 76 finished with value: 0.9664438436016782 and parameters: {'solver': 'saga', 'C': 0.030010983494862205, 'l1_ratio': 0.8515981125636577, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002538690009088182, 'max_iter': 4381, 'weight_class_0': 48.59860592029372, 'weight_class_1': 91.88948359089959, 'weight_class_2': 93.31332974102983}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  47%|███████████████████████████████████████████████████████████████▉                                                                         | 14/30 [01:23<04:08, 15.56s/it]

[I 2026-06-18 10:56:56,764] Trial 72 finished with value: 0.9664940950267387 and parameters: {'solver': 'saga', 'C': 0.0973754495936817, 'l1_ratio': 0.8641373639365134, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.837230450719772e-05, 'max_iter': 4392, 'weight_class_0': 57.75350734012396, 'weight_class_1': 75.19399766915569, 'weight_class_2': 85.93553924468841}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 15/30 [01:57<05:16, 21.13s/it]

[I 2026-06-18 10:57:30,814] Trial 85 finished with value: 0.9663936307653194 and parameters: {'solver': 'saga', 'C': 0.018825827993785203, 'l1_ratio': 0.8617893719474662, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002419585243624291, 'max_iter': 4274, 'weight_class_0': 48.13055056048064, 'weight_class_1': 92.43826285216883, 'weight_class_2': 86.54846688273524}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  53%|█████████████████████████████████████████████████████████████████████████                                                                | 16/30 [03:30<09:58, 42.74s/it]

[I 2026-06-18 10:59:03,726] Trial 78 finished with value: 0.9663954647845715 and parameters: {'solver': 'saga', 'C': 0.6895256319859737, 'l1_ratio': 0.8748820228148539, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00022291447057222463, 'max_iter': 4368, 'weight_class_0': 47.26155299742709, 'weight_class_1': 92.22668408698361, 'weight_class_2': 85.92534205891116}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 17/30 [03:57<08:14, 38.06s/it]

[I 2026-06-18 10:59:30,889] Trial 80 finished with value: 0.9663981152842757 and parameters: {'solver': 'saga', 'C': 0.8020873540324408, 'l1_ratio': 0.8775414133603052, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002489247943742917, 'max_iter': 4385, 'weight_class_0': 46.89264230990692, 'weight_class_1': 92.66171031027847, 'weight_class_2': 86.58200718320137}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 18/30 [03:59<05:26, 27.24s/it]

[I 2026-06-18 10:59:32,934] Trial 79 finished with value: 0.9664599222268653 and parameters: {'solver': 'saga', 'C': 0.7829538937057696, 'l1_ratio': 0.8759422915931737, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00020952433468182253, 'max_iter': 4594, 'weight_class_0': 48.89755788741692, 'weight_class_1': 68.98454336223516, 'weight_class_2': 92.34412969769353}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 19/30 [04:04<03:46, 20.62s/it]

[I 2026-06-18 10:59:38,135] Trial 83 finished with value: 0.9663666428292714 and parameters: {'solver': 'saga', 'C': 0.8081370619069584, 'l1_ratio': 0.8573151183312108, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002169605556541354, 'max_iter': 4590, 'weight_class_0': 79.26964993482115, 'weight_class_1': 93.48089755388372, 'weight_class_2': 85.68932305814394}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 20/30 [04:13<02:48, 16.88s/it]

[I 2026-06-18 10:59:46,294] Trial 87 finished with value: 0.9664247246867695 and parameters: {'solver': 'saga', 'C': 0.02978572699122965, 'l1_ratio': 0.7334072338360453, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.7808729585554155e-05, 'max_iter': 4608, 'weight_class_0': 41.06101194666788, 'weight_class_1': 67.90200101818141, 'weight_class_2': 85.49479622087476}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 21/30 [04:14<01:50, 12.23s/it]

[I 2026-06-18 10:59:47,691] Trial 73 finished with value: 0.966430508705575 and parameters: {'solver': 'saga', 'C': 0.8568861143298909, 'l1_ratio': 0.8479392341827929, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001509153890428584, 'max_iter': 4365, 'weight_class_0': 58.53320422308654, 'weight_class_1': 91.45319108289718, 'weight_class_2': 92.3055726033291}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  73%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 22/30 [04:17<01:15,  9.43s/it]

[I 2026-06-18 10:59:50,598] Trial 82 finished with value: 0.9664470035083157 and parameters: {'solver': 'saga', 'C': 0.9114355454465053, 'l1_ratio': 0.8829486344907926, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002478808453268693, 'max_iter': 4597, 'weight_class_0': 70.57975782419008, 'weight_class_1': 82.88426602031241, 'weight_class_2': 85.87595283176577}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 23/30 [04:19<00:50,  7.25s/it]

[I 2026-06-18 10:59:52,756] Trial 84 finished with value: 0.9663988280870776 and parameters: {'solver': 'saga', 'C': 0.72943261924474, 'l1_ratio': 0.8640751522186125, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00023611347708291357, 'max_iter': 4586, 'weight_class_0': 46.455149218348225, 'weight_class_1': 92.83733048252905, 'weight_class_2': 84.83550039854887}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 24/30 [04:24<00:39,  6.52s/it]

[I 2026-06-18 10:59:57,566] Trial 75 finished with value: 0.9664203242125463 and parameters: {'solver': 'saga', 'C': 0.7769722906640706, 'l1_ratio': 0.8634704879890712, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001267087906270028, 'max_iter': 4365, 'weight_class_0': 79.41874821690982, 'weight_class_1': 92.30145398484434, 'weight_class_2': 92.88988756971044}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 25/30 [04:26<00:26,  5.29s/it]

[I 2026-06-18 10:59:59,975] Trial 81 finished with value: 0.9664122599497652 and parameters: {'solver': 'saga', 'C': 1.0375575264962762, 'l1_ratio': 0.8559478441412852, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002444273164695201, 'max_iter': 4364, 'weight_class_0': 50.36811364191024, 'weight_class_1': 92.12403315064913, 'weight_class_2': 85.38265260804718}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 26/30 [04:31<00:21,  5.26s/it]

[I 2026-06-18 11:00:05,187] Trial 89 finished with value: 0.9664472691994398 and parameters: {'solver': 'saga', 'C': 0.030253874673575112, 'l1_ratio': 0.8203527982659284, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.592453068534883e-05, 'max_iter': 4135, 'weight_class_0': 40.09670279380643, 'weight_class_1': 66.17776798260667, 'weight_class_2': 94.54061969836964}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 27/30 [04:32<00:11,  3.92s/it]

[I 2026-06-18 11:00:05,984] Trial 88 finished with value: 0.9664063734112414 and parameters: {'solver': 'saga', 'C': 0.030012660395437686, 'l1_ratio': 0.8228323779559242, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.375519015999809e-05, 'max_iter': 4570, 'weight_class_0': 53.17466664057844, 'weight_class_1': 68.77212430453551, 'weight_class_2': 94.15677486911576}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 28/30 [04:37<00:08,  4.24s/it]

[I 2026-06-18 11:00:10,958] Trial 77 finished with value: 0.9664506363627854 and parameters: {'solver': 'saga', 'C': 0.9731747259754717, 'l1_ratio': 0.8502059776949186, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014625376732145317, 'max_iter': 4405, 'weight_class_0': 48.26990230996273, 'weight_class_1': 92.57128981026096, 'weight_class_2': 92.70860346031922}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 29/30 [04:42<00:04,  4.34s/it]

[I 2026-06-18 11:00:15,524] Trial 74 finished with value: 0.9664473654585322 and parameters: {'solver': 'saga', 'C': 0.8982105322796461, 'l1_ratio': 0.8742170780053262, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011489101523439219, 'max_iter': 4344, 'weight_class_0': 54.089599821611074, 'weight_class_1': 92.4173342512778, 'weight_class_2': 92.85661410372009}. Best is trial 59 with value: 0.9665009397831099.

Best trial: 59. Best value: 0.966501: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [05:13<00:00, 10.46s/it]

[I 2026-06-18 11:00:47,063] Trial 86 finished with value: 0.9664379407639793 and parameters: {'solver': 'saga', 'C': 0.733133322933437, 'l1_ratio': 0.7205834099572869, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.3928908646947333e-05, 'max_iter': 4591, 'weight_class_0': 50.54513895621818, 'weight_class_1': 91.6536723519764, 'weight_class_2': 86.69815873652722}. Best is trial 59 with value: 0.9665009397831099.

In [19]:
lg_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lg = LogisticRegression(**lg_params).fit(X_train, y_train.class_encoded)

test_proba = lg.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [20]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [21]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lg.csv', index=False)

In [22]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [23]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'hist_0', 'hist_1', 'hist_2', 'rf_0', 'rf_1', 'rf_2',
       'extra_0', 'extra_1', 'extra_2'],
      dtype='str')