# Imports

In [9]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import MulticlassThresholdOptimizer, load_pickle

from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

## Utils

In [ ]:
label_encoder = load_pickle('../models/')

# Loading Datasets

In [2]:
X_train = pd.read_parquet('../data/X_train_stacking_layer_one.parquet')
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_one.parquet')

In [3]:
X_train.head()

,lgbm_0,lgbm_1,cat_0,cat_1,xgb_0,xgb_1,hist_0,hist_1,extra_0,extra_1,rf_0,rf_1
0,9.999566e-01,0.000043,0.999900,0.000050,0.999734,0.000192,9.998896e-01,0.000105,0.912643,0.007039,0.999665,0.000155
1,9.895666e-01,0.000366,0.986604,0.000093,0.985616,0.000664,9.819315e-01,0.000384,0.803503,0.004824,0.965267,0.000184
2,3.890271e-07,1.000000,0.000016,0.999984,0.000088,0.999889,3.930889e-07,1.000000,0.006700,0.965519,0.000113,0.999887
3,9.998353e-01,0.000164,0.999925,0.000071,0.999614,0.000265,9.991001e-01,0.000895,0.932451,0.006030,0.999310,0.000345
4,9.993004e-01,0.000692,0.999187,0.000766,0.998981,0.000832,9.846569e-01,0.015320,0.915246,0.008021,0.997708,0.000696

In [4]:
X_test.head()

,lgbm_0,lgbm_1,cat_0,cat_1,xgb_0,xgb_1,hist_0,hist_1,extra_0,extra_1,rf_0,rf_1
0,0.999271,0.000708,0.996756,0.002437,0.997384,0.002024,0.999265,0.000701,0.611632,0.076394,0.977833,0.009356
1,0.997605,0.002393,0.997894,0.002102,0.998017,0.001866,0.971958,0.028034,0.942311,0.018000,0.998781,0.000921
2,0.998315,0.000205,0.999515,0.000035,0.994165,0.001013,0.996011,0.000573,0.530537,0.015231,0.980001,0.002162
3,0.000593,0.000201,0.001054,0.000337,0.003027,0.001288,0.000174,0.000112,0.086899,0.066500,0.009974,0.007596
4,0.999900,0.000097,0.999687,0.000311,0.999482,0.000408,0.999597,0.000382,0.945084,0.015204,0.999542,0.000244

# Machine Learning

In [5]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000),
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx, :]
        X_valid_fold = X.iloc[valid_idx, :]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        model = LogisticRegression(**params)
        model.fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)

        score = log_loss(y_valid_fold, proba)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)

study = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=20, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-04 16:18:02,789] A new study created in memory with name: no-name-03c3c641-3b99-49fc-8a38-2c30a0c0e120
Best trial: 5. Best value: 0.127569:   5%|██████▉                                                                                                                                    | 1/20 [00:18<05:57, 18.81s/it]

[I 2026-06-04 16:18:21,596] Trial 5 finished with value: 0.12756909329978816 and parameters: {'solver': 'saga', 'C': 0.00406966840233501, 'l1_ratio': 0.892836984648035, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.006704822604034238, 'max_iter': 2601}. Best is trial 5 with value: 0.12756909329978816.

Best trial: 5. Best value: 0.127569:  10%|█████████████▉                                                                                                                             | 2/20 [00:25<03:28, 11.56s/it]

[I 2026-06-04 16:18:28,086] Trial 3 finished with value: 0.14534839859392362 and parameters: {'solver': 'saga', 'C': 0.7989892100430462, 'l1_ratio': 0.922830863658472, 'class_weight': None, 'fit_intercept': False, 'tol': 0.008461246664135514, 'max_iter': 1982}. Best is trial 5 with value: 0.12756909329978816.

Best trial: 8. Best value: 0.127472:  15%|████████████████████▊                                                                                                                      | 3/20 [00:29<02:18,  8.15s/it]

[I 2026-06-04 16:18:32,173] Trial 8 finished with value: 0.12747160975800725 and parameters: {'solver': 'saga', 'C': 10.950508457055914, 'l1_ratio': 0.04617710083502469, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00168228553121991, 'max_iter': 4750}. Best is trial 8 with value: 0.12747160975800725.

Best trial: 8. Best value: 0.127472:  20%|███████████████████████████▊                                                                                                               | 4/20 [00:30<01:24,  5.27s/it]

[I 2026-06-04 16:18:33,028] Trial 6 finished with value: 0.1775407853726046 and parameters: {'solver': 'saga', 'C': 1.430785546169851, 'l1_ratio': 0.08300288082100482, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00033750718923317163, 'max_iter': 3029}. Best is trial 8 with value: 0.12747160975800725.

Best trial: 8. Best value: 0.127472:  25%|██████████████████████████████████▊                                                                                                        | 5/20 [00:33<01:10,  4.69s/it]

[I 2026-06-04 16:18:36,683] Trial 11 finished with value: 0.3196307126559412 and parameters: {'solver': 'saga', 'C': 8.340067337802293e-05, 'l1_ratio': 0.8868421233959036, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.84141025820367e-05, 'max_iter': 1237}. Best is trial 8 with value: 0.12747160975800725.

Best trial: 4. Best value: 0.102409:  30%|█████████████████████████████████████████▋                                                                                                 | 6/20 [00:36<00:56,  4.06s/it]

[I 2026-06-04 16:18:39,513] Trial 4 finished with value: 0.1024090857320655 and parameters: {'solver': 'saga', 'C': 80.79031041038265, 'l1_ratio': 0.7772266014546229, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000375763511914987, 'max_iter': 3246}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  35%|████████████████████████████████████████████████▋                                                                                          | 7/20 [00:38<00:42,  3.25s/it]

[I 2026-06-04 16:18:41,091] Trial 0 pruned.

Best trial: 4. Best value: 0.102409:  40%|███████████████████████████████████████████████████████▌                                                                                   | 8/20 [00:40<00:34,  2.87s/it]

[I 2026-06-04 16:18:43,165] Trial 7 pruned.

Best trial: 4. Best value: 0.102409:  45%|██████████████████████████████████████████████████████████████▌                                                                            | 9/20 [00:41<00:24,  2.19s/it]

[I 2026-06-04 16:18:43,859] Trial 9 pruned.

Best trial: 4. Best value: 0.102409:  50%|█████████████████████████████████████████████████████████████████████                                                                     | 10/20 [00:42<00:20,  2.06s/it]

[I 2026-06-04 16:18:45,620] Trial 13 pruned.

Best trial: 4. Best value: 0.102409:  55%|███████████████████████████████████████████████████████████████████████████▉                                                              | 11/20 [00:48<00:29,  3.30s/it]

[I 2026-06-04 16:18:51,736] Trial 15 finished with value: 0.12751988239053486 and parameters: {'solver': 'saga', 'C': 0.11258391713554079, 'l1_ratio': 0.8612174737618798, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.009925871561647719, 'max_iter': 3626}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  60%|██████████████████████████████████████████████████████████████████████████████████▊                                                       | 12/20 [00:50<00:21,  2.72s/it]

[I 2026-06-04 16:18:53,142] Trial 19 pruned.

Best trial: 4. Best value: 0.102409:  65%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                | 13/20 [00:57<00:29,  4.18s/it]

[I 2026-06-04 16:19:00,669] Trial 12 finished with value: 0.1274909790241306 and parameters: {'solver': 'saga', 'C': 0.026577383102779115, 'l1_ratio': 0.35813459387421387, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.791600008248126e-05, 'max_iter': 1918}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  70%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 14/20 [01:05<00:31,  5.31s/it]

[I 2026-06-04 16:19:08,589] Trial 14 finished with value: 0.12753785484739683 and parameters: {'solver': 'saga', 'C': 0.023713865580203598, 'l1_ratio': 0.7433197656227751, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.377405916054326e-05, 'max_iter': 3738}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 15/20 [01:07<00:20,  4.15s/it]

[I 2026-06-04 16:19:10,056] Trial 18 finished with value: 0.1029103838026123 and parameters: {'solver': 'saga', 'C': 0.013923933426767413, 'l1_ratio': 0.6910785648626249, 'class_weight': None, 'fit_intercept': True, 'tol': 9.425045305003317e-05, 'max_iter': 4602}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 16/20 [01:13<00:18,  4.65s/it]

[I 2026-06-04 16:19:15,864] Trial 17 finished with value: 0.12756876557337157 and parameters: {'solver': 'saga', 'C': 0.020910013752369665, 'l1_ratio': 0.9938249457815511, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.084012596610532e-05, 'max_iter': 1831}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 17/20 [01:13<00:10,  3.43s/it]

[I 2026-06-04 16:19:16,443] Trial 16 finished with value: 0.10344374511303442 and parameters: {'solver': 'saga', 'C': 0.009147182796766006, 'l1_ratio': 0.22855335266249277, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4430517373911665e-06, 'max_iter': 1263}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 18/20 [04:46<02:12, 66.36s/it]

[I 2026-06-04 16:22:49,319] Trial 10 pruned.

Best trial: 4. Best value: 0.102409:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 19/20 [15:48<04:05, 245.27s/it]

[I 2026-06-04 16:33:51,363] Trial 2 finished with value: 0.12746959133963573 and parameters: {'solver': 'saga', 'C': 66.24264330978316, 'l1_ratio': 0.8402477394168169, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00020344872835997542, 'max_iter': 2746}. Best is trial 4 with value: 0.1024090857320655.

Best trial: 4. Best value: 0.102409: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [16:45<00:00, 50.25s/it]

[I 2026-06-04 16:34:47,854] Trial 1 pruned.
Best trial score:
0.1024090857320655

Best params:
{'solver': 'saga', 'C': 80.79031041038265, 'l1_ratio': 0.7772266014546229, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000375763511914987, 'max_iter': 3246}

In [22]:
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=30, n_jobs=-1, show_progress_bar=True)

Best trial: 21. Best value: 0.102408:   3%|████▌                                                                                                                                     | 1/30 [00:28<13:58, 28.92s/it]

[I 2026-06-04 16:44:45,983] Trial 33 finished with value: 0.10240996680785783 and parameters: {'solver': 'saga', 'C': 3.1604235239083516, 'l1_ratio': 0.43597493556829703, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0029844473779650337, 'max_iter': 4929}. Best is trial 21 with value: 0.1024080564765762.

Best trial: 21. Best value: 0.102408:   7%|█████████▏                                                                                                                                | 2/30 [00:29<05:36, 12.03s/it]

[I 2026-06-04 16:44:46,187] Trial 35 finished with value: 0.10240808052403856 and parameters: {'solver': 'saga', 'C': 3.5068749000188606, 'l1_ratio': 0.3956115365538211, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0030773253875507438, 'max_iter': 3977}. Best is trial 21 with value: 0.1024080564765762.

Best trial: 21. Best value: 0.102408:  10%|█████████████▊                                                                                                                            | 3/30 [00:30<03:16,  7.29s/it]

[I 2026-06-04 16:44:47,830] Trial 36 finished with value: 0.1024093538944429 and parameters: {'solver': 'saga', 'C': 5.258204684883276, 'l1_ratio': 0.455028911295048, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0024590704638991975, 'max_iter': 4897}. Best is trial 21 with value: 0.1024080564765762.

Best trial: 38. Best value: 0.102408:  13%|██████████████████▍                                                                                                                       | 4/30 [00:31<01:58,  4.55s/it]

[I 2026-06-04 16:44:48,192] Trial 38 finished with value: 0.1024078427902518 and parameters: {'solver': 'saga', 'C': 3.3380768873511744, 'l1_ratio': 0.449094990457189, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0028942509329224464, 'max_iter': 4991}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  17%|███████████████████████                                                                                                                   | 5/30 [00:31<01:18,  3.13s/it]

[I 2026-06-04 16:44:48,795] Trial 40 finished with value: 0.10240844915359573 and parameters: {'solver': 'saga', 'C': 3.605045467026367, 'l1_ratio': 0.44931706649057346, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0030299630879229967, 'max_iter': 4997}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  23%|████████████████████████████████▏                                                                                                         | 7/30 [00:32<00:38,  1.65s/it]

[I 2026-06-04 16:44:49,699] Trial 31 finished with value: 0.10240858444061782 and parameters: {'solver': 'saga', 'C': 7.667777510103447, 'l1_ratio': 0.4442056942176511, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0017223267159181665, 'max_iter': 3942}. Best is trial 38 with value: 0.1024078427902518.
[I 2026-06-04 16:44:49,871] Trial 32 finished with value: 0.10240879014001306 and parameters: {'solver': 'saga', 'C': 3.9761727861511633, 'l1_ratio': 0.47361225809839996, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0030356958218118457, 'max_iter': 4975}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  27%|████████████████████████████████████▊                                                                                                     | 8/30 [00:33<00:26,  1.22s/it]

[I 2026-06-04 16:44:50,173] Trial 41 finished with value: 0.10240788611052931 and parameters: {'solver': 'saga', 'C': 3.5277180974462925, 'l1_ratio': 0.44491977720928866, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002854358714116588, 'max_iter': 4968}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  30%|█████████████████████████████████████████▍                                                                                                | 9/30 [00:33<00:23,  1.10s/it]

[I 2026-06-04 16:44:51,009] Trial 39 finished with value: 0.10240805068924648 and parameters: {'solver': 'saga', 'C': 2.3814614065465918, 'l1_ratio': 0.430648202913679, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002408472522885785, 'max_iter': 3984}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  33%|█████████████████████████████████████████████▋                                                                                           | 10/30 [00:34<00:17,  1.17it/s]

[I 2026-06-04 16:44:51,321] Trial 37 finished with value: 0.1024081835603842 and parameters: {'solver': 'saga', 'C': 3.3279997043872185, 'l1_ratio': 0.4492277582775712, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0023082671711042494, 'max_iter': 3970}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  37%|██████████████████████████████████████████████████▏                                                                                      | 11/30 [00:38<00:35,  1.86s/it]

[I 2026-06-04 16:44:55,452] Trial 30 finished with value: 0.10240821898174188 and parameters: {'solver': 'saga', 'C': 3.3056295350683427, 'l1_ratio': 0.45682378946747787, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020284533534793182, 'max_iter': 4953}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  40%|██████████████████████████████████████████████████████▊                                                                                  | 12/30 [00:54<01:53,  6.28s/it]

[I 2026-06-04 16:45:11,836] Trial 42 finished with value: 0.10245872209598865 and parameters: {'solver': 'saga', 'C': 0.11938791736981828, 'l1_ratio': 0.42572477851098234, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0026837587057747694, 'max_iter': 3957}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 38. Best value: 0.102408:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 15/30 [00:57<00:41,  2.79s/it]

[I 2026-06-04 16:45:14,365] Trial 49 finished with value: 0.10241173850040383 and parameters: {'solver': 'saga', 'C': 27.827696657520253, 'l1_ratio': 0.6288123080472676, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00572341186510052, 'max_iter': 4716}. Best is trial 38 with value: 0.1024078427902518.
[I 2026-06-04 16:45:14,389] Trial 44 finished with value: 0.10246755269041778 and parameters: {'solver': 'saga', 'C': 0.09974000654537253, 'l1_ratio': 0.6571603401471671, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0017352960528715885, 'max_iter': 3923}. Best is trial 38 with value: 0.1024078427902518.
[I 2026-06-04 16:45:14,516] Trial 50 finished with value: 0.10240950449517985 and parameters: {'solver': 'saga', 'C': 26.826679821636567, 'l1_ratio': 0.6427151102198561, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005716305411725953, 'max_iter': 4685}. Best is trial 38 with value: 0.1024078427902518.

Best trial: 51. Best value: 0.102405:  53%|█████████████████████████████████████████████████████████████████████████                                                                | 16/30 [00:58<00:32,  2.30s/it]

[I 2026-06-04 16:45:15,357] Trial 51 finished with value: 0.10240530596157663 and parameters: {'solver': 'saga', 'C': 26.234268109754403, 'l1_ratio': 0.3020093089421957, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005342004264432969, 'max_iter': 4641}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 17/30 [00:58<00:24,  1.88s/it]

[I 2026-06-04 16:45:16,031] Trial 45 finished with value: 0.10244866515582234 and parameters: {'solver': 'saga', 'C': 0.12737040266037067, 'l1_ratio': 0.6413732428485986, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001819014222994503, 'max_iter': 3898}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 18/30 [01:01<00:25,  2.13s/it]

[I 2026-06-04 16:45:18,827] Trial 52 finished with value: 0.10240795873923274 and parameters: {'solver': 'saga', 'C': 35.45104997506947, 'l1_ratio': 0.6402773020248663, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005968981029537997, 'max_iter': 3893}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 19/30 [01:06<00:30,  2.77s/it]

[I 2026-06-04 16:45:23,249] Trial 46 finished with value: 0.10246783675829634 and parameters: {'solver': 'saga', 'C': 0.10045169029378911, 'l1_ratio': 0.6421322255121821, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023545365218709222, 'max_iter': 3917}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 20/30 [01:07<00:23,  2.39s/it]

[I 2026-06-04 16:45:24,686] Trial 48 finished with value: 0.10244615555967333 and parameters: {'solver': 'saga', 'C': 0.13174269708919792, 'l1_ratio': 0.6395358860626823, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002570243723038912, 'max_iter': 4025}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 21/30 [01:08<00:16,  1.88s/it]

[I 2026-06-04 16:45:25,304] Trial 47 finished with value: 0.10244270789804924 and parameters: {'solver': 'saga', 'C': 0.1377376063269601, 'l1_ratio': 0.666533332468523, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023501271295823636, 'max_iter': 4006}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  73%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 22/30 [01:09<00:14,  1.78s/it]

[I 2026-06-04 16:45:26,846] Trial 43 finished with value: 0.10240824553470784 and parameters: {'solver': 'saga', 'C': 3.331221281768191, 'l1_ratio': 0.46144293489719485, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020503641743490385, 'max_iter': 3962}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 23/30 [01:10<00:11,  1.61s/it]

[I 2026-06-04 16:45:28,043] Trial 59 pruned.

Best trial: 51. Best value: 0.102405:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 24/30 [01:17<00:17,  2.95s/it]

[I 2026-06-04 16:45:34,183] Trial 53 finished with value: 0.1024094508225423 and parameters: {'solver': 'saga', 'C': 34.20720725486378, 'l1_ratio': 0.6518229841815191, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005686570402978123, 'max_iter': 4678}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 25/30 [01:20<00:15,  3.19s/it]

[I 2026-06-04 16:45:37,928] Trial 58 pruned.
[I 2026-06-04 16:45:37,941] Trial 57 pruned.

Best trial: 51. Best value: 0.102405:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 27/30 [01:47<00:23,  7.75s/it]

[I 2026-06-04 16:46:04,159] Trial 55 finished with value: 0.10240790766638046 and parameters: {'solver': 'saga', 'C': 1.5618891808771356, 'l1_ratio': 0.32755090432368883, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003306239794535687, 'max_iter': 3325}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 28/30 [01:53<00:14,  7.32s/it]

[I 2026-06-04 16:46:10,153] Trial 56 finished with value: 0.10240794640363877 and parameters: {'solver': 'saga', 'C': 1.248725444175947, 'l1_ratio': 0.3763498868060859, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019162023473349643, 'max_iter': 4090}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 29/30 [02:26<00:14, 14.09s/it]

[I 2026-06-04 16:46:43,453] Trial 34 finished with value: 0.10240839475615535 and parameters: {'solver': 'saga', 'C': 4.735435152940276, 'l1_ratio': 0.4482300101988604, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019965845212452694, 'max_iter': 4943}. Best is trial 51 with value: 0.10240530596157663.

Best trial: 51. Best value: 0.102405: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [02:45<00:00,  5.50s/it]

[I 2026-06-04 16:47:02,075] Trial 54 finished with value: 0.10240893293505852 and parameters: {'solver': 'saga', 'C': 19.1083000578225, 'l1_ratio': 0.3370590670101929, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00026240000267621573, 'max_iter': 3312}. Best is trial 51 with value: 0.10240530596157663.

In [23]:
lg = LogisticRegression(**study.best_params).fit(X_train, y_train.class_encoded)
train_proba = cross_val_predict(lg, X_train, y_train.class_encoded, cv=StratifiedKFold(shuffle=True, random_state=42, n_splits=5), n_jobs=-1, method='predict_proba')

In [24]:
test_proba = lg.predict_proba(X_test)

In [25]:
optimizer = MulticlassThresholdOptimizer()
optimizer.fit(train_proba, y_train.class_encoded)

MulticlassThresholdOptimizer()

In [26]:
final_predictions_idx = optimizer.predict(test_proba)

class_mapping = {0: 'GALAXY', 1: 'QSO', 2: 'STAR'}
sub_labels = [class_mapping[idx] for idx in final_predictions_idx]

# Submission

In [27]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lg.csv', index=False)

In [28]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [29]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'cat_0', 'cat_1', 'xgb_0', 'xgb_1', 'hist_0',
       'hist_1', 'extra_0', 'extra_1', 'rf_0', 'rf_1'],
      dtype='str')