# Imports

In [1]:
import optuna

import numpy as np
import pandas as pd

from utils import load_pickle

from sklearn.metrics import balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
to_drop = ['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0', 'xgb_1', 'xgb_2']

X_train = pd.read_parquet('../data/X_train_stacking_layer_two.parquet') #.drop(to_drop, axis=1)
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_two.parquet') #.drop(to_drop, axis=1)

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.999910,0.000083,0.000007,0.999866,0.000124,0.000010,0.999928,0.000070,0.000003,0.988210,0.004367,0.007423,0.999210,0.000790,0.000000
1,0.992961,0.000411,0.006628,0.991422,0.000567,0.008011,0.992562,0.000566,0.006872,0.986847,0.004779,0.008373,0.988522,0.001245,0.010233
2,0.000109,0.999858,0.000033,0.000162,0.999819,0.000019,0.000030,0.999962,0.000008,0.009897,0.988895,0.001208,0.002604,0.997396,0.000000
3,0.999805,0.000187,0.000009,0.999766,0.000223,0.000010,0.999837,0.000159,0.000004,0.988202,0.004372,0.007426,0.999098,0.000902,0.000000
4,0.998393,0.001560,0.000047,0.998544,0.001413,0.000043,0.998238,0.001711,0.000051,0.987966,0.004405,0.007629,0.998207,0.001793,0.000000

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.997841,0.002113,0.000045,0.997856,0.001945,0.000199,0.998030,0.001934,0.000036,0.987950,0.004507,0.007543,0.997783,0.002217,0.000000
1,0.996887,0.003080,0.000033,0.997599,0.002381,0.000020,0.996744,0.003240,0.000016,0.987886,0.004549,0.007565,0.997324,0.002676,0.000000
2,0.998244,0.001026,0.000731,0.998669,0.000563,0.000768,0.998349,0.000750,0.000901,0.987787,0.004504,0.007709,0.998949,0.001051,0.000000
3,0.000658,0.000086,0.999256,0.001490,0.000130,0.998380,0.000538,0.000138,0.999324,0.013634,0.004166,0.982199,0.000000,0.002127,0.997873
4,0.999840,0.000151,0.000009,0.999810,0.000178,0.000012,0.999880,0.000116,0.000004,0.988019,0.004456,0.007524,0.999069,0.000931,0.000000

# Machine Learning

In [6]:
def objective(trial, X, y):
    
    l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)
    C = trial.suggest_float("C", 1e-5, 100.0, log=True)
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced"])
    fit_intercept = trial.suggest_categorical("fit_intercept", [True, False])
    tol = trial.suggest_float("tol", 1e-6, 1e-2, log=True)
    max_iter = trial.suggest_int("max_iter", 1000, 5000)

    w0 = trial.suggest_float('weight_class_0', 0.05, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.05, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):
        
        X_train_fold, X_valid_fold = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train_fold, y_valid_fold = y.iloc[train_idx], y.iloc[valid_idx]

        model = LogisticRegression(
            solver="saga",
            C=C,
            l1_ratio=l1_ratio,
            class_weight=class_weight,
            fit_intercept=fit_intercept,
            tol=tol,
            max_iter=max_iter,
            random_state=42,
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)
        
        weighted_probas = proba * weights
        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.class_encoded), 
    n_trials=90, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-26 15:18:10,077] A new study created in memory with name: no-name-1573af92-10b9-45df-ac33-1115b570d65c
Best trial: 5. Best value: 0.923371:   1%|█▍                                                                                                                            | 1/90 [00:18<27:31, 18.56s/it]

[I 2026-06-26 15:18:28,633] Trial 5 finished with value: 0.9233714957151508 and parameters: {'l1_ratio': 0.456884762008827, 'C': 0.09476487698300906, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.009463243563337826, 'max_iter': 1761, 'weight_class_0': 9.328742403456971, 'weight_class_1': 0.7991707725009226, 'weight_class_2': 0.3154189417165417}. Best is trial 5 with value: 0.9233714957151508.

Best trial: 0. Best value: 0.928678:   2%|██▊                                                                                                                           | 2/90 [00:26<17:39, 12.04s/it]

[I 2026-06-26 15:18:36,109] Trial 0 finished with value: 0.9286775741408718 and parameters: {'l1_ratio': 0.2579161679256694, 'C': 0.46671947673357883, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002278321757851549, 'max_iter': 2506, 'weight_class_0': 2.909360210945182, 'weight_class_1': 0.15027295775722108, 'weight_class_2': 1.6194657429077404}. Best is trial 0 with value: 0.9286775741408718.

Best trial: 9. Best value: 0.945169:   3%|████▏                                                                                                                         | 3/90 [00:27<10:24,  7.18s/it]

[I 2026-06-26 15:18:37,497] Trial 9 finished with value: 0.9451694285202004 and parameters: {'l1_ratio': 0.8921583407611517, 'C': 0.0004527043766366511, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001009495929853975, 'max_iter': 1042, 'weight_class_0': 2.3910647798679774, 'weight_class_1': 1.0630475410964222, 'weight_class_2': 0.9925222800333221}. Best is trial 9 with value: 0.9451694285202004.

Best trial: 4. Best value: 0.95413:   4%|█████▋                                                                                                                         | 4/90 [00:28<06:51,  4.78s/it]

[I 2026-06-26 15:18:38,597] Trial 4 finished with value: 0.9541299024320647 and parameters: {'l1_ratio': 0.5454859889419199, 'C': 8.50202926344212, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0054416886426727805, 'max_iter': 4016, 'weight_class_0': 0.1195850410756883, 'weight_class_1': 2.731584156411981, 'weight_class_2': 0.12778998295519856}. Best is trial 4 with value: 0.9541299024320647.

Best trial: 4. Best value: 0.95413:   6%|███████                                                                                                                        | 5/90 [00:29<05:03,  3.57s/it]

[I 2026-06-26 15:18:40,019] Trial 6 finished with value: 0.6483075331321857 and parameters: {'l1_ratio': 0.8946823689166019, 'C': 4.047865828666752e-05, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007229331382601671, 'max_iter': 1343, 'weight_class_0': 5.786442971489399, 'weight_class_1': 3.989423354538948, 'weight_class_2': 1.656976147036758}. Best is trial 4 with value: 0.9541299024320647.

Best trial: 7. Best value: 0.966257:   7%|████████▍                                                                                                                     | 6/90 [00:31<03:59,  2.86s/it]

[I 2026-06-26 15:18:41,495] Trial 7 finished with value: 0.9662572400379716 and parameters: {'l1_ratio': 0.09388518982273708, 'C': 0.0027771512557332677, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007160120094325022, 'max_iter': 2483, 'weight_class_0': 0.07881533959602297, 'weight_class_1': 0.793371101040205, 'weight_class_2': 1.53935308849017}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:   8%|█████████▊                                                                                                                    | 7/90 [00:34<04:09,  3.01s/it]

[I 2026-06-26 15:18:44,817] Trial 10 pruned.

Best trial: 7. Best value: 0.966257:   9%|███████████▏                                                                                                                  | 8/90 [00:35<03:08,  2.30s/it]

[I 2026-06-26 15:18:45,595] Trial 3 finished with value: 0.9657890008643267 and parameters: {'l1_ratio': 0.542954969969617, 'C': 2.320316638484963, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005221123474650162, 'max_iter': 1100, 'weight_class_0': 0.7888314872457539, 'weight_class_1': 1.561884389371202, 'weight_class_2': 4.979619070948559}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  10%|████████████▌                                                                                                                 | 9/90 [00:37<02:53,  2.14s/it]

[I 2026-06-26 15:18:47,382] Trial 2 pruned.

Best trial: 7. Best value: 0.966257:  11%|█████████████▉                                                                                                               | 10/90 [00:37<02:08,  1.60s/it]

[I 2026-06-26 15:18:47,793] Trial 1 finished with value: 0.9649310750081426 and parameters: {'l1_ratio': 0.333138313795181, 'C': 0.10582778206752441, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001975400268936386, 'max_iter': 2984, 'weight_class_0': 0.2795521085233793, 'weight_class_1': 0.10631789333810342, 'weight_class_2': 1.0759845816959377}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  12%|███████████████▎                                                                                                             | 11/90 [00:40<02:37,  2.00s/it]

[I 2026-06-26 15:18:50,691] Trial 13 pruned.

Best trial: 7. Best value: 0.966257:  13%|████████████████▋                                                                                                            | 12/90 [00:44<03:24,  2.62s/it]

[I 2026-06-26 15:18:54,731] Trial 12 finished with value: 0.9623965666491892 and parameters: {'l1_ratio': 0.05198517725851759, 'C': 6.922308260867442e-05, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0017383130384072945, 'max_iter': 4920, 'weight_class_0': 0.11566680442736813, 'weight_class_1': 0.15757627990811313, 'weight_class_2': 0.20801513162387372}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  14%|██████████████████                                                                                                           | 13/90 [00:49<04:24,  3.44s/it]

[I 2026-06-26 15:19:00,052] Trial 11 finished with value: 0.9613633595222287 and parameters: {'l1_ratio': 0.04883306231931661, 'C': 23.240322342427007, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00030482991022399015, 'max_iter': 1492, 'weight_class_0': 0.24569890120571336, 'weight_class_1': 1.6527416374379473, 'weight_class_2': 0.11237573989427503}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  16%|███████████████████▍                                                                                                         | 14/90 [00:51<03:47,  2.99s/it]

[I 2026-06-26 15:19:02,017] Trial 17 pruned.

Best trial: 7. Best value: 0.966257:  17%|████████████████████▊                                                                                                        | 15/90 [00:54<03:43,  2.98s/it]

[I 2026-06-26 15:19:04,961] Trial 14 pruned.

Best trial: 7. Best value: 0.966257:  18%|██████████████████████▏                                                                                                      | 16/90 [00:55<02:47,  2.27s/it]

[I 2026-06-26 15:19:05,580] Trial 19 pruned.

Best trial: 7. Best value: 0.966257:  19%|███████████████████████▌                                                                                                     | 17/90 [00:57<02:36,  2.15s/it]

[I 2026-06-26 15:19:07,443] Trial 16 finished with value: 0.9650669977217712 and parameters: {'l1_ratio': 0.5952199456942541, 'C': 0.0013672706235001615, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009350716055930588, 'max_iter': 1186, 'weight_class_0': 0.11275715248748372, 'weight_class_1': 0.10925041602648186, 'weight_class_2': 0.4678591354568415}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  20%|█████████████████████████                                                                                                    | 18/90 [00:58<02:11,  1.82s/it]

[I 2026-06-26 15:19:08,509] Trial 8 finished with value: 0.9641215589998744 and parameters: {'l1_ratio': 0.6830613773660525, 'C': 0.12889129061562235, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3206840275401798e-05, 'max_iter': 4623, 'weight_class_0': 0.05405449811111229, 'weight_class_1': 2.044211172186655, 'weight_class_2': 1.6929870698818743}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  21%|██████████████████████████▍                                                                                                  | 19/90 [01:00<02:12,  1.87s/it]

[I 2026-06-26 15:19:10,493] Trial 15 pruned.

Best trial: 7. Best value: 0.966257:  22%|███████████████████████████▊                                                                                                 | 20/90 [01:06<03:33,  3.04s/it]

[I 2026-06-26 15:19:16,270] Trial 18 pruned.

Best trial: 7. Best value: 0.966257:  23%|█████████████████████████████▏                                                                                               | 21/90 [01:17<06:13,  5.41s/it]

[I 2026-06-26 15:19:27,204] Trial 27 pruned.

Best trial: 7. Best value: 0.966257:  24%|██████████████████████████████▌                                                                                              | 22/90 [01:21<05:42,  5.04s/it]

[I 2026-06-26 15:19:31,382] Trial 30 pruned.

Best trial: 7. Best value: 0.966257:  26%|███████████████████████████████▉                                                                                             | 23/90 [01:25<05:11,  4.65s/it]

[I 2026-06-26 15:19:35,106] Trial 24 finished with value: 0.9622371396120359 and parameters: {'l1_ratio': 0.7005637678048362, 'C': 0.00787354213534602, 'class_weight': None, 'fit_intercept': True, 'tol': 8.934016949451054e-05, 'max_iter': 2131, 'weight_class_0': 0.6772560410026762, 'weight_class_1': 0.41208741160840345, 'weight_class_2': 9.930415794440913}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  27%|█████████████████████████████████▎                                                                                           | 24/90 [01:29<05:07,  4.66s/it]

[I 2026-06-26 15:19:39,783] Trial 25 finished with value: 0.9633078790672756 and parameters: {'l1_ratio': 0.6848177630647293, 'C': 0.005468879756398284, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7865149465857136e-05, 'max_iter': 2211, 'weight_class_0': 0.5955131903830106, 'weight_class_1': 0.4798396664162375, 'weight_class_2': 7.616455344232718}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  28%|██████████████████████████████████▋                                                                                          | 25/90 [01:35<05:22,  4.96s/it]

[I 2026-06-26 15:19:45,456] Trial 29 finished with value: 0.9627732147219223 and parameters: {'l1_ratio': 0.7449620734609232, 'C': 0.012497291910072218, 'class_weight': None, 'fit_intercept': True, 'tol': 3.91177193619823e-05, 'max_iter': 2101, 'weight_class_0': 0.41936056829445617, 'weight_class_1': 0.3459934323544001, 'weight_class_2': 7.929565072822603}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  29%|████████████████████████████████████                                                                                         | 26/90 [01:45<07:01,  6.58s/it]

[I 2026-06-26 15:19:55,821] Trial 32 finished with value: 0.9650790287921571 and parameters: {'l1_ratio': 0.37448522122054284, 'C': 0.007210581984092659, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006784214467618952, 'max_iter': 1983, 'weight_class_0': 0.5635299459703403, 'weight_class_1': 0.41597162774108837, 'weight_class_2': 0.5402531563495326}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  30%|█████████████████████████████████████▌                                                                                       | 27/90 [01:48<05:36,  5.34s/it]

[I 2026-06-26 15:19:58,253] Trial 22 finished with value: 0.9648609154060086 and parameters: {'l1_ratio': 0.032656491350565364, 'C': 83.61085598291972, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014452909021456462, 'max_iter': 2128, 'weight_class_0': 0.5681570158155581, 'weight_class_1': 0.7036255069952148, 'weight_class_2': 9.579070377373842}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  31%|██████████████████████████████████████▉                                                                                      | 28/90 [02:07<09:55,  9.61s/it]

[I 2026-06-26 15:20:17,824] Trial 35 finished with value: 0.9632661351026874 and parameters: {'l1_ratio': 0.14554388325482848, 'C': 1.7089656109003135, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005241463091368615, 'max_iter': 1004, 'weight_class_0': 0.18950467116480849, 'weight_class_1': 0.05110767982062382, 'weight_class_2': 0.6758694745734001}. Best is trial 7 with value: 0.9662572400379716.
[I 2026-06-26 15:20:17,893] Trial 33 finished with value: 0.963763408601427 and parameters: {'l1_ratio': 0.16007208869929695, 'C': 3.0134776153254403, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005481452870712571, 'max_iter': 1018, 'weight_class_0': 0.1921021069636887, 'weight_class_1': 0.057020364841653785, 'weight_class_2': 0.7471777466177726}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  33%|█████████████████████████████████████████▋                                                                                   | 30/90 [02:13<06:31,  6.52s/it]

[I 2026-06-26 15:20:23,665] Trial 36 finished with value: 0.9644115839568315 and parameters: {'l1_ratio': 0.15427853673830477, 'C': 1.7472073143272928, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005749490021670422, 'max_iter': 1129, 'weight_class_0': 0.18619035292642838, 'weight_class_1': 0.0616391602475071, 'weight_class_2': 0.6514525552237361}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  34%|███████████████████████████████████████████                                                                                  | 31/90 [02:25<07:40,  7.80s/it]

[I 2026-06-26 15:20:35,351] Trial 41 pruned.

Best trial: 7. Best value: 0.966257:  36%|████████████████████████████████████████████▍                                                                                | 32/90 [02:28<06:28,  6.70s/it]

[I 2026-06-26 15:20:38,945] Trial 40 finished with value: 0.9662129755291435 and parameters: {'l1_ratio': 0.3302136255937931, 'C': 0.024797893795875728, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004690791707448541, 'max_iter': 1696, 'weight_class_0': 1.2578110265271238, 'weight_class_1': 1.1495500556081877, 'weight_class_2': 2.7934015771998837}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  37%|█████████████████████████████████████████████▊                                                                               | 33/90 [02:31<05:18,  5.58s/it]

[I 2026-06-26 15:20:41,529] Trial 38 finished with value: 0.965064915023602 and parameters: {'l1_ratio': 0.1640666021494167, 'C': 1.8539304338216451, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00044656264694760216, 'max_iter': 1777, 'weight_class_0': 1.2946475250004013, 'weight_class_1': 1.3479096745442734, 'weight_class_2': 0.8529946970724959}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  38%|███████████████████████████████████████████████▏                                                                             | 34/90 [02:31<03:50,  4.12s/it]

[I 2026-06-26 15:20:41,902] Trial 34 finished with value: 0.96462275879184 and parameters: {'l1_ratio': 0.3966923629923032, 'C': 1.9124247968093593, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004933132676643995, 'max_iter': 1008, 'weight_class_0': 0.1801825357576253, 'weight_class_1': 0.06000666116977015, 'weight_class_2': 0.5514663088393457}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  39%|████████████████████████████████████████████████▌                                                                            | 35/90 [02:33<03:08,  3.43s/it]

[I 2026-06-26 15:20:43,600] Trial 20 pruned.

Best trial: 7. Best value: 0.966257:  40%|██████████████████████████████████████████████████                                                                           | 36/90 [02:37<03:17,  3.65s/it]

[I 2026-06-26 15:20:47,794] Trial 39 finished with value: 0.9647385494248617 and parameters: {'l1_ratio': 0.4128915445478754, 'C': 2.545509232499216, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003874211681221425, 'max_iter': 1753, 'weight_class_0': 1.2275263461859633, 'weight_class_1': 1.3856765239112698, 'weight_class_2': 0.7450561473839451}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  41%|███████████████████████████████████████████████████▍                                                                         | 37/90 [02:41<03:15,  3.69s/it]

[I 2026-06-26 15:20:51,584] Trial 42 pruned.

Best trial: 7. Best value: 0.966257:  42%|████████████████████████████████████████████████████▊                                                                        | 38/90 [02:47<03:40,  4.25s/it]

[I 2026-06-26 15:20:57,150] Trial 37 finished with value: 0.9641233228819945 and parameters: {'l1_ratio': 0.15536955755358295, 'C': 5.897587650650619, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00045171200527301727, 'max_iter': 1752, 'weight_class_0': 1.780278012404109, 'weight_class_1': 1.7893823578195645, 'weight_class_2': 0.7931755002283118}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  43%|██████████████████████████████████████████████████████▏                                                                      | 39/90 [02:50<03:29,  4.12s/it]

[I 2026-06-26 15:21:00,955] Trial 45 finished with value: 0.9647632954110211 and parameters: {'l1_ratio': 0.2838754772283373, 'C': 0.3297583498325005, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009215800720663173, 'max_iter': 2989, 'weight_class_0': 1.1457140230427008, 'weight_class_1': 0.505318627769575, 'weight_class_2': 5.708742935358107}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  44%|███████████████████████████████████████████████████████▌                                                                     | 40/90 [02:51<02:28,  2.97s/it]

[I 2026-06-26 15:21:01,188] Trial 43 finished with value: 0.965186749131948 and parameters: {'l1_ratio': 0.36897615790326743, 'C': 0.0018715023394857114, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003563314700527427, 'max_iter': 1797, 'weight_class_0': 1.259134933600281, 'weight_class_1': 1.0451985892940647, 'weight_class_2': 5.819410727322739}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  46%|████████████████████████████████████████████████████████▉                                                                    | 41/90 [02:52<01:59,  2.44s/it]

[I 2026-06-26 15:21:02,406] Trial 48 pruned.

Best trial: 7. Best value: 0.966257:  47%|██████████████████████████████████████████████████████████▎                                                                  | 42/90 [02:53<01:43,  2.16s/it]

[I 2026-06-26 15:21:03,927] Trial 46 finished with value: 0.9655609035961724 and parameters: {'l1_ratio': 0.452227594349862, 'C': 0.5122055822121877, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00938257026494087, 'max_iter': 1903, 'weight_class_0': 1.2215090230135186, 'weight_class_1': 0.5431247792309818, 'weight_class_2': 1.2074503939734336}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  48%|███████████████████████████████████████████████████████████▋                                                                 | 43/90 [02:55<01:27,  1.86s/it]

[I 2026-06-26 15:21:05,064] Trial 44 finished with value: 0.9650241805358837 and parameters: {'l1_ratio': 0.35662389161728636, 'C': 0.41956880527774226, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004215333686025221, 'max_iter': 2985, 'weight_class_0': 0.9498753794462444, 'weight_class_1': 0.5520967762645094, 'weight_class_2': 5.111420388717864}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  49%|█████████████████████████████████████████████████████████████                                                                | 44/90 [02:57<01:30,  1.97s/it]

[I 2026-06-26 15:21:07,301] Trial 47 finished with value: 0.9658828073449545 and parameters: {'l1_ratio': 0.30201329246101327, 'C': 0.30511971300699836, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009945254346326007, 'max_iter': 2894, 'weight_class_0': 0.9483861234819755, 'weight_class_1': 0.539994190127573, 'weight_class_2': 1.2082066257366875}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  50%|██████████████████████████████████████████████████████████████▌                                                              | 45/90 [02:58<01:18,  1.75s/it]

[I 2026-06-26 15:21:08,539] Trial 49 pruned.

Best trial: 7. Best value: 0.966257:  52%|█████████████████████████████████████████████████████████████████▎                                                           | 47/90 [03:02<01:15,  1.75s/it]

[I 2026-06-26 15:21:12,651] Trial 50 pruned.
[I 2026-06-26 15:21:12,752] Trial 51 pruned.

Best trial: 7. Best value: 0.966257:  53%|██████████████████████████████████████████████████████████████████▋                                                          | 48/90 [03:04<01:13,  1.75s/it]

[I 2026-06-26 15:21:14,501] Trial 52 pruned.

Best trial: 7. Best value: 0.966257:  54%|████████████████████████████████████████████████████████████████████                                                         | 49/90 [03:05<00:59,  1.45s/it]

[I 2026-06-26 15:21:15,253] Trial 53 pruned.

Best trial: 7. Best value: 0.966257:  56%|█████████████████████████████████████████████████████████████████████▍                                                       | 50/90 [03:06<00:54,  1.37s/it]

[I 2026-06-26 15:21:16,448] Trial 54 pruned.

Best trial: 7. Best value: 0.966257:  57%|██████████████████████████████████████████████████████████████████████▊                                                      | 51/90 [03:10<01:24,  2.16s/it]

[I 2026-06-26 15:21:20,451] Trial 55 pruned.

Best trial: 7. Best value: 0.966257:  59%|█████████████████████████████████████████████████████████████████████████▌                                                   | 53/90 [03:17<01:33,  2.53s/it]

[I 2026-06-26 15:21:27,198] Trial 26 pruned.
[I 2026-06-26 15:21:27,368] Trial 57 pruned.

Best trial: 7. Best value: 0.966257:  60%|███████████████████████████████████████████████████████████████████████████                                                  | 54/90 [03:19<01:29,  2.48s/it]

[I 2026-06-26 15:21:29,755] Trial 59 pruned.

Best trial: 7. Best value: 0.966257:  61%|████████████████████████████████████████████████████████████████████████████▍                                                | 55/90 [03:23<01:42,  2.93s/it]

[I 2026-06-26 15:21:33,699] Trial 21 pruned.

Best trial: 7. Best value: 0.966257:  62%|█████████████████████████████████████████████████████████████████████████████▊                                               | 56/90 [03:24<01:14,  2.20s/it]

[I 2026-06-26 15:21:34,230] Trial 56 finished with value: 0.9660454519245535 and parameters: {'l1_ratio': 0.48632678695780424, 'C': 0.04462765637599123, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002364130908364912, 'max_iter': 1412, 'weight_class_0': 1.6160273810064618, 'weight_class_1': 1.0098634841809817, 'weight_class_2': 2.9514827578746634}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  63%|███████████████████████████████████████████████████████████████████████████████▏                                             | 57/90 [03:26<01:15,  2.28s/it]

[I 2026-06-26 15:21:36,695] Trial 62 pruned.

Best trial: 7. Best value: 0.966257:  64%|████████████████████████████████████████████████████████████████████████████████▌                                            | 58/90 [03:28<01:10,  2.21s/it]

[I 2026-06-26 15:21:38,755] Trial 58 finished with value: 0.9657979012316215 and parameters: {'l1_ratio': 0.2206271356400501, 'C': 0.1939143712332768, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002397300881380058, 'max_iter': 3301, 'weight_class_0': 1.5361549554003324, 'weight_class_1': 2.9439128427135315, 'weight_class_2': 2.4203649027994953}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  66%|█████████████████████████████████████████████████████████████████████████████████▉                                           | 59/90 [03:32<01:21,  2.62s/it]

[I 2026-06-26 15:21:42,321] Trial 60 finished with value: 0.9648989705310094 and parameters: {'l1_ratio': 0.5543006239512922, 'C': 0.21954721263886834, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002288886641671028, 'max_iter': 3334, 'weight_class_0': 0.3842687622599623, 'weight_class_1': 0.26320980507268077, 'weight_class_2': 2.357027698272822}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  67%|███████████████████████████████████████████████████████████████████████████████████▎                                         | 60/90 [03:34<01:14,  2.47s/it]

[I 2026-06-26 15:21:44,431] Trial 61 finished with value: 0.9651151274004939 and parameters: {'l1_ratio': 0.21195149826442222, 'C': 0.879918132734408, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002440898046309765, 'max_iter': 3468, 'weight_class_0': 0.41489427731195183, 'weight_class_1': 0.2510106849881989, 'weight_class_2': 2.123889274980751}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  68%|████████████████████████████████████████████████████████████████████████████████████▋                                        | 61/90 [03:36<01:07,  2.34s/it]

[I 2026-06-26 15:21:46,475] Trial 63 pruned.

Best trial: 7. Best value: 0.966257:  69%|██████████████████████████████████████████████████████████████████████████████████████                                       | 62/90 [03:47<02:21,  5.05s/it]

[I 2026-06-26 15:21:57,835] Trial 65 finished with value: 0.9650112252721827 and parameters: {'l1_ratio': 0.5484464028046987, 'C': 0.07170322048543133, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001563138312423069, 'max_iter': 2332, 'weight_class_0': 1.4169172997439914, 'weight_class_1': 3.4286561837080374, 'weight_class_2': 1.4867158297414664}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  70%|███████████████████████████████████████████████████████████████████████████████████████▌                                     | 63/90 [03:48<01:40,  3.73s/it]

[I 2026-06-26 15:21:58,494] Trial 64 finished with value: 0.9647704604180714 and parameters: {'l1_ratio': 0.22475370565647682, 'C': 15.901875067095146, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002709263877666601, 'max_iter': 3219, 'weight_class_0': 0.43468082305148203, 'weight_class_1': 2.8248791117188694, 'weight_class_2': 1.960556390321309}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  71%|████████████████████████████████████████████████████████████████████████████████████████▉                                    | 64/90 [03:51<01:31,  3.51s/it]

[I 2026-06-26 15:22:01,487] Trial 71 pruned.

Best trial: 7. Best value: 0.966257:  72%|██████████████████████████████████████████████████████████████████████████████████████████▎                                  | 65/90 [03:56<01:42,  4.11s/it]

[I 2026-06-26 15:22:07,016] Trial 68 finished with value: 0.9647471337162855 and parameters: {'l1_ratio': 0.56830296738826, 'C': 0.1047209915637248, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012538907288431695, 'max_iter': 3554, 'weight_class_0': 0.4603953946046419, 'weight_class_1': 3.2161345104243937, 'weight_class_2': 1.3792420538301502}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  73%|███████████████████████████████████████████████████████████████████████████████████████████▋                                 | 66/90 [03:57<01:15,  3.15s/it]

[I 2026-06-26 15:22:07,929] Trial 69 finished with value: 0.965014475604572 and parameters: {'l1_ratio': 0.5422289349583621, 'C': 0.051118690003246633, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0013411025424557995, 'max_iter': 3640, 'weight_class_0': 1.5051141490075182, 'weight_class_1': 3.849908845176937, 'weight_class_2': 1.5599456986276234}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  74%|█████████████████████████████████████████████████████████████████████████████████████████████                                | 67/90 [04:00<01:08,  2.98s/it]

[I 2026-06-26 15:22:10,495] Trial 70 finished with value: 0.9648233136668392 and parameters: {'l1_ratio': 0.6148954745858923, 'C': 0.06362239396369855, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0013061470999979159, 'max_iter': 3739, 'weight_class_0': 2.360143327714822, 'weight_class_1': 3.1971508266357174, 'weight_class_2': 1.5165984726871375}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▍                              | 68/90 [04:05<01:17,  3.53s/it]

[I 2026-06-26 15:22:15,316] Trial 72 finished with value: 0.9651378791896951 and parameters: {'l1_ratio': 0.09658390256191973, 'C': 0.07304444218170744, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0014092473631016449, 'max_iter': 2801, 'weight_class_0': 2.4825792899137764, 'weight_class_1': 2.462820638080959, 'weight_class_2': 1.5516487780330863}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  77%|███████████████████████████████████████████████████████████████████████████████████████████████▊                             | 69/90 [04:09<01:15,  3.61s/it]

[I 2026-06-26 15:22:19,118] Trial 66 finished with value: 0.9652481921062019 and parameters: {'l1_ratio': 0.5839247169142805, 'C': 0.7624136653472718, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013277485411282118, 'max_iter': 2768, 'weight_class_0': 1.5204110524237784, 'weight_class_1': 2.814801822666003, 'weight_class_2': 1.6812654705132426}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 70/90 [04:10<01:00,  3.03s/it]

[I 2026-06-26 15:22:20,778] Trial 67 finished with value: 0.9652274553780144 and parameters: {'l1_ratio': 0.5343114269571894, 'C': 0.6968497765827256, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001264866036386281, 'max_iter': 2408, 'weight_class_0': 1.465038632371642, 'weight_class_1': 2.504589333942547, 'weight_class_2': 1.4976340348480552}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 71/90 [04:11<00:44,  2.33s/it]

[I 2026-06-26 15:22:21,473] Trial 78 pruned.

Best trial: 7. Best value: 0.966257:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████                         | 72/90 [04:16<00:54,  3.01s/it]

[I 2026-06-26 15:22:26,094] Trial 79 pruned.

Best trial: 7. Best value: 0.966257:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 73/90 [04:16<00:37,  2.20s/it]

[I 2026-06-26 15:22:26,381] Trial 76 finished with value: 0.9656333433285251 and parameters: {'l1_ratio': 0.11083609258242268, 'C': 0.01924860565981073, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.006859694412888196, 'max_iter': 3734, 'weight_class_0': 0.9426551579277699, 'weight_class_1': 0.7637267033555011, 'weight_class_2': 4.427510943810403}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 74/90 [04:18<00:34,  2.17s/it]

[I 2026-06-26 15:22:28,498] Trial 73 finished with value: 0.9650645705665457 and parameters: {'l1_ratio': 0.4430153598299978, 'C': 0.09116745601492397, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001141489534761645, 'max_iter': 3572, 'weight_class_0': 2.202263154175439, 'weight_class_1': 0.74716833789403, 'weight_class_2': 4.212099027995641}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 7. Best value: 0.966257:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 75/90 [04:18<00:24,  1.63s/it]

[I 2026-06-26 15:22:28,864] Trial 74 finished with value: 0.9650128899543695 and parameters: {'l1_ratio': 0.44756911072740113, 'C': 0.05675769372136018, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010607464829603434, 'max_iter': 3651, 'weight_class_0': 2.190645758578799, 'weight_class_1': 0.7264824167104621, 'weight_class_2': 4.443521090070791}. Best is trial 7 with value: 0.9662572400379716.

Best trial: 75. Best value: 0.966258:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 76/90 [04:20<00:21,  1.55s/it]

[I 2026-06-26 15:22:30,238] Trial 75 finished with value: 0.9662583810460816 and parameters: {'l1_ratio': 0.4401377688399122, 'C': 0.017056517383486847, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012766148780469333, 'max_iter': 3772, 'weight_class_0': 2.273407690558069, 'weight_class_1': 2.1378716869670944, 'weight_class_2': 4.479888997485939}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 77/90 [04:21<00:19,  1.53s/it]

[I 2026-06-26 15:22:31,695] Trial 81 pruned.

Best trial: 75. Best value: 0.966258:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 78/90 [04:23<00:17,  1.48s/it]

[I 2026-06-26 15:22:33,081] Trial 80 pruned.

Best trial: 75. Best value: 0.966258:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 79/90 [04:27<00:25,  2.28s/it]

[I 2026-06-26 15:22:37,226] Trial 82 pruned.

Best trial: 75. Best value: 0.966258:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 80/90 [04:28<00:18,  1.89s/it]

[I 2026-06-26 15:22:38,196] Trial 77 finished with value: 0.9657214968980368 and parameters: {'l1_ratio': 0.1068546064928255, 'C': 0.014852482947999048, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008368438460718019, 'max_iter': 1532, 'weight_class_0': 0.9991050480575787, 'weight_class_1': 0.7411543963839856, 'weight_class_2': 4.125952592085361}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 81/90 [04:37<00:38,  4.23s/it]

[I 2026-06-26 15:22:47,897] Trial 89 pruned.

Best trial: 75. Best value: 0.966258:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 82/90 [04:40<00:30,  3.81s/it]

[I 2026-06-26 15:22:50,724] Trial 84 finished with value: 0.9647212593890275 and parameters: {'l1_ratio': 0.4243271970835327, 'C': 0.003831279294181933, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0037437335045585572, 'max_iter': 4107, 'weight_class_0': 0.7882517240981645, 'weight_class_1': 1.7723448802597954, 'weight_class_2': 7.18789550955428}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 83/90 [04:42<00:21,  3.08s/it]

[I 2026-06-26 15:22:52,095] Trial 86 finished with value: 0.9651770562940738 and parameters: {'l1_ratio': 0.1289854386652326, 'C': 0.004216324807311157, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003634147713636904, 'max_iter': 3899, 'weight_class_0': 0.8259495991463308, 'weight_class_1': 1.1930092754181756, 'weight_class_2': 0.9793744356163236}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 84/90 [04:45<00:18,  3.11s/it]

[I 2026-06-26 15:22:55,287] Trial 85 finished with value: 0.9652481413363365 and parameters: {'l1_ratio': 0.29698526586802904, 'C': 0.00433041361217096, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000848011403883088, 'max_iter': 4193, 'weight_class_0': 0.7731794346671929, 'weight_class_1': 1.225188828474459, 'weight_class_2': 0.9581519691542295}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 85/90 [04:47<00:14,  2.81s/it]

[I 2026-06-26 15:22:57,376] Trial 88 finished with value: 0.9645390238631594 and parameters: {'l1_ratio': 0.2513550950545887, 'C': 0.014557894682736007, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008111286754504259, 'max_iter': 4249, 'weight_class_0': 0.7656822453944203, 'weight_class_1': 1.9928434293525363, 'weight_class_2': 7.498800468994533}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 86/90 [04:47<00:08,  2.03s/it]

[I 2026-06-26 15:22:57,601] Trial 87 finished with value: 0.96519564366107 and parameters: {'l1_ratio': 0.12218732547436005, 'C': 0.0053827854256960775, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008123180893938059, 'max_iter': 3858, 'weight_class_0': 5.052752862642631, 'weight_class_1': 4.764961131345942, 'weight_class_2': 6.128891719070427}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 87/90 [05:01<00:17,  5.75s/it]

[I 2026-06-26 15:23:12,038] Trial 31 pruned.

Best trial: 75. Best value: 0.966258:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 88/90 [05:03<00:09,  4.61s/it]

[I 2026-06-26 15:23:13,963] Trial 28 pruned.

Best trial: 75. Best value: 0.966258:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 89/90 [05:06<00:03,  3.86s/it]

[I 2026-06-26 15:23:16,080] Trial 83 pruned.

Best trial: 75. Best value: 0.966258: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [16:52<00:00, 11.25s/it]

[I 2026-06-26 15:35:02,890] Trial 23 finished with value: 0.9653480298808844 and parameters: {'l1_ratio': 0.677827677601056, 'C': 61.64977838909518, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001548241047833755, 'max_iter': 2183, 'weight_class_0': 0.5013982211485529, 'weight_class_1': 0.7180504345808008, 'weight_class_2': 7.387946288608322}. Best is trial 75 with value: 0.9662583810460816.

Best trial score:
0.9662583810460816

Best params:
{'l1_ratio': 0.4401377688399122, 'C': 0.017056517383486847, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012766148780469333, 'max_iter': 3772, 'weight_class_0': 2.273407690558069, 'weight_class_1': 2.1378716869670944, 'weight_class_2': 4.479888997485939}

In [21]:
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=80, n_jobs=-1, show_progress_bar=True)

print("\nBest trial score:")
print(study.best_trial.value)
print("\nBest params:")
print(study.best_trial.params)

Best trial: 75. Best value: 0.966258:   1%|█▌                                                                                                                           | 1/80 [00:15<20:52, 15.85s/it]

[I 2026-06-26 15:45:08,405] Trial 122 pruned.

Best trial: 75. Best value: 0.966258:   2%|███▏                                                                                                                         | 2/80 [00:24<15:00, 11.55s/it]

[I 2026-06-26 15:45:16,939] Trial 131 finished with value: 0.9658178227633112 and parameters: {'l1_ratio': 0.20654963379626076, 'C': 0.09400379967483277, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0030652450026953104, 'max_iter': 4708, 'weight_class_0': 2.1348314938374613, 'weight_class_1': 1.7975410138930061, 'weight_class_2': 1.9188438745228857}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:   4%|████▋                                                                                                                        | 3/80 [00:24<08:18,  6.48s/it]

[I 2026-06-26 15:45:17,371] Trial 127 finished with value: 0.9658007646282757 and parameters: {'l1_ratio': 0.30560225727528917, 'C': 0.09313884623448694, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002991888090521535, 'max_iter': 4700, 'weight_class_0': 2.1301739116069554, 'weight_class_1': 2.54533493541172, 'weight_class_2': 2.3185967433972254}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:   5%|██████▎                                                                                                                      | 4/80 [00:25<05:06,  4.03s/it]

[I 2026-06-26 15:45:17,648] Trial 121 finished with value: 0.9657800917264016 and parameters: {'l1_ratio': 0.3118564896028079, 'C': 0.08986285779538022, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002931817221316745, 'max_iter': 4748, 'weight_class_0': 2.1898855973158975, 'weight_class_1': 1.856918551222427, 'weight_class_2': 1.9259109919180726}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:   6%|███████▊                                                                                                                     | 5/80 [00:25<03:21,  2.68s/it]

[I 2026-06-26 15:45:17,955] Trial 128 finished with value: 0.9658743473396655 and parameters: {'l1_ratio': 0.31389902288116484, 'C': 0.1140451086149086, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00299058383285315, 'max_iter': 4732, 'weight_class_0': 2.228732996134244, 'weight_class_1': 1.8980836055679684, 'weight_class_2': 2.3042276775642816}. Best is trial 75 with value: 0.9662583810460816.

[I 2026-06-26 15:45:18,197] Trial 130 finished with value: 0.9657462614229984 and parameters: {'l1_ratio': 0.20605637466304752, 'C': 0.11539555077924125, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0030093015812032225, 'max_iter': 4701, 'weight_class_0': 2.224948641745097, 'weight_class_1': 1.9094049299484015, 'weight_class_2': 1.9316631765065058}. Best is trial 75 with value: 0.9662583810460816.
[I 2026-06-26 15:45:18,328] Trial 125 finished with value: 0.9657535786757047 and parameters: {'l1_ratio': 0.2088215374131997, 'C': 0.09715086788088848, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003015614334405717, 'max_iter': 4704, 'weight_class_0': 2.2083199900022916, 'weight_class_1': 1.8650309600092825, 'weight_class_2': 1.9042117289980511}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:   9%|██████████▉                                                                                                                  | 7/80 [00:25<01:35,  1.31s/it]

[I 2026-06-26 15:45:18,374] Trial 124 finished with value: 0.9657047893911251 and parameters: {'l1_ratio': 0.3075386410657426, 'C': 0.11717745683154238, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002943587073664172, 'max_iter': 4707, 'weight_class_0': 2.308509531133903, 'weight_class_1': 1.8467290708324653, 'weight_class_2': 1.8803651056714852}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  11%|██████████████                                                                                                               | 9/80 [00:26<00:52,  1.35it/s]

[I 2026-06-26 15:45:18,637] Trial 123 finished with value: 0.9657438902317006 and parameters: {'l1_ratio': 0.3102436657780357, 'C': 0.09722345250943443, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002811242338030031, 'max_iter': 4722, 'weight_class_0': 2.2039311124232146, 'weight_class_1': 1.818912163327394, 'weight_class_2': 1.8611450444395372}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  12%|███████████████▌                                                                                                            | 10/80 [00:26<00:44,  1.56it/s]

[I 2026-06-26 15:45:18,997] Trial 120 finished with value: 0.9655419011229007 and parameters: {'l1_ratio': 0.20593812196758124, 'C': 0.08308308754346555, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002980907510678341, 'max_iter': 4745, 'weight_class_0': 2.2193095123352675, 'weight_class_1': 2.5368516856550962, 'weight_class_2': 1.8820917734354954}. Best is trial 75 with value: 0.9662583810460816.
[I 2026-06-26 15:45:19,008] Trial 126 finished with value: 0.9657212638710764 and parameters: {'l1_ratio': 0.21298946984959358, 'C': 0.08149698705033835, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00300491776557064, 'max_iter': 4716, 'weight_class_0': 2.160030863979175, 'weight_class_1': 1.0720417462288818, 'weight_class_2': 2.399686921074762}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  15%|██████████████████▌                                                                                                         | 12/80 [00:31<01:30,  1.34s/it]

[I 2026-06-26 15:45:23,571] Trial 129 finished with value: 0.9656137940890837 and parameters: {'l1_ratio': 0.1446109985738963, 'C': 0.08648318149395655, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001011063971674348, 'max_iter': 4737, 'weight_class_0': 2.245919005855245, 'weight_class_1': 2.615393186468421, 'weight_class_2': 2.046084024132044}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  16%|████████████████████▏                                                                                                       | 13/80 [00:42<03:59,  3.58s/it]

[I 2026-06-26 15:45:34,556] Trial 132 finished with value: 0.9660388442357919 and parameters: {'l1_ratio': 0.30895041314780053, 'C': 0.0068524103305151905, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0031905076220231873, 'max_iter': 4690, 'weight_class_0': 2.2790435991388103, 'weight_class_1': 2.467312553066003, 'weight_class_2': 8.238575437016353}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  18%|█████████████████████▋                                                                                                      | 14/80 [00:42<03:11,  2.90s/it]

[I 2026-06-26 15:45:35,422] Trial 135 pruned.

Best trial: 75. Best value: 0.966258:  19%|███████████████████████▎                                                                                                    | 15/80 [00:43<02:30,  2.32s/it]

[I 2026-06-26 15:45:36,119] Trial 138 pruned.
[I 2026-06-26 15:45:36,159] Trial 140 pruned.

Best trial: 75. Best value: 0.966258:  22%|███████████████████████████▉                                                                                                | 18/80 [00:45<01:23,  1.34s/it]

[I 2026-06-26 15:45:37,862] Trial 142 pruned.
[I 2026-06-26 15:45:38,036] Trial 141 pruned.

Best trial: 75. Best value: 0.966258:  24%|█████████████████████████████▍                                                                                              | 19/80 [00:46<01:09,  1.14s/it]

[I 2026-06-26 15:45:38,554] Trial 137 pruned.

Best trial: 75. Best value: 0.966258:  25%|███████████████████████████████                                                                                             | 20/80 [00:48<01:36,  1.60s/it]

[I 2026-06-26 15:45:41,460] Trial 133 finished with value: 0.9656961859137059 and parameters: {'l1_ratio': 0.2123478914185479, 'C': 0.1251509731189775, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002945387410170244, 'max_iter': 4506, 'weight_class_0': 2.1612041608356782, 'weight_class_1': 1.089904345673934, 'weight_class_2': 1.840040505307422}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  26%|████████████████████████████████▌                                                                                           | 21/80 [00:49<01:12,  1.23s/it]

[I 2026-06-26 15:45:41,684] Trial 139 finished with value: 0.9660364557591183 and parameters: {'l1_ratio': 0.28404295433267085, 'C': 0.04938466531597772, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004389154501138424, 'max_iter': 4515, 'weight_class_0': 2.5036942189171834, 'weight_class_1': 2.2837293373806897, 'weight_class_2': 8.080463697693167}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  28%|██████████████████████████████████                                                                                          | 22/80 [01:04<05:01,  5.19s/it]

[I 2026-06-26 15:45:57,029] Trial 143 pruned.

Best trial: 75. Best value: 0.966258:  29%|███████████████████████████████████▋                                                                                        | 23/80 [01:06<04:05,  4.31s/it]

[I 2026-06-26 15:45:59,131] Trial 147 finished with value: 0.9659719913939385 and parameters: {'l1_ratio': 0.28397972982250963, 'C': 0.03406407440878046, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00414361663429204, 'max_iter': 4491, 'weight_class_0': 1.674461886660094, 'weight_class_1': 1.389465098363369, 'weight_class_2': 5.696468228283395}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  30%|█████████████████████████████████████▏                                                                                      | 24/80 [01:08<03:16,  3.50s/it]

[I 2026-06-26 15:46:00,661] Trial 149 finished with value: 0.9656615975048639 and parameters: {'l1_ratio': 0.3913033430461346, 'C': 0.03059459260128453, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003852181454008702, 'max_iter': 4845, 'weight_class_0': 2.98235347943509, 'weight_class_1': 1.378791656197041, 'weight_class_2': 5.894938834901672}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  31%|██████████████████████████████████████▊                                                                                     | 25/80 [01:09<02:33,  2.79s/it]

[I 2026-06-26 15:46:01,750] Trial 150 finished with value: 0.9659611904031971 and parameters: {'l1_ratio': 0.36394468042956024, 'C': 0.02765074278553012, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004048185349140939, 'max_iter': 4622, 'weight_class_0': 1.4403510942910664, 'weight_class_1': 1.630472218574833, 'weight_class_2': 5.685674191796386}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  32%|████████████████████████████████████████▎                                                                                   | 26/80 [01:10<02:11,  2.44s/it]

[I 2026-06-26 15:46:03,336] Trial 144 finished with value: 0.9660251671757063 and parameters: {'l1_ratio': 0.2784963529428407, 'C': 0.045282382473612874, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001515708071928139, 'max_iter': 4523, 'weight_class_0': 2.557749671714221, 'weight_class_1': 2.301208296376232, 'weight_class_2': 8.021322063353951}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  34%|█████████████████████████████████████████▊                                                                                  | 27/80 [01:12<02:00,  2.27s/it]

[I 2026-06-26 15:46:05,189] Trial 152 finished with value: 0.9656567964296757 and parameters: {'l1_ratio': 0.4068345865149157, 'C': 0.030421321741072465, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004307316217040943, 'max_iter': 4827, 'weight_class_0': 3.000356530947168, 'weight_class_1': 1.3833247451776136, 'weight_class_2': 5.955013579786176}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  35%|███████████████████████████████████████████▍                                                                                | 28/80 [01:12<01:27,  1.68s/it]

[I 2026-06-26 15:46:05,421] Trial 151 finished with value: 0.9658471244804655 and parameters: {'l1_ratio': 0.4133601125313221, 'C': 0.020799914163737523, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00402677543972214, 'max_iter': 4808, 'weight_class_0': 3.0238464321067338, 'weight_class_1': 1.594811134489857, 'weight_class_2': 5.760558774014819}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  36%|████████████████████████████████████████████▉                                                                               | 29/80 [01:13<01:13,  1.43s/it]

[I 2026-06-26 15:46:06,347] Trial 148 finished with value: 0.9659722641964106 and parameters: {'l1_ratio': 0.17324193327937615, 'C': 0.03414237006862495, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0014770049810901827, 'max_iter': 4296, 'weight_class_0': 1.7232808818608074, 'weight_class_1': 1.3610204881302448, 'weight_class_2': 5.520518193865859}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  38%|██████████████████████████████████████████████▌                                                                             | 30/80 [01:17<01:51,  2.23s/it]

[I 2026-06-26 15:46:10,458] Trial 134 finished with value: 0.9655843597196754 and parameters: {'l1_ratio': 0.31772661998425134, 'C': 0.11291253250996013, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.3354336799943608e-05, 'max_iter': 4657, 'weight_class_0': 2.31367727172583, 'weight_class_1': 2.429222834906401, 'weight_class_2': 1.995605808645959}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  40%|█████████████████████████████████████████████████▌                                                                          | 32/80 [01:27<02:27,  3.07s/it]

[I 2026-06-26 15:46:19,635] Trial 136 finished with value: 0.9651192452578264 and parameters: {'l1_ratio': 0.21023161442935628, 'C': 0.12612477169538872, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.3826698709974455e-06, 'max_iter': 4492, 'weight_class_0': 2.4679292256267695, 'weight_class_1': 1.0983209720965577, 'weight_class_2': 1.33612798269225}. Best is trial 75 with value: 0.9662583810460816.
[I 2026-06-26 15:46:19,801] Trial 154 finished with value: 0.9654971590888811 and parameters: {'l1_ratio': 0.41702848133692805, 'C': 0.03142765414768556, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005718678589208417, 'max_iter': 4290, 'weight_class_0': 3.4939081337711873, 'weight_class_1': 1.40127889665227, 'weight_class_2': 8.452728821439653}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  41%|███████████████████████████████████████████████████▏                                                                        | 33/80 [01:28<01:53,  2.42s/it]

[I 2026-06-26 15:46:20,721] Trial 155 finished with value: 0.965908196563525 and parameters: {'l1_ratio': 0.28333952715941363, 'C': 0.03278581772069922, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005992781406722834, 'max_iter': 4392, 'weight_class_0': 1.6080889162513843, 'weight_class_1': 1.6237911929067306, 'weight_class_2': 6.286148928453687}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  42%|████████████████████████████████████████████████████▋                                                                       | 34/80 [01:29<01:33,  2.03s/it]

[I 2026-06-26 15:46:21,842] Trial 156 finished with value: 0.9654622474959442 and parameters: {'l1_ratio': 0.16986868064411098, 'C': 0.021400303054572335, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005718887615500668, 'max_iter': 4296, 'weight_class_0': 1.4697139382227498, 'weight_class_1': 1.657216886178565, 'weight_class_2': 8.663434919828836}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  44%|██████████████████████████████████████████████████████▎                                                                     | 35/80 [01:30<01:15,  1.68s/it]

[I 2026-06-26 15:46:22,703] Trial 145 finished with value: 0.9655010603688355 and parameters: {'l1_ratio': 0.2795663064826436, 'C': 0.0067126285165282065, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.57086522246789e-05, 'max_iter': 4527, 'weight_class_0': 1.64134239028329, 'weight_class_1': 1.4093411855484932, 'weight_class_2': 8.401699922036169}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  45%|███████████████████████████████████████████████████████▊                                                                    | 36/80 [01:32<01:23,  1.90s/it]

[I 2026-06-26 15:46:25,106] Trial 159 finished with value: 0.9658430568457461 and parameters: {'l1_ratio': 0.2815416445382687, 'C': 0.01637442239711398, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0055415054086562785, 'max_iter': 4295, 'weight_class_0': 1.6051459703620563, 'weight_class_1': 2.934564282306749, 'weight_class_2': 8.170114302032486}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  46%|█████████████████████████████████████████████████████████▎                                                                  | 37/80 [01:33<01:07,  1.57s/it]

[I 2026-06-26 15:46:25,903] Trial 153 finished with value: 0.9657145561002816 and parameters: {'l1_ratio': 0.1653615240932693, 'C': 0.023137164349394706, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0015013338708781917, 'max_iter': 4855, 'weight_class_0': 3.0366516123359633, 'weight_class_1': 1.4233026128923232, 'weight_class_2': 5.753262904070685}. Best is trial 75 with value: 0.9662583810460816.
[I 2026-06-26 15:46:25,959] Trial 157 finished with value: 0.9660496959770881 and parameters: {'l1_ratio': 0.4184255703239461, 'C': 0.018074661902656327, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0041856034137839684, 'max_iter': 4282, 'weight_class_0': 1.6055280620697434, 'weight_class_1': 1.6190905259388157, 'weight_class_2': 5.735813838613509}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  49%|████████████████████████████████████████████████████████████▍                                                               | 39/80 [01:37<01:12,  1.76s/it]

[I 2026-06-26 15:46:29,888] Trial 161 finished with value: 0.9657157012332224 and parameters: {'l1_ratio': 0.36174491728964103, 'C': 0.017360895068863957, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005589628302546253, 'max_iter': 4315, 'weight_class_0': 1.1257017227106807, 'weight_class_1': 3.0704001968524284, 'weight_class_2': 6.459725043766559}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  50%|██████████████████████████████████████████████████████████████                                                              | 40/80 [01:39<01:17,  1.95s/it]

[I 2026-06-26 15:46:32,387] Trial 146 finished with value: 0.9659453317614284 and parameters: {'l1_ratio': 0.28158956692437626, 'C': 0.02885185937914614, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.344501664914005e-06, 'max_iter': 4845, 'weight_class_0': 1.6229361662303148, 'weight_class_1': 1.3860974390793654, 'weight_class_2': 5.78737071427085}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  51%|███████████████████████████████████████████████████████████████▌                                                            | 41/80 [01:40<01:06,  1.69s/it]

[I 2026-06-26 15:46:33,363] Trial 158 finished with value: 0.9658083200255287 and parameters: {'l1_ratio': 0.17401373850981358, 'C': 0.019562343320938976, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014685900530239599, 'max_iter': 4312, 'weight_class_0': 1.6191747207244196, 'weight_class_1': 2.976288913787032, 'weight_class_2': 8.68425217935105}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  52%|█████████████████████████████████████████████████████████████████                                                           | 42/80 [01:41<00:53,  1.42s/it]

[I 2026-06-26 15:46:34,040] Trial 160 finished with value: 0.965600169318049 and parameters: {'l1_ratio': 0.16659049364683093, 'C': 0.017831740976948174, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016044336235267642, 'max_iter': 4616, 'weight_class_0': 1.609555975255844, 'weight_class_1': 1.582521857764448, 'weight_class_2': 8.569091325240493}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  55%|████████████████████████████████████████████████████████████████████▏                                                       | 44/80 [01:47<01:08,  1.90s/it]

[I 2026-06-26 15:46:39,638] Trial 166 pruned.
[I 2026-06-26 15:46:39,826] Trial 162 finished with value: 0.9656057206599782 and parameters: {'l1_ratio': 0.16919307368366626, 'C': 0.020262494562999753, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005225408026016024, 'max_iter': 4351, 'weight_class_0': 1.614983415581171, 'weight_class_1': 1.3646883477142324, 'weight_class_2': 8.220171048021255}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  56%|█████████████████████████████████████████████████████████████████████▊                                                      | 45/80 [01:50<01:22,  2.36s/it]

[I 2026-06-26 15:46:43,301] Trial 168 pruned.

Best trial: 75. Best value: 0.966258:  57%|███████████████████████████████████████████████████████████████████████▎                                                    | 46/80 [01:54<01:29,  2.64s/it]

[I 2026-06-26 15:46:46,622] Trial 163 finished with value: 0.9657443453971609 and parameters: {'l1_ratio': 0.2845275060544811, 'C': 0.018186333077959867, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002282551584654675, 'max_iter': 4304, 'weight_class_0': 1.6182200440141001, 'weight_class_1': 1.6442276310885389, 'weight_class_2': 7.764053428805687}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  59%|████████████████████████████████████████████████████████████████████████▊                                                   | 47/80 [01:54<01:07,  2.04s/it]

[I 2026-06-26 15:46:47,234] Trial 164 pruned.

Best trial: 75. Best value: 0.966258:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 48/80 [01:57<01:14,  2.33s/it]

[I 2026-06-26 15:46:50,256] Trial 165 finished with value: 0.9659451235379057 and parameters: {'l1_ratio': 0.34779999513494264, 'C': 0.014828026875601665, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001640588404205475, 'max_iter': 4609, 'weight_class_0': 1.6032185084227386, 'weight_class_1': 2.177314860134628, 'weight_class_2': 7.52644818659846}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  61%|███████████████████████████████████████████████████████████████████████████▉                                                | 49/80 [01:58<01:00,  1.94s/it]

[I 2026-06-26 15:46:51,256] Trial 170 pruned.

Best trial: 75. Best value: 0.966258:  62%|█████████████████████████████████████████████████████████████████████████████▌                                              | 50/80 [02:01<01:02,  2.09s/it]

[I 2026-06-26 15:46:53,709] Trial 169 finished with value: 0.9655845907923613 and parameters: {'l1_ratio': 0.3500103441882384, 'C': 0.01775940975907604, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014453701670894402, 'max_iter': 4424, 'weight_class_0': 1.19000960131782, 'weight_class_1': 1.5848595732745585, 'weight_class_2': 6.890830405400753}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  64%|███████████████████████████████████████████████████████████████████████████████                                             | 51/80 [02:01<00:45,  1.57s/it]

[I 2026-06-26 15:46:54,042] Trial 167 finished with value: 0.9657884814568967 and parameters: {'l1_ratio': 0.3460069659246606, 'C': 0.04465364226398416, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0015006072560394166, 'max_iter': 4615, 'weight_class_0': 1.9254706585856063, 'weight_class_1': 0.9166504667776133, 'weight_class_2': 4.5909039216875325}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  65%|████████████████████████████████████████████████████████████████████████████████▌                                           | 52/80 [02:06<01:09,  2.50s/it]

[I 2026-06-26 15:46:58,721] Trial 176 pruned.

Best trial: 75. Best value: 0.966258:  66%|██████████████████████████████████████████████████████████████████████████████████▏                                         | 53/80 [02:13<01:43,  3.82s/it]

[I 2026-06-26 15:47:05,630] Trial 171 finished with value: 0.966054372914819 and parameters: {'l1_ratio': 0.3623453837588946, 'C': 0.061978013171338525, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006439780126865128, 'max_iter': 4422, 'weight_class_0': 1.3832817365684293, 'weight_class_1': 2.1317023957726287, 'weight_class_2': 4.668320165725435}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  68%|███████████████████████████████████████████████████████████████████████████████████▋                                        | 54/80 [02:17<01:41,  3.92s/it]

[I 2026-06-26 15:47:09,774] Trial 178 finished with value: 0.9660918500160935 and parameters: {'l1_ratio': 0.3366566740679575, 'C': 0.04802218570971874, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004551448172906316, 'max_iter': 4425, 'weight_class_0': 1.4339417195195332, 'weight_class_1': 2.004247458583705, 'weight_class_2': 4.63934374431118}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  69%|█████████████████████████████████████████████████████████████████████████████████████▎                                      | 55/80 [02:20<01:31,  3.68s/it]

[I 2026-06-26 15:47:12,893] Trial 179 finished with value: 0.9661287153536982 and parameters: {'l1_ratio': 0.43009442118087315, 'C': 0.04381138928523317, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004668422420412504, 'max_iter': 4203, 'weight_class_0': 1.3981716791021856, 'weight_class_1': 2.1206801676522593, 'weight_class_2': 4.653525540713905}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 56/80 [02:29<02:07,  5.33s/it]

[I 2026-06-26 15:47:22,082] Trial 175 finished with value: 0.9653834570076605 and parameters: {'l1_ratio': 0.4688801706667789, 'C': 0.055296188568006735, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.336853197071801e-05, 'max_iter': 4438, 'weight_class_0': 1.864001729319816, 'weight_class_1': 8.691517136199778, 'weight_class_2': 4.810847779733908}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  71%|████████████████████████████████████████████████████████████████████████████████████████▎                                   | 57/80 [02:30<01:29,  3.90s/it]

[I 2026-06-26 15:47:22,647] Trial 174 finished with value: 0.9660462765644526 and parameters: {'l1_ratio': 0.33502772201375186, 'C': 0.06049234612878563, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.13735252031425e-05, 'max_iter': 4444, 'weight_class_0': 1.3832602128266835, 'weight_class_1': 2.179086291456451, 'weight_class_2': 4.732172562308446}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  72%|█████████████████████████████████████████████████████████████████████████████████████████▉                                  | 58/80 [02:31<01:10,  3.21s/it]

[I 2026-06-26 15:47:24,229] Trial 177 pruned.

Best trial: 75. Best value: 0.966258:  74%|███████████████████████████████████████████████████████████████████████████████████████████▍                                | 59/80 [02:32<00:55,  2.63s/it]

[I 2026-06-26 15:47:25,511] Trial 184 pruned.

Best trial: 75. Best value: 0.966258:  75%|█████████████████████████████████████████████████████████████████████████████████████████████                               | 60/80 [02:35<00:49,  2.46s/it]

[I 2026-06-26 15:47:27,577] Trial 172 finished with value: 0.9661039704843863 and parameters: {'l1_ratio': 0.3369894470532959, 'C': 0.04869698927841154, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.261154020549249e-06, 'max_iter': 4425, 'weight_class_0': 1.4034797200868359, 'weight_class_1': 2.1236729839849033, 'weight_class_2': 4.6518577915404125}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  76%|██████████████████████████████████████████████████████████████████████████████████████████████▌                             | 61/80 [02:40<01:01,  3.25s/it]

[I 2026-06-26 15:47:32,658] Trial 186 pruned.

Best trial: 75. Best value: 0.966258:  78%|████████████████████████████████████████████████████████████████████████████████████████████████                            | 62/80 [02:40<00:44,  2.48s/it]

[I 2026-06-26 15:47:33,337] Trial 182 finished with value: 0.9662353226499732 and parameters: {'l1_ratio': 0.9319576408035846, 'C': 0.008974947309412003, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.380861332883226e-05, 'max_iter': 4459, 'weight_class_0': 1.448880515061281, 'weight_class_1': 2.1250917491861863, 'weight_class_2': 5.355605088475555}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  79%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 63/80 [02:42<00:39,  2.30s/it]

[I 2026-06-26 15:47:35,206] Trial 181 finished with value: 0.9661361766491392 and parameters: {'l1_ratio': 0.43793459087840286, 'C': 0.04056841882118031, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010260793088930732, 'max_iter': 4436, 'weight_class_0': 1.413296034204626, 'weight_class_1': 2.1003541680199067, 'weight_class_2': 4.62248190426565}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 64/80 [02:44<00:35,  2.23s/it]

[I 2026-06-26 15:47:37,286] Trial 183 finished with value: 0.9661326404986363 and parameters: {'l1_ratio': 0.0868884820322147, 'C': 0.008415607912095174, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00013686595199469137, 'max_iter': 4909, 'weight_class_0': 1.8619065544590578, 'weight_class_1': 2.080578081233198, 'weight_class_2': 5.503067841930275}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 65/80 [02:50<00:48,  3.21s/it]

[I 2026-06-26 15:47:42,795] Trial 190 pruned.

Best trial: 75. Best value: 0.966258:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 66/80 [02:50<00:32,  2.35s/it]

[I 2026-06-26 15:47:43,127] Trial 185 finished with value: 0.9661652181914473 and parameters: {'l1_ratio': 0.4310283701856529, 'C': 0.06609889188414712, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005927345535947113, 'max_iter': 4197, 'weight_class_0': 1.9603101700399654, 'weight_class_1': 2.17206001835649, 'weight_class_2': 4.636529603022417}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 67/80 [02:58<00:51,  3.98s/it]

[I 2026-06-26 15:47:50,902] Trial 188 finished with value: 0.9661825791817724 and parameters: {'l1_ratio': 0.443419563536747, 'C': 0.06419658614050792, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012199074087520978, 'max_iter': 4114, 'weight_class_0': 2.002999823698094, 'weight_class_1': 2.074846673265301, 'weight_class_2': 4.082137601869372}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 68/80 [02:59<00:37,  3.09s/it]

[I 2026-06-26 15:47:51,914] Trial 180 finished with value: 0.966239839738736 and parameters: {'l1_ratio': 0.43813400452380014, 'C': 0.04005243196274609, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.2231556994602528e-06, 'max_iter': 4414, 'weight_class_0': 1.927302321049038, 'weight_class_1': 2.1498799183161523, 'weight_class_2': 4.676646291552317}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 69/80 [02:59<00:25,  2.27s/it]

[I 2026-06-26 15:47:52,291] Trial 173 finished with value: 0.9661122100650982 and parameters: {'l1_ratio': 0.9724611093821829, 'C': 0.05993982491145499, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.717007778507591e-05, 'max_iter': 4431, 'weight_class_0': 1.86415033319362, 'weight_class_1': 2.114186723628048, 'weight_class_2': 4.695745794643893}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 75. Best value: 0.966258:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 70/80 [03:00<00:19,  1.93s/it]

[I 2026-06-26 15:47:53,396] Trial 187 finished with value: 0.9660574782364083 and parameters: {'l1_ratio': 0.5308566579921111, 'C': 0.01014971119108035, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005682004514104501, 'max_iter': 4105, 'weight_class_0': 1.8028190131067656, 'weight_class_1': 2.0375596035446204, 'weight_class_2': 3.203278552486115}. Best is trial 75 with value: 0.9662583810460816.

Best trial: 189. Best value: 0.96632:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 71/80 [03:01<00:14,  1.57s/it]

[I 2026-06-26 15:47:54,122] Trial 189 finished with value: 0.9663201050233999 and parameters: {'l1_ratio': 0.4274426593956689, 'C': 0.009483079576015114, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006218491059873419, 'max_iter': 4171, 'weight_class_0': 1.8092898550143288, 'weight_class_1': 2.65760019710011, 'weight_class_2': 3.970725989165942}. Best is trial 189 with value: 0.9663201050233999.

Best trial: 189. Best value: 0.96632:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 72/80 [03:04<00:15,  1.98s/it]

[I 2026-06-26 15:47:57,090] Trial 192 pruned.

Best trial: 189. Best value: 0.96632:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 73/80 [03:09<00:19,  2.81s/it]

[I 2026-06-26 15:48:01,846] Trial 191 finished with value: 0.965822410405744 and parameters: {'l1_ratio': 0.336088746355916, 'C': 0.0016817915246530423, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014266692671149336, 'max_iter': 4169, 'weight_class_0': 1.3206190087713408, 'weight_class_1': 2.7132037760941303, 'weight_class_2': 4.3929098885516575}. Best is trial 189 with value: 0.9663201050233999.

Best trial: 193. Best value: 0.966348:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 74/80 [03:17<00:27,  4.56s/it]

[I 2026-06-26 15:48:10,488] Trial 193 finished with value: 0.9663482802797547 and parameters: {'l1_ratio': 0.33444640323378966, 'C': 0.009816711499908143, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.402666379694602e-05, 'max_iter': 4393, 'weight_class_0': 1.3891686022004115, 'weight_class_1': 2.802558290832105, 'weight_class_2': 4.261825099062885}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 75/80 [03:20<00:19,  3.84s/it]

[I 2026-06-26 15:48:12,617] Trial 195 finished with value: 0.9661424058832557 and parameters: {'l1_ratio': 0.39375042538946126, 'C': 0.0040745587460588, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010831644059328582, 'max_iter': 4378, 'weight_class_0': 1.3934991936451027, 'weight_class_1': 2.6183791705112824, 'weight_class_2': 4.046968121613779}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 76/80 [03:21<00:12,  3.21s/it]

[I 2026-06-26 15:48:14,367] Trial 194 finished with value: 0.9662875444184259 and parameters: {'l1_ratio': 0.43091892023140904, 'C': 0.011399633289815794, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.1286823285443e-05, 'max_iter': 4217, 'weight_class_0': 1.31411533492382, 'weight_class_1': 2.6594336185184444, 'weight_class_2': 4.021312668798019}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 77/80 [03:22<00:07,  2.43s/it]

[I 2026-06-26 15:48:15,003] Trial 196 finished with value: 0.965796505947613 and parameters: {'l1_ratio': 0.07123548946114304, 'C': 0.0016297078923428793, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011743365976757377, 'max_iter': 4389, 'weight_class_0': 1.396610290774711, 'weight_class_1': 2.7125468904885066, 'weight_class_2': 4.286379656305838}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 78/80 [03:24<00:04,  2.38s/it]

[I 2026-06-26 15:48:17,251] Trial 197 finished with value: 0.9660550066799594 and parameters: {'l1_ratio': 0.8249705669229007, 'C': 0.07136309590840828, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.600312478944951e-05, 'max_iter': 4231, 'weight_class_0': 1.2203818627208338, 'weight_class_1': 2.7171603453135122, 'weight_class_2': 4.07843678680907}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 79/80 [03:26<00:02,  2.22s/it]

[I 2026-06-26 15:48:19,097] Trial 198 finished with value: 0.9657278861858953 and parameters: {'l1_ratio': 0.83164015645327, 'C': 0.0018499381248313755, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.585512029126983e-05, 'max_iter': 4090, 'weight_class_0': 1.212311396828259, 'weight_class_1': 2.001532621714819, 'weight_class_2': 4.120032289953299}. Best is trial 193 with value: 0.9663482802797547.

Best trial: 193. Best value: 0.966348: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [03:37<00:00,  2.71s/it]

[I 2026-06-26 15:48:29,570] Trial 199 finished with value: 0.9660674237420359 and parameters: {'l1_ratio': 0.9353065668405115, 'C': 0.06655056548619691, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010611153678190407, 'max_iter': 4050, 'weight_class_0': 1.3644101139063267, 'weight_class_1': 2.664329469212658, 'weight_class_2': 4.268092894188272}. Best is trial 193 with value: 0.9663482802797547.

Best trial score:
0.9663482802797547

Best params:
{'l1_ratio': 0.33444640323378966, 'C': 0.009816711499908143, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.402666379694602e-05, 'max_iter': 4393, 'weight_class_0': 1.3891686022004115, 'weight_class_1': 2.802558290832105, 'weight_class_2': 4.261825099062885}

In [28]:
lg_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lg = LogisticRegression(
    solver="saga",
    random_state=42,
    **lg_params
).fit(X_train, y_train.class_encoded)

test_proba = lg.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [29]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [30]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lg.csv', index=False)

In [31]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [32]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'lg_0', 'lg_1', 'lg_2', 'sgd_0', 'sgd_1', 'sgd_2'],
      dtype='str')

In [33]:
len(study.trials)

200