# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle

from sklearn.metrics import balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
# cols_to_drop = ['lg_0', 'lg_1', 'lg_2', 'extra_0', 'extra_1', 'extra_2', 'rf_0', 'rf_1', 'rf_2', 'hist_0', 'hist_1', 'hist_2']

X_train = pd.read_parquet('../data/X_train_stacking_layer_two.parquet') #.drop(columns=cols_to_drop)
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_two.parquet') #.drop(columns=cols_to_drop)

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.999910,0.000083,0.000007,0.999866,0.000124,0.000010,0.999928,0.000070,0.000003,0.988210,0.004367,0.007423,0.999210,0.000790,0.000000
1,0.992961,0.000411,0.006628,0.991422,0.000567,0.008011,0.992562,0.000566,0.006872,0.986847,0.004779,0.008373,0.988522,0.001245,0.010233
2,0.000109,0.999858,0.000033,0.000162,0.999819,0.000019,0.000030,0.999962,0.000008,0.009897,0.988895,0.001208,0.002604,0.997396,0.000000
3,0.999805,0.000187,0.000009,0.999766,0.000223,0.000010,0.999837,0.000159,0.000004,0.988202,0.004372,0.007426,0.999098,0.000902,0.000000
4,0.998393,0.001560,0.000047,0.998544,0.001413,0.000043,0.998238,0.001711,0.000051,0.987966,0.004405,0.007629,0.998207,0.001793,0.000000

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.997841,0.002113,0.000045,0.997856,0.001945,0.000199,0.998030,0.001934,0.000036,0.987950,0.004507,0.007543,0.997783,0.002217,0.000000
1,0.996887,0.003080,0.000033,0.997599,0.002381,0.000020,0.996744,0.003240,0.000016,0.987886,0.004549,0.007565,0.997324,0.002676,0.000000
2,0.998244,0.001026,0.000731,0.998669,0.000563,0.000768,0.998349,0.000750,0.000901,0.987787,0.004504,0.007709,0.998949,0.001051,0.000000
3,0.000658,0.000086,0.999256,0.001490,0.000130,0.998380,0.000538,0.000138,0.999324,0.013634,0.004166,0.982199,0.000000,0.002127,0.997873
4,0.999840,0.000151,0.000009,0.999810,0.000178,0.000012,0.999880,0.000116,0.000004,0.988019,0.004456,0.007524,0.999069,0.000931,0.000000

# Machine Learning

In [6]:
def objective(trial, X, y):
    
    loss = trial.suggest_categorical("loss", ["log_loss", "modified_huber", "hinge", "perceptron"])
    penalty = trial.suggest_categorical("penalty", ["l2", "l1", "elasticnet"])
    alpha = trial.suggest_float("alpha", 1e-9, 1e-1, log=True)
    l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)
    
    learning_rate = trial.suggest_categorical("learning_rate", ["optimal", "adaptive", "constant", "invscaling"])
    eta0 = trial.suggest_float("eta0", 1e-5, 1.0, log=True)
    power_t = trial.suggest_float("power_t", 0.1, 0.5) if learning_rate == "invscaling" else 0.5
    
    epsilon = trial.suggest_float("epsilon", 1e-3, 1e-1, log=True) 
    tol = trial.suggest_float("tol", 1e-6, 1e-2, log=True)
    average = trial.suggest_categorical("average", [True, False, 1, 5, 10]) # Permite médias baseadas em amostras

    class_weight = trial.suggest_categorical("class_weight", ["balanced", None])
    max_iter = trial.suggest_int("max_iter", 1000, 5000)

    w0 = trial.suggest_float('weight_class_0', 0.05, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.05, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):
        X_train_fold, X_valid_fold = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train_fold, y_valid_fold = y.iloc[train_idx], y.iloc[valid_idx]
        
        model = SGDClassifier(
            loss=loss,
            penalty=penalty,
            alpha=alpha,
            learning_rate=learning_rate,
            eta0=eta0,
            power_t=power_t,
            l1_ratio=l1_ratio,
            epsilon=epsilon,
            tol=tol,
            average=average,
            class_weight=class_weight,
            max_iter=max_iter,
            random_state=42,
            n_jobs=1
        ).fit(X_train_fold, y_train_fold)

        if loss in ["log_loss", "modified_huber"]:
            proba = model.predict_proba(X_valid_fold)
            weighted_probas = proba * weights
            pred = np.argmax(weighted_probas, axis=1)
        
        else:
            decision = model.decision_function(X_valid_fold)
            weighted_decision = decision * weights
            pred = np.argmax(weighted_decision, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.class_encoded), 
    n_trials=60, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-26 16:01:09,385] A new study created in memory with name: no-name-037b66cc-8f8a-4699-8f42-58136eb5b26f
Best trial: 11. Best value: 0.95523:   2%|██                                                                                                                            | 1/60 [00:13<13:19, 13.54s/it]

[I 2026-06-26 16:01:22,918] Trial 11 finished with value: 0.9552302339515817 and parameters: {'loss': 'perceptron', 'penalty': 'l2', 'alpha': 0.026338791137051495, 'l1_ratio': 0.23420408435467832, 'learning_rate': 'invscaling', 'eta0': 0.08662252522495897, 'power_t': 0.324085343787464, 'epsilon': 0.001878334942861441, 'tol': 0.000580389730867494, 'average': False, 'class_weight': 'balanced', 'max_iter': 3349, 'weight_class_0': 3.26451033075061, 'weight_class_1': 0.558984960183296, 'weight_class_2': 0.4151023653624717}. Best is trial 11 with value: 0.9552302339515817.

Best trial: 1. Best value: 0.958779:   3%|████▏                                                                                                                         | 2/60 [00:13<05:30,  5.70s/it]

[I 2026-06-26 16:01:23,135] Trial 1 finished with value: 0.9587791723826482 and parameters: {'loss': 'perceptron', 'penalty': 'l2', 'alpha': 5.900882007936968e-07, 'l1_ratio': 0.9148256430608815, 'learning_rate': 'constant', 'eta0': 0.015442668729119991, 'epsilon': 0.0021724364301837695, 'tol': 3.116989881656874e-05, 'average': 1, 'class_weight': None, 'max_iter': 1585, 'weight_class_0': 7.3304867100264675, 'weight_class_1': 3.013995623183563, 'weight_class_2': 0.18773380273754553}. Best is trial 1 with value: 0.9587791723826482.

Best trial: 1. Best value: 0.958779:   5%|██████▎                                                                                                                       | 3/60 [00:15<03:37,  3.82s/it]

[I 2026-06-26 16:01:24,710] Trial 0 finished with value: 0.9501619832907359 and parameters: {'loss': 'perceptron', 'penalty': 'elasticnet', 'alpha': 7.290360796261684e-05, 'l1_ratio': 0.08597035187522284, 'learning_rate': 'invscaling', 'eta0': 0.00038634844588304474, 'power_t': 0.4611383695066943, 'epsilon': 0.056808362479307886, 'tol': 0.0001735398136466864, 'average': False, 'class_weight': None, 'max_iter': 3272, 'weight_class_0': 1.8664831150856944, 'weight_class_1': 0.9486801520907333, 'weight_class_2': 0.2876189035090752}. Best is trial 1 with value: 0.9587791723826482.

Best trial: 1. Best value: 0.958779:   7%|████████▍                                                                                                                     | 4/60 [00:19<03:31,  3.78s/it]

[I 2026-06-26 16:01:28,424] Trial 5 finished with value: 0.016336451160055304 and parameters: {'loss': 'log_loss', 'penalty': 'elasticnet', 'alpha': 8.84343759196917e-05, 'l1_ratio': 0.9707315415744566, 'learning_rate': 'constant', 'eta0': 0.04535599111823958, 'epsilon': 0.019230565848379247, 'tol': 0.000676838836745196, 'average': 5, 'class_weight': 'balanced', 'max_iter': 1545, 'weight_class_0': 0.07355345289138865, 'weight_class_1': 1.9181842932925701, 'weight_class_2': 0.07471228601448798}. Best is trial 1 with value: 0.9587791723826482.

Best trial: 1. Best value: 0.958779:   8%|██████████▌                                                                                                                   | 5/60 [00:19<02:21,  2.57s/it]

[I 2026-06-26 16:01:28,859] Trial 2 finished with value: 0.14299854143919385 and parameters: {'loss': 'perceptron', 'penalty': 'l1', 'alpha': 3.110473176715023e-06, 'l1_ratio': 0.36643161181044437, 'learning_rate': 'optimal', 'eta0': 0.0016978819158165958, 'epsilon': 0.007557434117048961, 'tol': 0.004927489983002035, 'average': 1, 'class_weight': None, 'max_iter': 2905, 'weight_class_0': 0.129955760902277, 'weight_class_1': 0.11927209835219693, 'weight_class_2': 0.06160562348075332}. Best is trial 1 with value: 0.9587791723826482.

Best trial: 1. Best value: 0.958779:  10%|████████████▌                                                                                                                 | 6/60 [00:19<01:38,  1.82s/it]

[I 2026-06-26 16:01:29,218] Trial 8 pruned.

Best trial: 1. Best value: 0.958779:  12%|██████████████▋                                                                                                               | 7/60 [00:20<01:20,  1.52s/it]

[I 2026-06-26 16:01:30,136] Trial 9 pruned.

Best trial: 4. Best value: 0.960989:  13%|████████████████▊                                                                                                             | 8/60 [00:28<02:55,  3.37s/it]

[I 2026-06-26 16:01:37,456] Trial 4 finished with value: 0.9609886072392279 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 1.2313843797107876e-08, 'l1_ratio': 0.12054602610256104, 'learning_rate': 'constant', 'eta0': 0.5602126121703505, 'epsilon': 0.0034388979520072176, 'tol': 6.588933825526775e-05, 'average': 10, 'class_weight': None, 'max_iter': 2677, 'weight_class_0': 0.15585767067652131, 'weight_class_1': 3.9965242024419743, 'weight_class_2': 0.36609628144670936}. Best is trial 4 with value: 0.9609886072392279.

Best trial: 4. Best value: 0.960989:  15%|██████████████████▉                                                                                                           | 9/60 [00:32<03:02,  3.57s/it]

[I 2026-06-26 16:01:41,464] Trial 3 pruned.

Best trial: 7. Best value: 0.965072:  18%|██████████████████████▉                                                                                                      | 11/60 [00:32<01:30,  1.84s/it]

[I 2026-06-26 16:01:41,880] Trial 7 finished with value: 0.965071824415757 and parameters: {'loss': 'perceptron', 'penalty': 'elasticnet', 'alpha': 7.987164657915873e-08, 'l1_ratio': 0.5169620324168412, 'learning_rate': 'constant', 'eta0': 0.45426803209042405, 'epsilon': 0.009291015981382237, 'tol': 0.00013944006060015202, 'average': 5, 'class_weight': 'balanced', 'max_iter': 2653, 'weight_class_0': 0.05898087203024368, 'weight_class_1': 0.07940513407495137, 'weight_class_2': 3.460209852271887}. Best is trial 7 with value: 0.965071824415757.
[I 2026-06-26 16:01:42,010] Trial 16 pruned.

Best trial: 7. Best value: 0.965072:  20%|█████████████████████████                                                                                                    | 12/60 [00:33<01:17,  1.61s/it]

[I 2026-06-26 16:01:43,079] Trial 6 pruned.

Best trial: 7. Best value: 0.965072:  22%|███████████████████████████                                                                                                  | 13/60 [00:41<02:49,  3.60s/it]

[I 2026-06-26 16:01:51,260] Trial 20 pruned.

Best trial: 7. Best value: 0.965072:  23%|█████████████████████████████▏                                                                                               | 14/60 [01:00<06:09,  8.03s/it]

[I 2026-06-26 16:02:09,554] Trial 18 finished with value: 0.9649204589566269 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 1.8672639489470415e-07, 'l1_ratio': 0.19556903031406592, 'learning_rate': 'optimal', 'eta0': 2.0439642994394815e-05, 'epsilon': 0.0015139035303541745, 'tol': 0.008091466818829203, 'average': 1, 'class_weight': 'balanced', 'max_iter': 4275, 'weight_class_0': 0.8461596727885528, 'weight_class_1': 0.5317658128349828, 'weight_class_2': 0.4546242206524948}. Best is trial 7 with value: 0.965071824415757.

Best trial: 7. Best value: 0.965072:  25%|███████████████████████████████▎                                                                                             | 15/60 [01:01<04:29,  5.98s/it]

[I 2026-06-26 16:02:10,763] Trial 15 finished with value: 0.9596748961321111 and parameters: {'loss': 'hinge', 'penalty': 'l2', 'alpha': 0.003848627062071977, 'l1_ratio': 0.3933113281424445, 'learning_rate': 'adaptive', 'eta0': 3.4174497918550075e-05, 'epsilon': 0.002784966142324949, 'tol': 0.002624007847260471, 'average': 1, 'class_weight': 'balanced', 'max_iter': 3274, 'weight_class_0': 4.231260187176284, 'weight_class_1': 0.42831643463173874, 'weight_class_2': 5.635137440668426}. Best is trial 7 with value: 0.965071824415757.

Best trial: 7. Best value: 0.965072:  27%|█████████████████████████████████▎                                                                                           | 16/60 [01:07<04:22,  5.97s/it]

[I 2026-06-26 16:02:16,726] Trial 10 pruned.

Best trial: 7. Best value: 0.965072:  28%|███████████████████████████████████▍                                                                                         | 17/60 [01:17<05:07,  7.16s/it]

[I 2026-06-26 16:02:26,646] Trial 14 pruned.

Best trial: 7. Best value: 0.965072:  30%|█████████████████████████████████████▌                                                                                       | 18/60 [01:17<03:35,  5.13s/it]

[I 2026-06-26 16:02:27,042] Trial 12 pruned.

Best trial: 7. Best value: 0.965072:  32%|███████████████████████████████████████▌                                                                                     | 19/60 [01:37<06:29,  9.50s/it]

[I 2026-06-26 16:02:46,714] Trial 19 pruned.

Best trial: 7. Best value: 0.965072:  33%|█████████████████████████████████████████▋                                                                                   | 20/60 [01:38<04:37,  6.93s/it]

[I 2026-06-26 16:02:47,674] Trial 25 finished with value: 0.959778420810372 and parameters: {'loss': 'hinge', 'penalty': 'elasticnet', 'alpha': 3.0125743354238656e-09, 'l1_ratio': 0.5745740675665998, 'learning_rate': 'adaptive', 'eta0': 1.0206553374738307e-05, 'epsilon': 0.019027526888260173, 'tol': 0.0034125137607098903, 'average': 1, 'class_weight': 'balanced', 'max_iter': 4103, 'weight_class_0': 0.4858710420240675, 'weight_class_1': 0.05285658414461309, 'weight_class_2': 0.9398458668025286}. Best is trial 7 with value: 0.965071824415757.

Best trial: 7. Best value: 0.965072:  35%|███████████████████████████████████████████▊                                                                                 | 21/60 [01:54<06:20,  9.75s/it]

[I 2026-06-26 16:03:03,981] Trial 13 finished with value: 0.9622159325139735 and parameters: {'loss': 'modified_huber', 'penalty': 'l2', 'alpha': 0.014352233066748883, 'l1_ratio': 0.30574301438416596, 'learning_rate': 'adaptive', 'eta0': 0.05196585541864494, 'epsilon': 0.0475555103092048, 'tol': 2.2887201712336917e-05, 'average': 10, 'class_weight': None, 'max_iter': 3124, 'weight_class_0': 0.3395947912960747, 'weight_class_1': 4.69384596022874, 'weight_class_2': 9.188479259657177}. Best is trial 7 with value: 0.965071824415757.

Best trial: 7. Best value: 0.965072:  37%|█████████████████████████████████████████████▊                                                                               | 22/60 [01:55<04:24,  6.96s/it]

[I 2026-06-26 16:03:04,436] Trial 17 finished with value: 0.8997427138165459 and parameters: {'loss': 'perceptron', 'penalty': 'elasticnet', 'alpha': 0.0019202486007583119, 'l1_ratio': 0.9144404319404418, 'learning_rate': 'adaptive', 'eta0': 0.29040502246012384, 'epsilon': 0.0017244270471495444, 'tol': 0.00046702334104299116, 'average': False, 'class_weight': 'balanced', 'max_iter': 3306, 'weight_class_0': 0.1679899362268383, 'weight_class_1': 0.17937114677678226, 'weight_class_2': 0.21926131344290953}. Best is trial 7 with value: 0.965071824415757.

Best trial: 7. Best value: 0.965072:  38%|███████████████████████████████████████████████▉                                                                             | 23/60 [02:38<10:59, 17.83s/it]

[I 2026-06-26 16:03:47,629] Trial 23 finished with value: 0.9634015804540066 and parameters: {'loss': 'modified_huber', 'penalty': 'elasticnet', 'alpha': 1.4692099152013842e-09, 'l1_ratio': 0.5226308472505405, 'learning_rate': 'adaptive', 'eta0': 0.7169502481760178, 'epsilon': 0.00574843944162711, 'tol': 0.004600588934394572, 'average': 1, 'class_weight': None, 'max_iter': 2481, 'weight_class_0': 0.2754796837531012, 'weight_class_1': 9.640197982924466, 'weight_class_2': 1.082331952713358}. Best is trial 7 with value: 0.965071824415757.

Best trial: 29. Best value: 0.965175:  40%|█████████████████████████████████████████████████▌                                                                          | 24/60 [02:56<10:46, 17.95s/it]

[I 2026-06-26 16:04:05,844] Trial 29 finished with value: 0.9651746932695099 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 1.7110885354816367e-08, 'l1_ratio': 0.5969366161143892, 'learning_rate': 'optimal', 'eta0': 1.063385521634415e-05, 'epsilon': 0.015505208265829941, 'tol': 0.009581028284775082, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2195, 'weight_class_0': 0.3682885471709597, 'weight_class_1': 0.0683371444344765, 'weight_class_2': 0.9011790022175157}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  42%|███████████████████████████████████████████████████▋                                                                        | 25/60 [03:01<08:13, 14.09s/it]

[I 2026-06-26 16:04:10,941] Trial 21 finished with value: 0.9601940488246713 and parameters: {'loss': 'hinge', 'penalty': 'elasticnet', 'alpha': 1.223688358862103e-09, 'l1_ratio': 0.5582180003151477, 'learning_rate': 'adaptive', 'eta0': 2.9070736760071142e-05, 'epsilon': 0.09423768639845334, 'tol': 1.3182378540037304e-06, 'average': 5, 'class_weight': 'balanced', 'max_iter': 4651, 'weight_class_0': 0.44357751906190906, 'weight_class_1': 0.056570505155339165, 'weight_class_2': 1.1450477376001493}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  43%|█████████████████████████████████████████████████████▋                                                                      | 26/60 [03:16<08:05, 14.29s/it]

[I 2026-06-26 16:04:25,707] Trial 24 finished with value: 0.9631246738555737 and parameters: {'loss': 'modified_huber', 'penalty': 'elasticnet', 'alpha': 1.3614488102406777e-09, 'l1_ratio': 0.5777680286364212, 'learning_rate': 'adaptive', 'eta0': 0.9318508863898707, 'epsilon': 0.005302180945749511, 'tol': 0.00011264999015102214, 'average': 1, 'class_weight': None, 'max_iter': 2456, 'weight_class_0': 0.24473655595077937, 'weight_class_1': 9.44220366408664, 'weight_class_2': 0.8451475055955507}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  45%|███████████████████████████████████████████████████████▊                                                                    | 27/60 [03:28<07:34, 13.78s/it]

[I 2026-06-26 16:04:38,279] Trial 22 finished with value: 0.959919979844807 and parameters: {'loss': 'modified_huber', 'penalty': 'elasticnet', 'alpha': 1.134727956684663e-09, 'l1_ratio': 0.5250481348480835, 'learning_rate': 'adaptive', 'eta0': 0.825755394891924, 'epsilon': 0.006097339923113001, 'tol': 8.858996791298422e-06, 'average': 1, 'class_weight': None, 'max_iter': 2330, 'weight_class_0': 0.2644858431158013, 'weight_class_1': 0.06825186317291308, 'weight_class_2': 1.0309197362513471}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  47%|█████████████████████████████████████████████████████████▊                                                                  | 28/60 [03:53<09:06, 17.08s/it]

[I 2026-06-26 16:05:03,069] Trial 35 finished with value: 0.9651298341940325 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 6.675152600930331e-08, 'l1_ratio': 0.6812044094814327, 'learning_rate': 'optimal', 'eta0': 0.00013733089093980456, 'epsilon': 0.012039689679408393, 'tol': 0.009134709016656558, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2119, 'weight_class_0': 0.05553934865697772, 'weight_class_1': 0.0827251343112424, 'weight_class_2': 0.5227082231986516}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  48%|███████████████████████████████████████████████████████████▉                                                                | 29/60 [04:51<15:10, 29.37s/it]

[I 2026-06-26 16:06:01,095] Trial 37 finished with value: 0.9650802876548381 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 2.4221230463265843e-08, 'l1_ratio': 0.6503665364756586, 'learning_rate': 'optimal', 'eta0': 0.00015028922808863287, 'epsilon': 0.010340066290101703, 'tol': 0.008919756449122216, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2204, 'weight_class_0': 0.0525060152675034, 'weight_class_1': 0.09781091127259675, 'weight_class_2': 0.6254466677864882}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  50%|██████████████████████████████████████████████████████████████                                                              | 30/60 [04:56<10:58, 21.96s/it]

[I 2026-06-26 16:06:05,775] Trial 31 finished with value: 0.9648728810757209 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 4.331609481577584e-08, 'l1_ratio': 0.24219115230602478, 'learning_rate': 'optimal', 'eta0': 0.00012843716473254533, 'epsilon': 0.011465594964001813, 'tol': 0.00924113076046801, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2358, 'weight_class_0': 0.3034842772510622, 'weight_class_1': 0.9848706528753762, 'weight_class_2': 0.7621040292057838}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  52%|████████████████████████████████████████████████████████████████                                                            | 31/60 [04:59<07:50, 16.24s/it]

[I 2026-06-26 16:06:08,668] Trial 36 finished with value: 0.9646686642658523 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 7.904607821307168e-08, 'l1_ratio': 0.6984629017264209, 'learning_rate': 'optimal', 'eta0': 0.00013626027361892092, 'epsilon': 0.010696283973462234, 'tol': 0.0013134500999151472, 'average': 5, 'class_weight': 'balanced', 'max_iter': 2163, 'weight_class_0': 0.07572428282814941, 'weight_class_1': 0.10328154147145838, 'weight_class_2': 0.5864143389722075}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  53%|██████████████████████████████████████████████████████████████████▏                                                         | 32/60 [05:30<09:43, 20.84s/it]

[I 2026-06-26 16:06:40,230] Trial 34 finished with value: 0.9649944796535713 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 6.120406736634618e-08, 'l1_ratio': 0.5219402543642732, 'learning_rate': 'optimal', 'eta0': 0.00015357406227860108, 'epsilon': 0.010772304296925527, 'tol': 0.00782459944333987, 'average': 5, 'class_weight': 'balanced', 'max_iter': 2368, 'weight_class_0': 0.0516444718112099, 'weight_class_1': 1.1274605756539102, 'weight_class_2': 0.8474890708953449}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  55%|████████████████████████████████████████████████████████████████████▏                                                       | 33/60 [05:39<07:42, 17.12s/it]

[I 2026-06-26 16:06:48,680] Trial 38 finished with value: 0.9646946171637577 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 6.867590468518145e-08, 'l1_ratio': 0.7313766404898804, 'learning_rate': 'optimal', 'eta0': 0.00015917228898913087, 'epsilon': 0.011854329790540656, 'tol': 0.0012415264173291584, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1967, 'weight_class_0': 0.05103394662187244, 'weight_class_1': 0.10623415159542246, 'weight_class_2': 0.6087517649937135}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  57%|██████████████████████████████████████████████████████████████████████▎                                                     | 34/60 [05:53<07:01, 16.21s/it]

[I 2026-06-26 16:07:02,769] Trial 33 finished with value: 0.9644577138664328 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 3.410932070579074e-08, 'l1_ratio': 0.23354844087233295, 'learning_rate': 'optimal', 'eta0': 0.0002845087344487302, 'epsilon': 0.014231584520674188, 'tol': 1.1646140175528903e-06, 'average': 5, 'class_weight': 'balanced', 'max_iter': 2546, 'weight_class_0': 0.3159473585710959, 'weight_class_1': 9.4677879808218, 'weight_class_2': 0.802499212495282}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  58%|████████████████████████████████████████████████████████████████████████▎                                                   | 35/60 [05:55<05:00, 12.00s/it]

[I 2026-06-26 16:07:04,953] Trial 30 finished with value: 0.9650843839987748 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 1.6203165389959046e-08, 'l1_ratio': 0.5330478281052893, 'learning_rate': 'optimal', 'eta0': 0.00014405539780418461, 'epsilon': 0.01276278711951306, 'tol': 0.006797252431240659, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2269, 'weight_class_0': 0.3118660827146924, 'weight_class_1': 0.06744186132510933, 'weight_class_2': 0.8031111759723614}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  60%|██████████████████████████████████████████████████████████████████████████▍                                                 | 36/60 [05:57<03:35,  8.99s/it]

[I 2026-06-26 16:07:06,901] Trial 32 finished with value: 0.9647373137428069 and parameters: {'loss': 'modified_huber', 'penalty': 'l1', 'alpha': 3.626035118999949e-08, 'l1_ratio': 0.24272666661646364, 'learning_rate': 'optimal', 'eta0': 0.2199767926228417, 'epsilon': 0.013483552584944896, 'tol': 9.775021217314854e-06, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2392, 'weight_class_0': 0.3186933177299071, 'weight_class_1': 1.2396047288262098, 'weight_class_2': 0.6916646281191311}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  62%|████████████████████████████████████████████████████████████████████████████▍                                               | 37/60 [06:08<03:38,  9.50s/it]

[I 2026-06-26 16:07:17,602] Trial 45 finished with value: 0.9650757657360574 and parameters: {'loss': 'perceptron', 'penalty': 'l1', 'alpha': 8.827310270348986e-09, 'l1_ratio': 0.8058432616534676, 'learning_rate': 'invscaling', 'eta0': 0.0005900493570128464, 'power_t': 0.10585617423249852, 'epsilon': 0.030154093050898646, 'tol': 0.0002757875273137059, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1818, 'weight_class_0': 0.10644829502042381, 'weight_class_1': 0.08462043245651116, 'weight_class_2': 1.8182439202210197}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 29. Best value: 0.965175:  63%|██████████████████████████████████████████████████████████████████████████████▌                                             | 38/60 [06:12<02:52,  7.82s/it]

[I 2026-06-26 16:07:21,499] Trial 39 finished with value: 0.9651583126485669 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 5.2537138493771484e-08, 'l1_ratio': 0.6910821269775365, 'learning_rate': 'optimal', 'eta0': 0.00013384510686054055, 'epsilon': 0.009984404728592135, 'tol': 0.0012281755176738335, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1994, 'weight_class_0': 0.06266426492457607, 'weight_class_1': 0.09254669800506334, 'weight_class_2': 0.13627960883206688}. Best is trial 29 with value: 0.9651746932695099.

Best trial: 40. Best value: 0.965181:  65%|████████████████████████████████████████████████████████████████████████████████▌                                           | 39/60 [06:23<03:05,  8.82s/it]

[I 2026-06-26 16:07:32,657] Trial 40 finished with value: 0.9651808005759704 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 2.693221248202336e-08, 'l1_ratio': 0.7017421972439976, 'learning_rate': 'optimal', 'eta0': 0.00010430292142869474, 'epsilon': 0.011503959651262293, 'tol': 0.007951950125426767, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1929, 'weight_class_0': 0.08798084668993786, 'weight_class_1': 0.1118793270245609, 'weight_class_2': 0.6792614151438167}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  67%|██████████████████████████████████████████████████████████████████████████████████▋                                         | 40/60 [06:43<04:07, 12.38s/it]

[I 2026-06-26 16:07:53,363] Trial 28 finished with value: 0.9650084717061101 and parameters: {'loss': 'hinge', 'penalty': 'elasticnet', 'alpha': 1.3329820996742024e-09, 'l1_ratio': 0.5278548305902624, 'learning_rate': 'optimal', 'eta0': 1.326589784369566e-05, 'epsilon': 0.014554958199394542, 'tol': 0.009502326056576629, 'average': 1, 'class_weight': 'balanced', 'max_iter': 3978, 'weight_class_0': 0.33698964613717025, 'weight_class_1': 0.053295714324778254, 'weight_class_2': 0.7380773275971728}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  68%|████████████████████████████████████████████████████████████████████████████████████▋                                       | 41/60 [07:05<04:47, 15.15s/it]

[I 2026-06-26 16:08:14,955] Trial 50 finished with value: 0.9645034511038177 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 2.283884355491137e-07, 'l1_ratio': 0.6297365441655256, 'learning_rate': 'optimal', 'eta0': 6.963602491748844e-05, 'epsilon': 0.003977977791796352, 'tol': 0.005303504281591172, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1713, 'weight_class_0': 0.092682527100435, 'weight_class_1': 0.17182393672375182, 'weight_class_2': 0.1265410816441479}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  70%|██████████████████████████████████████████████████████████████████████████████████████▊                                     | 42/60 [07:08<03:27, 11.51s/it]

[I 2026-06-26 16:08:17,996] Trial 27 finished with value: 0.9650952759713018 and parameters: {'loss': 'hinge', 'penalty': 'elasticnet', 'alpha': 1.350195166562259e-09, 'l1_ratio': 0.6540920106382595, 'learning_rate': 'optimal', 'eta0': 1.2524119790161124e-05, 'epsilon': 0.016927134101841247, 'tol': 0.007721409965526817, 'average': 1, 'class_weight': 'balanced', 'max_iter': 4073, 'weight_class_0': 0.35325068872613474, 'weight_class_1': 0.05050118804019525, 'weight_class_2': 1.0343450923685034}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  72%|████████████████████████████████████████████████████████████████████████████████████████▊                                   | 43/60 [07:28<03:56, 13.88s/it]

[I 2026-06-26 16:08:37,397] Trial 51 finished with value: 0.9644215509686193 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 2.5309804684252834e-07, 'l1_ratio': 0.817030464986617, 'learning_rate': 'optimal', 'eta0': 5.081782307941215e-05, 'epsilon': 0.004391309218366881, 'tol': 0.004051456575822979, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1399, 'weight_class_0': 0.09754574102122023, 'weight_class_1': 0.16491467144354768, 'weight_class_2': 0.1176917742224852}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  73%|██████████████████████████████████████████████████████████████████████████████████████████▉                                 | 44/60 [07:58<05:00, 18.80s/it]

[I 2026-06-26 16:09:07,667] Trial 44 finished with value: 0.9650555123023379 and parameters: {'loss': 'perceptron', 'penalty': 'l1', 'alpha': 1.526416151131705e-08, 'l1_ratio': 0.8120891185568672, 'learning_rate': 'optimal', 'eta0': 0.0004910984246415397, 'epsilon': 0.016126134922022764, 'tol': 0.0056985667467613944, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1817, 'weight_class_0': 0.10117734334077315, 'weight_class_1': 0.07790764462011252, 'weight_class_2': 0.1348293086386762}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  75%|█████████████████████████████████████████████████████████████████████████████████████████████                               | 45/60 [08:53<07:25, 29.68s/it]

[I 2026-06-26 16:10:02,755] Trial 41 finished with value: 0.9650145630443481 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 7.0079208519582055e-09, 'l1_ratio': 0.7077536386987517, 'learning_rate': 'optimal', 'eta0': 0.00011725966002800129, 'epsilon': 0.012188731096446637, 'tol': 0.0012722863256448605, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1917, 'weight_class_0': 0.09805808944098351, 'weight_class_1': 0.11747462080105897, 'weight_class_2': 0.6075402236334061}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  77%|███████████████████████████████████████████████████████████████████████████████████████████████                             | 46/60 [08:55<04:58, 21.31s/it]

[I 2026-06-26 16:10:04,511] Trial 47 finished with value: 0.9648396941639543 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 8.549663545128338e-09, 'l1_ratio': 0.6471216707835006, 'learning_rate': 'optimal', 'eta0': 6.876194438982112e-05, 'epsilon': 0.034475848239971074, 'tol': 0.005898278488126949, 'average': True, 'class_weight': 'balanced', 'max_iter': 1743, 'weight_class_0': 0.09803714411835968, 'weight_class_1': 0.14885859425823353, 'weight_class_2': 1.588171858163839}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 47/60 [09:03<03:47, 17.48s/it]

[I 2026-06-26 16:10:13,069] Trial 56 pruned.

Best trial: 40. Best value: 0.965181:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 48/60 [09:05<02:33, 12.77s/it]

[I 2026-06-26 16:10:14,844] Trial 57 pruned.

Best trial: 40. Best value: 0.965181:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 49/60 [09:07<01:44,  9.52s/it]

[I 2026-06-26 16:10:16,791] Trial 42 finished with value: 0.9651066602113909 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 1.1653515170383456e-08, 'l1_ratio': 0.7695538089183636, 'learning_rate': 'optimal', 'eta0': 0.00011105315436260761, 'epsilon': 0.010592455590119976, 'tol': 0.00024871143381072496, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1799, 'weight_class_0': 0.052325532632143526, 'weight_class_1': 0.09926680716774969, 'weight_class_2': 1.7174934362568555}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 50/60 [09:09<01:11,  7.14s/it]

[I 2026-06-26 16:10:18,390] Trial 48 finished with value: 0.9649134222410053 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 9.255769596061917e-09, 'l1_ratio': 0.6368560514027577, 'learning_rate': 'optimal', 'eta0': 5.545522316928265e-05, 'epsilon': 0.004261593570449098, 'tol': 0.005184798153182568, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1592, 'weight_class_0': 0.10936783722509985, 'weight_class_1': 0.1427607712588356, 'weight_class_2': 0.12712901845756844}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 51/60 [09:15<01:02,  6.93s/it]

[I 2026-06-26 16:10:24,818] Trial 53 pruned.

Best trial: 40. Best value: 0.965181:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 52/60 [09:16<00:40,  5.03s/it]

[I 2026-06-26 16:10:25,420] Trial 49 finished with value: 0.9649013164412839 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 7.734320304397924e-09, 'l1_ratio': 0.6257929607480234, 'learning_rate': 'optimal', 'eta0': 6.25554342199477e-05, 'epsilon': 0.004424782091727392, 'tol': 0.004780579433362574, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1659, 'weight_class_0': 0.10411391443252334, 'weight_class_1': 0.1482642996124448, 'weight_class_2': 0.12122024600037921}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 40. Best value: 0.965181:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 53/60 [09:16<00:26,  3.79s/it]

[I 2026-06-26 16:10:26,302] Trial 58 pruned.

Best trial: 40. Best value: 0.965181:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 54/60 [09:19<00:20,  3.50s/it]

[I 2026-06-26 16:10:29,112] Trial 46 finished with value: 0.9650622361974731 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 7.684398155764491e-09, 'l1_ratio': 0.8172995305251177, 'learning_rate': 'optimal', 'eta0': 7.151902536661733e-05, 'epsilon': 0.030738651028614734, 'tol': 0.004265223037156797, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1787, 'weight_class_0': 0.11801040377142212, 'weight_class_1': 0.14448121635667344, 'weight_class_2': 1.598669561797329}. Best is trial 40 with value: 0.9651808005759704.

Best trial: 43. Best value: 0.965183:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 55/60 [09:42<00:46,  9.26s/it]

[I 2026-06-26 16:10:51,832] Trial 43 finished with value: 0.9651826343119738 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 9.689736169307372e-09, 'l1_ratio': 0.770062125020043, 'learning_rate': 'optimal', 'eta0': 0.00039626607675890006, 'epsilon': 0.015450027627626357, 'tol': 0.001122221127192132, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1876, 'weight_class_0': 0.09687765950579234, 'weight_class_1': 0.10015647111318432, 'weight_class_2': 1.5646633284138467}. Best is trial 43 with value: 0.9651826343119738.

Best trial: 43. Best value: 0.965183:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 56/60 [10:03<00:51, 12.79s/it]

[I 2026-06-26 16:11:12,841] Trial 52 finished with value: 0.9650109649110291 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 6.696432589153425e-09, 'l1_ratio': 0.8110126823032032, 'learning_rate': 'optimal', 'eta0': 7.631940053296591e-05, 'epsilon': 0.018660889363666836, 'tol': 0.005406782420845199, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1505, 'weight_class_0': 0.13318395347587716, 'weight_class_1': 0.14061295234783608, 'weight_class_2': 1.3917955242249735}. Best is trial 43 with value: 0.9651826343119738.

Best trial: 43. Best value: 0.965183:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 57/60 [10:51<01:10, 23.48s/it]

[I 2026-06-26 16:12:01,258] Trial 55 finished with value: 0.9651357501136756 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 7.964417219851478e-09, 'l1_ratio': 0.6317951345327052, 'learning_rate': 'optimal', 'eta0': 6.0218616578010916e-05, 'epsilon': 0.008082539910416001, 'tol': 0.0016808378144047235, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1593, 'weight_class_0': 0.14110194517430508, 'weight_class_1': 0.12049304885963458, 'weight_class_2': 1.6648341129526645}. Best is trial 43 with value: 0.9651826343119738.

Best trial: 43. Best value: 0.965183:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 58/60 [10:55<00:35, 17.58s/it]

[I 2026-06-26 16:12:05,096] Trial 54 finished with value: 0.9650363817898017 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 5.504406447375479e-09, 'l1_ratio': 0.6302792132230632, 'learning_rate': 'optimal', 'eta0': 6.369381400906912e-05, 'epsilon': 0.008164570562087588, 'tol': 0.001434970308348108, 'average': 1, 'class_weight': 'balanced', 'max_iter': 2905, 'weight_class_0': 0.13103548438569954, 'weight_class_1': 0.1297748122224722, 'weight_class_2': 1.3888363969434463}. Best is trial 43 with value: 0.9651826343119738.

Best trial: 43. Best value: 0.965183:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 59/60 [11:03<00:14, 14.57s/it]

[I 2026-06-26 16:12:12,634] Trial 26 finished with value: 0.9649857983290072 and parameters: {'loss': 'hinge', 'penalty': 'elasticnet', 'alpha': 1.0164652601501406e-09, 'l1_ratio': 0.6217147014824294, 'learning_rate': 'optimal', 'eta0': 2.035870661892815e-05, 'epsilon': 0.01984965181360695, 'tol': 1.0349387693670746e-06, 'average': 1, 'class_weight': 'balanced', 'max_iter': 4048, 'weight_class_0': 0.4809187160421657, 'weight_class_1': 0.05304314600534901, 'weight_class_2': 0.9969268416943458}. Best is trial 43 with value: 0.9651826343119738.

Best trial: 43. Best value: 0.965183: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [12:00<00:00, 12.01s/it]

[I 2026-06-26 16:13:10,254] Trial 59 finished with value: 0.9651298059054303 and parameters: {'loss': 'hinge', 'penalty': 'l1', 'alpha': 4.3556894549052916e-09, 'l1_ratio': 0.7641990807157217, 'learning_rate': 'optimal', 'eta0': 0.0008201683031529088, 'epsilon': 0.020958397903830486, 'tol': 0.0009820596028975086, 'average': 1, 'class_weight': 'balanced', 'max_iter': 1390, 'weight_class_0': 0.13725246350847753, 'weight_class_1': 0.20226164009486253, 'weight_class_2': 0.23521733487234062}. Best is trial 43 with value: 0.9651826343119738.

Best trial score:
0.9651826343119738

Best params:
{'loss': 'hinge', 'penalty': 'l1', 'alpha': 9.689736169307372e-09, 'l1_ratio': 0.770062125020043, 'learning_rate': 'optimal', 'eta0': 0.00039626607675890006, 'epsilon': 0.015450027627626357, 'tol': 0.001122221127192132, 'average': True, 'class_weight': 'balanced', 'max_iter': 1876, 'weight_class_0': 0.09687765950579234, 'weight_class_1': 0.10015647111318432, 'weight_class_2': 1.5646633284138467}

In [7]:
# study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=500, n_jobs=-1, show_progress_bar=True)

# print("\nBest trial score:")
# print(study.best_trial.value)

# print("\nBest params:")
# print(study.best_trial.params)

In [8]:
sgd_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

sgd = SGDClassifier(
    **sgd_params,
    random_state=42,
    n_jobs=1
).fit(X_train, y_train.class_encoded)

loss = sgd_params['loss']

if loss in ["log_loss", "modified_huber"]:
    test_proba = sgd.predict_proba(X_test)

else:
    test_proba = sgd.decision_function(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [9]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [10]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_sgd.csv', index=False)

In [11]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [12]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'lg_0', 'lg_1', 'lg_2', 'sgd_0', 'sgd_1', 'sgd_2'],
      dtype='str')

In [13]:
len(study.trials)

60