# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/X_train_stacking_layer_two.parquet')
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_two.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.999980,0.000019,7.173664e-07,0.999940,0.000059,0.000001,0.999902,0.000087,0.000011,0.999964,0.000035,9.391767e-07,9.999364e-01,0.000064,0.000000,0.998533,0.001276,0.000191
1,0.993270,0.000283,6.446509e-03,0.994368,0.000245,0.005387,0.993982,0.000245,0.005772,0.992230,0.000265,7.504966e-03,9.951892e-01,0.000171,0.004639,0.972023,0.002391,0.025586
2,0.000034,0.999962,4.381048e-06,0.000139,0.999859,0.000002,0.000214,0.999774,0.000012,0.000013,0.999981,6.276192e-06,3.944814e-07,1.000000,0.000000,0.000114,0.999862,0.000024
3,0.999879,0.000120,7.617780e-07,0.999812,0.000187,0.000001,0.999843,0.000145,0.000012,0.999931,0.000069,5.789762e-07,9.998199e-01,0.000180,0.000000,0.998349,0.001455,0.000196
4,0.997913,0.002069,1.828613e-05,0.998790,0.001202,0.000008,0.998263,0.001704,0.000033,0.996330,0.003666,3.709336e-06,9.977873e-01,0.002205,0.000008,0.994559,0.004657,0.000784

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.998106,0.001851,0.000042,0.997287,0.002522,0.000192,0.998122,0.001845,0.000033,0.993568,0.006380,0.000053,0.998112,0.001858,0.000030,0.991100,0.006021,0.002879
1,0.997635,0.002352,0.000014,0.997773,0.002224,0.000003,0.997897,0.002071,0.000032,0.996850,0.003147,0.000003,0.998374,0.001623,0.000003,0.993814,0.005762,0.000424
2,0.997136,0.001323,0.001541,0.997897,0.000212,0.001892,0.997850,0.000528,0.001622,0.992689,0.000960,0.006351,0.997662,0.000721,0.001618,0.987143,0.003596,0.009262
3,0.000485,0.000066,0.999449,0.001142,0.000192,0.998666,0.000653,0.000081,0.999266,0.000062,0.000010,0.999928,0.000413,0.000015,0.999572,0.000552,0.000322,0.999126
4,0.999485,0.000510,0.000004,0.999636,0.000360,0.000003,0.999666,0.000319,0.000016,0.999455,0.000531,0.000014,0.999776,0.000222,0.000002,0.998133,0.001603,0.000264

# Machine Learning

In [8]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx, :]
        X_valid_fold = X.iloc[valid_idx, :]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        solver = trial.suggest_categorical("solver", ["svd", "lsqr", "eigen"])
        shrinkage = None
        tol = 0.0001

        if solver in ["lsqr", "eigen"]:
            shrinkage = trial.suggest_float("shrinkage", 0.0, 1.0)

        if solver == "svd":
            tol = trial.suggest_float("tol", 1e-5, 1e-3, log=True)

        params = {
            "solver": solver,
            "shrinkage": shrinkage,
            "tol": tol
        }
        
        model = LinearDiscriminantAnalysis(**params).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)

        w0 = trial.suggest_float('weight_class_0', 0.1, 100.0)
        w1 = trial.suggest_float('weight_class_1', 0.1, 100.0)
        w2 = trial.suggest_float('weight_class_2', 0.1, 100.0)

        weights = np.array([w0, w1, w2])
        weighted_probas = proba * weights

        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=120, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-16 17:33:00,867] A new study created in memory with name: no-name-7a7a0716-9c09-4e7e-aa64-49e772ccce90
Best trial: 0. Best value: 0.961828:   1%|█▏                                                                                                                                        | 1/120 [00:08<16:08,  8.14s/it]

[I 2026-06-16 17:33:08,986] Trial 0 finished with value: 0.961828181048854 and parameters: {'solver': 'lsqr', 'shrinkage': 0.6211592122685499, 'weight_class_0': 39.02841183483406, 'weight_class_1': 7.179990423571741, 'weight_class_2': 41.89119129334394}. Best is trial 0 with value: 0.961828181048854.

[I 2026-06-16 17:33:10,197] Trial 11 finished with value: 0.9589576621537717 and parameters: {'solver': 'lsqr', 'shrinkage': 0.04148010460643481, 'weight_class_0': 23.028866441111138, 'weight_class_1': 22.657759345841207, 'weight_class_2': 57.29762723706113}. Best is trial 0 with value: 0.961828181048854.

[I 2026-06-16 17:33:10,264] Trial 5 finished with value: 0.9593818575874898 and parameters: {'solver': 'eigen', 'shrinkage': 0.04487390966375282, 'weight_class_0': 21.291931343338362, 'weight_class_1': 68.79794091132335, 'weight_class_2': 93.08898109250971}. Best is trial 0 with value: 0.961828181048854.
[I 2026-06-16 17:33:10,294] Trial 4 finished with value: 0.9624840622580102 and parameters: {'solver': 'eigen', 'shrinkage': 0.7701498108570852, 'weight_class_0': 69.61731779480208, 'weight_class_1': 37.20150065515457, 'weight_class_2': 64.30012255578146}. Best is trial 4 with value: 0.9624840622580102.
[I 2026-06-16 17:33:10,304] Trial 1 finished with value: 0.9584652157831108 and parameters: {'solver': 'lsqr', 'shrinkage': 0.05999369396652576, 'weight_class_0': 63.480249862711695, 'weight_class_1': 15.513311100474095, 'weight_class_2': 54.0812224009997}. Best is trial 4 with value: 0.9624840622580102.
[I 2026-06-16 17:33:10,568] Trial 9 pruned.

Best trial: 4. Best value: 0.962484:   8%|██████████▎                                                                                                                               | 9/120 [00:10<00:59,  1.85it/s]

[I 2026-06-16 17:33:10,590] Trial 10 pruned.
[I 2026-06-16 17:33:10,607] Trial 2 pruned.
[I 2026-06-16 17:33:10,673] Trial 6 pruned.
[I 2026-06-16 17:33:11,015] Trial 3 pruned.

Best trial: 4. Best value: 0.962484:   9%|████████████▌                                                                                                                            | 11/120 [00:10<00:31,  3.48it/s]

[I 2026-06-16 17:33:11,051] Trial 7 pruned.
[I 2026-06-16 17:33:11,190] Trial 8 pruned.

Best trial: 4. Best value: 0.962484:  11%|██████████████▊                                                                                                                          | 13/120 [00:12<01:00,  1.75it/s]

[I 2026-06-16 17:33:13,401] Trial 12 pruned.

Best trial: 4. Best value: 0.962484:  12%|███████████████▉                                                                                                                         | 14/120 [00:14<01:28,  1.20it/s]

[I 2026-06-16 17:33:15,387] Trial 15 finished with value: 0.9623423814598739 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7263775207164753, 'weight_class_0': 69.66798402466529, 'weight_class_1': 41.98995034146134, 'weight_class_2': 69.42498155195406}. Best is trial 4 with value: 0.9624840622580102.

Best trial: 4. Best value: 0.962484:  12%|█████████████████▏                                                                                                                       | 15/120 [00:14<01:13,  1.42it/s]

[I 2026-06-16 17:33:15,605] Trial 14 finished with value: 0.9623998870317635 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7384031892415899, 'weight_class_0': 71.75931773682436, 'weight_class_1': 44.18091033511875, 'weight_class_2': 73.70941644299614}. Best is trial 4 with value: 0.9624840622580102.

Best trial: 13. Best value: 0.962929:  14%|███████████████████▎                                                                                                                    | 17/120 [00:15<00:48,  2.11it/s]

[I 2026-06-16 17:33:15,817] Trial 16 finished with value: 0.962373937616787 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7346565378566557, 'weight_class_0': 73.83733362791057, 'weight_class_1': 42.589526128324465, 'weight_class_2': 74.33292870092392}. Best is trial 4 with value: 0.9624840622580102.
[I 2026-06-16 17:33:15,951] Trial 21 finished with value: 0.9628674647320346 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7117757878480858, 'weight_class_0': 5.596044211756016, 'weight_class_1': 43.138608961927204, 'weight_class_2': 75.03335887687624}. Best is trial 21 with value: 0.9628674647320346.
[I 2026-06-16 17:33:15,980] Trial 13 finished with value: 0.9629292565032921 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7339350958023745, 'weight_class_0': 4.220699278550633, 'weight_class_1': 41.66644802912967, 'weight_class_2': 72.7674222452963}. Best is trial 13 with value: 0.9629292565032921.

[I 2026-06-16 17:33:16,054] Trial 19 finished with value: 0.9623990039827719 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7377757563697102, 'weight_class_0': 70.39927373180247, 'weight_class_1': 44.02648468363749, 'weight_class_2': 73.42615589315605}. Best is trial 13 with value: 0.9629292565032921.
[I 2026-06-16 17:33:16,062] Trial 23 finished with value: 0.9628318990223109 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7237261940218773, 'weight_class_0': 6.928189891035927, 'weight_class_1': 44.67523921540462, 'weight_class_2': 72.01823288062438}. Best is trial 13 with value: 0.9629292565032921.
[I 2026-06-16 17:33:16,068] Trial 18 finished with value: 0.963193193348685 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7703161051564085, 'weight_class_0': 1.1484439038207057, 'weight_class_1': 42.11486973065464, 'weight_class_2': 73.5050051012846}. Best is trial 18 with value: 0.963193193348685.

Best trial: 18. Best value: 0.963193:  18%|████████████████████████▉                                                                                                               | 22/120 [00:15<00:14,  6.59it/s]

[I 2026-06-16 17:33:16,192] Trial 17 finished with value: 0.9623786537510771 and parameters: {'solver': 'lsqr', 'shrinkage': 0.733383192687347, 'weight_class_0': 72.28122114916083, 'weight_class_1': 40.99996655139962, 'weight_class_2': 73.84320420545319}. Best is trial 18 with value: 0.963193193348685.
[I 2026-06-16 17:33:16,412] Trial 20 finished with value: 0.9628143741609003 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7031372292878713, 'weight_class_0': 6.14308927791555, 'weight_class_1': 46.12373947708824, 'weight_class_2': 69.34165316938746}. Best is trial 18 with value: 0.963193193348685.

Best trial: 18. Best value: 0.963193:  20%|███████████████████████████▏                                                                                                            | 24/120 [00:15<00:15,  6.01it/s]

[I 2026-06-16 17:33:16,589] Trial 22 finished with value: 0.9629177305555621 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7202849557201112, 'weight_class_0': 4.212763028829173, 'weight_class_1': 45.83154121164207, 'weight_class_2': 73.86952593282751}. Best is trial 18 with value: 0.963193193348685.

Best trial: 24. Best value: 0.963228:  21%|████████████████████████████▎                                                                                                           | 25/120 [00:17<00:47,  2.01it/s]

[I 2026-06-16 17:33:18,677] Trial 24 finished with value: 0.9632279170866009 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7179339070655235, 'weight_class_0': 0.5525699222759357, 'weight_class_1': 44.528399054591304, 'weight_class_2': 68.24195573959808}. Best is trial 24 with value: 0.9632279170866009.

Best trial: 26. Best value: 0.963471:  22%|█████████████████████████████▍                                                                                                          | 26/120 [00:19<01:11,  1.32it/s]

[I 2026-06-16 17:33:20,476] Trial 26 finished with value: 0.9634708587610985 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9873176415216713, 'weight_class_0': 0.5594960847654633, 'weight_class_1': 70.61078215573698, 'weight_class_2': 84.80612434371004}. Best is trial 26 with value: 0.9634708587610985.

Best trial: 27. Best value: 0.963503:  22%|██████████████████████████████▌                                                                                                         | 27/120 [00:20<01:03,  1.47it/s]

[I 2026-06-16 17:33:20,861] Trial 27 finished with value: 0.9635028417039697 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9421114501674475, 'weight_class_0': 0.25902186115410997, 'weight_class_1': 58.75804152155732, 'weight_class_2': 86.02186770623867}. Best is trial 27 with value: 0.9635028417039697.

Best trial: 32. Best value: 0.963515:  26%|███████████████████████████████████▏                                                                                                    | 31/120 [00:20<00:27,  3.19it/s]

[I 2026-06-16 17:33:21,204] Trial 28 finished with value: 0.9633373275877137 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9479382330364068, 'weight_class_0': 2.0939280303079433, 'weight_class_1': 58.586305806930284, 'weight_class_2': 84.28963412390746}. Best is trial 27 with value: 0.9635028417039697.
[I 2026-06-16 17:33:21,220] Trial 31 finished with value: 0.9630807233552507 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8856083994737276, 'weight_class_0': 15.38672413940934, 'weight_class_1': 58.04514952996745, 'weight_class_2': 87.54428919009452}. Best is trial 27 with value: 0.9635028417039697.
[I 2026-06-16 17:33:21,249] Trial 30 finished with value: 0.9633601313676265 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9444742395684601, 'weight_class_0': 1.6696083298442068, 'weight_class_1': 58.67866917880971, 'weight_class_2': 84.93553675844524}. Best is trial 27 with value: 0.9635028417039697.
[I 2026-06-16 17:33:21,259] Trial 25 finished with value: 0.9634596468587358 and parameters: {'solver': 'eigen', 'shrinkage': 0.9666460003849584, 'weight_class_0': 0.5773310339985045, 'weight_class_1': 55.50987094161708, 'weight_class_2': 76.26625967988662}. Best is trial 27 with value: 0.9635028417039697.
[I 2026-06-16 17:33:21,339] Trial 32 finished with value: 0.9635152308374844 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9320478085138038, 'weight_class_0': 0.2488670497974761, 'weight_class_1': 57.61876128920343, 'weight_class_2': 87.34365723335826}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  28%|█████████████████████████████████████▍                                                                                                  | 33/120 [00:20<00:20,  4.32it/s]

[I 2026-06-16 17:33:21,403] Trial 29 finished with value: 0.9633521769766181 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9360618231127734, 'weight_class_0': 1.608701663764338, 'weight_class_1': 62.64941106694039, 'weight_class_2': 86.70314097103284}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  29%|███████████████████████████████████████▋                                                                                                | 35/120 [00:21<00:20,  4.19it/s]

[I 2026-06-16 17:33:21,855] Trial 33 finished with value: 0.9631851716751522 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9333417742316426, 'weight_class_0': 14.99676772000158, 'weight_class_1': 58.1706407603001, 'weight_class_2': 96.42974272606048}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:21,953] Trial 35 finished with value: 0.9632156814863482 and parameters: {'solver': 'lsqr', 'shrinkage': 0.958949118921612, 'weight_class_0': 15.886047226740127, 'weight_class_1': 59.0057490069049, 'weight_class_2': 96.52227503233323}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:21,946] Trial 34 finished with value: 0.9632047436613158 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9480050005222979, 'weight_class_0': 15.428076448363555, 'weight_class_1': 56.02247655986049, 'weight_class_2': 86.07005609813355}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  31%|█████████████████████████████████████████▉                                                                                              | 37/120 [00:22<00:33,  2.45it/s]

[I 2026-06-16 17:33:23,489] Trial 36 finished with value: 0.9631720887498896 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9356799702742417, 'weight_class_0': 16.461178217497483, 'weight_class_1': 58.45552361140657, 'weight_class_2': 85.268804013975}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  32%|███████████████████████████████████████████                                                                                             | 38/120 [00:24<01:00,  1.36it/s]

[I 2026-06-16 17:33:25,741] Trial 37 finished with value: 0.9632454005051937 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9867589320021122, 'weight_class_0': 15.842702812126275, 'weight_class_1': 69.36181450595737, 'weight_class_2': 84.5959416244847}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  32%|████████████████████████████████████████████▏                                                                                           | 39/120 [00:25<00:56,  1.43it/s]

[I 2026-06-16 17:33:26,286] Trial 38 finished with value: 0.9632256052554983 and parameters: {'solver': 'eigen', 'shrinkage': 0.9549544493937427, 'weight_class_0': 12.666057159939268, 'weight_class_1': 77.76831644944153, 'weight_class_2': 99.68857736024124}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  33%|█████████████████████████████████████████████▎                                                                                          | 40/120 [00:26<00:56,  1.41it/s]

[I 2026-06-16 17:33:27,029] Trial 48 pruned.

Best trial: 32. Best value: 0.963515:  36%|████████████████████████████████████████████████▋                                                                                       | 43/120 [00:26<00:30,  2.48it/s]

[I 2026-06-16 17:33:27,407] Trial 42 finished with value: 0.9632968292946904 and parameters: {'solver': 'eigen', 'shrinkage': 0.9996311338789501, 'weight_class_0': 13.751425661901663, 'weight_class_1': 76.70906802431873, 'weight_class_2': 98.20556839061648}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,412] Trial 40 finished with value: 0.9630513917635426 and parameters: {'solver': 'eigen', 'shrinkage': 0.8559969558335684, 'weight_class_0': 13.263460987543601, 'weight_class_1': 76.94907824633378, 'weight_class_2': 99.08062665247948}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,429] Trial 43 finished with value: 0.9630362614699693 and parameters: {'solver': 'eigen', 'shrinkage': 0.8556121310293952, 'weight_class_0': 14.137244863637765, 'weight_class_1': 78.20921597484185, 'weight_class_2': 99.98001801135464}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,503] Trial 45 finished with value: 0.9629368507669245 and parameters: {'solver': 'eigen', 'shrinkage': 0.8463637503156831, 'weight_class_0': 29.42685996628872, 'weight_class_1': 76.15150917939802, 'weight_class_2': 80.92030729118035}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  38%|████████████████████████████████████████████████████▏                                                                                   | 46/120 [00:26<00:17,  4.23it/s]

[I 2026-06-16 17:33:27,648] Trial 47 finished with value: 0.9629363870679815 and parameters: {'solver': 'eigen', 'shrinkage': 0.8585357485232424, 'weight_class_0': 30.877593982076345, 'weight_class_1': 74.4378868626824, 'weight_class_2': 80.10824236021408}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,722] Trial 39 finished with value: 0.9630521968217203 and parameters: {'solver': 'eigen', 'shrinkage': 0.8647465326633101, 'weight_class_0': 13.610644271155971, 'weight_class_1': 78.24144549522649, 'weight_class_2': 99.40516693138724}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  41%|███████████████████████████████████████████████████████▌                                                                                | 49/120 [00:27<00:12,  5.50it/s]

[I 2026-06-16 17:33:27,874] Trial 41 finished with value: 0.963055231798925 and parameters: {'solver': 'eigen', 'shrinkage': 0.8635782951128906, 'weight_class_0': 14.246021644533258, 'weight_class_1': 78.597456128255, 'weight_class_2': 97.84333221550875}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,881] Trial 46 finished with value: 0.9629508431888112 and parameters: {'solver': 'eigen', 'shrinkage': 0.8518227034537571, 'weight_class_0': 29.78725920752498, 'weight_class_1': 74.9522390734388, 'weight_class_2': 99.95023043693789}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:27,890] Trial 44 finished with value: 0.963021470939989 and parameters: {'solver': 'eigen', 'shrinkage': 0.8436380022652479, 'weight_class_0': 13.699415570054594, 'weight_class_1': 80.78163923146394, 'weight_class_2': 82.96587545259857}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  42%|████████████████████████████████████████████████████████▋                                                                               | 50/120 [00:31<01:04,  1.08it/s]

[I 2026-06-16 17:33:31,674] Trial 49 pruned.

Best trial: 32. Best value: 0.963515:  42%|█████████████████████████████████████████████████████████▊                                                                              | 51/120 [00:32<01:04,  1.06it/s]

[I 2026-06-16 17:33:32,846] Trial 50 pruned.

Best trial: 32. Best value: 0.963515:  43%|██████████████████████████████████████████████████████████▉                                                                             | 52/120 [00:34<01:32,  1.36s/it]

[I 2026-06-16 17:33:35,514] Trial 51 pruned.

Best trial: 32. Best value: 0.963515:  44%|████████████████████████████████████████████████████████████                                                                            | 53/120 [00:35<01:20,  1.20s/it]

[I 2026-06-16 17:33:36,260] Trial 52 pruned.

[I 2026-06-16 17:33:38,212] Trial 58 pruned.

[I 2026-06-16 17:33:38,247] Trial 54 pruned.
[I 2026-06-16 17:33:38,888] Trial 56 pruned.
[I 2026-06-16 17:33:38,906] Trial 55 pruned.
[I 2026-06-16 17:33:38,909] Trial 59 pruned.

Best trial: 32. Best value: 0.963515:  49%|██████████████████████████████████████████████████████████████████▊                                                                     | 59/120 [00:38<00:33,  1.81it/s]

[I 2026-06-16 17:33:39,011] Trial 53 pruned.
[I 2026-06-16 17:33:39,510] Trial 60 pruned.

Best trial: 32. Best value: 0.963515:  51%|█████████████████████████████████████████████████████████████████████▏                                                                  | 61/120 [00:38<00:25,  2.35it/s]

[I 2026-06-16 17:33:39,703] Trial 57 pruned.

Best trial: 32. Best value: 0.963515:  52%|██████████████████████████████████████████████████████████████████████▎                                                                 | 62/120 [00:40<00:32,  1.78it/s]

[I 2026-06-16 17:33:40,900] Trial 61 pruned.

Best trial: 32. Best value: 0.963515:  52%|███████████████████████████████████████████████████████████████████████▍                                                                | 63/120 [00:41<00:44,  1.28it/s]

[I 2026-06-16 17:33:42,519] Trial 64 pruned.
[I 2026-06-16 17:33:42,582] Trial 62 pruned.

Best trial: 32. Best value: 0.963515:  54%|█████████████████████████████████████████████████████████████████████████▋                                                              | 65/120 [00:42<00:32,  1.70it/s]

[I 2026-06-16 17:33:43,064] Trial 63 pruned.

Best trial: 32. Best value: 0.963515:  55%|██████████████████████████████████████████████████████████████████████████▊                                                             | 66/120 [00:43<00:36,  1.49it/s]

[I 2026-06-16 17:33:44,020] Trial 70 pruned.

Best trial: 32. Best value: 0.963515:  57%|█████████████████████████████████████████████████████████████████████████████                                                           | 68/120 [00:44<00:40,  1.28it/s]

[I 2026-06-16 17:33:45,191] Trial 65 finished with value: 0.9633587319666941 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9130834345362001, 'weight_class_0': 1.3188704669865596, 'weight_class_1': 64.09073082025246, 'weight_class_2': 89.34335121817738}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:45,226] Trial 67 finished with value: 0.9634904183199644 and parameters: {'solver': 'lsqr', 'shrinkage': 0.903236591250854, 'weight_class_0': 0.3336453310188181, 'weight_class_1': 64.82128651244382, 'weight_class_2': 88.40514487014873}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:45,319] Trial 68 finished with value: 0.9630919679674991 and parameters: {'solver': 'lsqr', 'shrinkage': 0.47499620445130925, 'weight_class_0': 0.3372270152514751, 'weight_class_1': 63.82254975115583, 'weight_class_2': 90.09782757388554}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 32. Best value: 0.963515:  59%|████████████████████████████████████████████████████████████████████████████████▍                                                       | 71/120 [00:44<00:19,  2.46it/s]

[I 2026-06-16 17:33:45,676] Trial 69 finished with value: 0.963447034947514 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9128084649318612, 'weight_class_0': 0.6866437704592381, 'weight_class_1': 63.9397064114414, 'weight_class_2': 89.36684161016173}. Best is trial 32 with value: 0.9635152308374844.
[I 2026-06-16 17:33:45,786] Trial 66 finished with value: 0.9632953118134508 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9096482920717693, 'weight_class_0': 2.344752657700089, 'weight_class_1': 62.931562474672255, 'weight_class_2': 89.37326349854882}. Best is trial 32 with value: 0.9635152308374844.

Best trial: 71. Best value: 0.963531:  60%|█████████████████████████████████████████████████████████████████████████████████▌                                                      | 72/120 [00:45<00:17,  2.82it/s]

[I 2026-06-16 17:33:45,977] Trial 71 finished with value: 0.9635310687008729 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9085881852204492, 'weight_class_0': 0.18719043295550875, 'weight_class_1': 66.95300520628852, 'weight_class_2': 89.36236166275735}. Best is trial 71 with value: 0.9635310687008729.

Best trial: 71. Best value: 0.963531:  61%|██████████████████████████████████████████████████████████████████████████████████▋                                                     | 73/120 [00:45<00:20,  2.35it/s]

[I 2026-06-16 17:33:46,642] Trial 72 finished with value: 0.963298268678386 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9137499960676061, 'weight_class_0': 2.1514456502197707, 'weight_class_1': 64.0083130571157, 'weight_class_2': 89.45778781007772}. Best is trial 71 with value: 0.9635310687008729.

Best trial: 73. Best value: 0.963542:  62%|███████████████████████████████████████████████████████████████████████████████████▊                                                    | 74/120 [00:46<00:17,  2.62it/s]

[I 2026-06-16 17:33:46,876] Trial 73 finished with value: 0.9635421694576172 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9083880223465686, 'weight_class_0': 0.17022376591473254, 'weight_class_1': 64.71705174841405, 'weight_class_2': 88.93653177519766}. Best is trial 73 with value: 0.9635421694576172.

Best trial: 73. Best value: 0.963542:  62%|█████████████████████████████████████████████████████████████████████████████████████                                                   | 75/120 [00:46<00:22,  1.99it/s]

[I 2026-06-16 17:33:47,741] Trial 75 finished with value: 0.9632836482731145 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9106390070267045, 'weight_class_0': 1.974173482037582, 'weight_class_1': 62.68556854356953, 'weight_class_2': 47.12617954344093}. Best is trial 73 with value: 0.9635421694576172.

Best trial: 73. Best value: 0.963542:  63%|██████████████████████████████████████████████████████████████████████████████████████▏                                                 | 76/120 [00:47<00:20,  2.17it/s]

[I 2026-06-16 17:33:48,077] Trial 74 finished with value: 0.9633045420337657 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9123370990192424, 'weight_class_0': 1.9091662045149367, 'weight_class_1': 62.5793024183502, 'weight_class_2': 77.33263684429512}. Best is trial 73 with value: 0.9635421694576172.

[I 2026-06-16 17:33:48,385] Trial 76 finished with value: 0.9632936307778224 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9109375405379574, 'weight_class_0': 2.3904466381247405, 'weight_class_1': 62.671065760014116, 'weight_class_2': 87.36820753607613}. Best is trial 73 with value: 0.9635421694576172.
[I 2026-06-16 17:33:48,601] Trial 78 pruned.

Best trial: 77. Best value: 0.963548:  67%|██████████████████████████████████████████████████████████████████████████████████████████▋                                             | 80/120 [00:48<00:12,  3.11it/s]

[I 2026-06-16 17:33:49,092] Trial 77 finished with value: 0.9635480568613104 and parameters: {'solver': 'lsqr', 'shrinkage': 0.912060363991702, 'weight_class_0': 0.14265004353713973, 'weight_class_1': 62.76488128516153, 'weight_class_2': 77.58456296190928}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:49,254] Trial 82 pruned.

Best trial: 77. Best value: 0.963548:  68%|███████████████████████████████████████████████████████████████████████████████████████████▊                                            | 81/120 [00:49<00:16,  2.34it/s]

[I 2026-06-16 17:33:49,921] Trial 84 pruned.

Best trial: 77. Best value: 0.963548:  69%|██████████████████████████████████████████████████████████████████████████████████████████████                                          | 83/120 [00:49<00:13,  2.65it/s]

[I 2026-06-16 17:33:50,566] Trial 79 finished with value: 0.9632166243819548 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9028990248532353, 'weight_class_0': 4.298286905186276, 'weight_class_1': 70.27075943935408, 'weight_class_2': 77.65006216126623}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:50,633] Trial 80 finished with value: 0.963059818156928 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7856812380435381, 'weight_class_0': 3.752558101656583, 'weight_class_1': 70.27669161807825, 'weight_class_2': 78.23063020292024}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  71%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 85/120 [00:50<00:11,  2.92it/s]

[I 2026-06-16 17:33:51,202] Trial 83 finished with value: 0.9633262397434471 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9993511359168842, 'weight_class_0': 4.980699052282801, 'weight_class_1': 69.33673217818993, 'weight_class_2': 78.63795949246799}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:51,323] Trial 81 finished with value: 0.963069943973698 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7996960601019767, 'weight_class_0': 4.2342861361970625, 'weight_class_1': 69.43974493510875, 'weight_class_2': 76.93667636277536}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  72%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 86/120 [00:50<00:09,  3.43it/s]

[I 2026-06-16 17:33:51,503] Trial 87 pruned.
[I 2026-06-16 17:33:51,534] Trial 88 pruned.

Best trial: 77. Best value: 0.963548:  73%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 88/120 [00:51<00:07,  4.13it/s]

[I 2026-06-16 17:33:51,891] Trial 89 pruned.
[I 2026-06-16 17:33:51,956] Trial 85 finished with value: 0.9630400495977774 and parameters: {'solver': 'lsqr', 'shrinkage': 0.7994886813532253, 'weight_class_0': 4.829074433937259, 'weight_class_1': 71.10682248069114, 'weight_class_2': 77.26802157298721}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 90/120 [00:52<00:12,  2.42it/s]

[I 2026-06-16 17:33:53,222] Trial 86 finished with value: 0.9633236950349191 and parameters: {'solver': 'lsqr', 'shrinkage': 0.995851600671011, 'weight_class_0': 5.17245114967578, 'weight_class_1': 69.14616131620815, 'weight_class_2': 94.56861775364348}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 91/120 [00:53<00:15,  1.82it/s]

[I 2026-06-16 17:33:54,252] Trial 90 finished with value: 0.9633197437324617 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9989626295745341, 'weight_class_0': 5.719216401349456, 'weight_class_1': 55.10461319308607, 'weight_class_2': 66.11454983404322}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:54,348] Trial 91 finished with value: 0.9632904516223201 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9817529147795186, 'weight_class_0': 5.770258491748215, 'weight_class_1': 55.25389607682394, 'weight_class_2': 66.59467779347834}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 93/120 [00:54<00:15,  1.76it/s]

[I 2026-06-16 17:33:55,465] Trial 92 finished with value: 0.9633029520229096 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9799863805501102, 'weight_class_0': 5.273156284170596, 'weight_class_1': 55.130900548282405, 'weight_class_2': 82.68412269323366}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 94/120 [00:55<00:14,  1.76it/s]

[I 2026-06-16 17:33:56,008] Trial 94 finished with value: 0.9633103241328023 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9877574054671077, 'weight_class_0': 5.769152558524451, 'weight_class_1': 55.4101585614192, 'weight_class_2': 83.44464556022182}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:56,096] Trial 93 finished with value: 0.9633103241328023 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9861044066640422, 'weight_class_0': 5.512086186706406, 'weight_class_1': 55.33802372194657, 'weight_class_2': 82.2193289589713}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 97/120 [00:55<00:08,  2.82it/s]

[I 2026-06-16 17:33:56,354] Trial 96 finished with value: 0.9632335987630597 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9657503720715775, 'weight_class_0': 11.576673099588465, 'weight_class_1': 54.06538816666746, 'weight_class_2': 82.43175309601415}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:56,489] Trial 95 finished with value: 0.9632407816150638 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9776893970296312, 'weight_class_0': 11.421775021130044, 'weight_class_1': 55.57199990497154, 'weight_class_2': 67.66244586330063}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 99/120 [00:56<00:06,  3.43it/s]

[I 2026-06-16 17:33:56,820] Trial 98 finished with value: 0.9632337101515906 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9710214253473389, 'weight_class_0': 11.47176175837661, 'weight_class_1': 54.957580894238575, 'weight_class_2': 82.46586729993761}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:56,966] Trial 99 finished with value: 0.9635021674104152 and parameters: {'solver': 'lsqr', 'shrinkage': 0.968287314968144, 'weight_class_0': 0.2512128929143591, 'weight_class_1': 55.97963189170424, 'weight_class_2': 82.20667735872522}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 101/120 [00:56<00:04,  4.53it/s]

[I 2026-06-16 17:33:57,036] Trial 97 finished with value: 0.9632171536450835 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9616982562012106, 'weight_class_0': 11.644910916781663, 'weight_class_1': 55.7706319879078, 'weight_class_2': 70.28157709746813}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:33:57,221] Trial 100 finished with value: 0.9631151588727797 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9727811491818354, 'weight_class_0': 61.94902010481468, 'weight_class_1': 55.78513806364814, 'weight_class_2': 83.15572586360865}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 102/120 [00:58<00:11,  1.62it/s]

[I 2026-06-16 17:33:58,859] Trial 101 finished with value: 0.9631083686789891 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9664517973509005, 'weight_class_0': 56.646130011871875, 'weight_class_1': 54.547600098111715, 'weight_class_2': 82.94856305578953}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 103/120 [00:58<00:10,  1.61it/s]

[I 2026-06-16 17:33:59,504] Trial 102 finished with value: 0.963236667260083 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9715873224012808, 'weight_class_0': 10.577603261736227, 'weight_class_1': 59.35206512565498, 'weight_class_2': 82.71449845147013}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 104/120 [00:58<00:08,  1.93it/s]

[I 2026-06-16 17:33:59,757] Trial 103 finished with value: 0.9632107757298011 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9548597763865738, 'weight_class_0': 11.077803217557923, 'weight_class_1': 59.987610415187824, 'weight_class_2': 82.65587635856485}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 105/120 [00:59<00:07,  1.99it/s]

[I 2026-06-16 17:34:00,254] Trial 112 pruned.

Best trial: 77. Best value: 0.963548:  88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 106/120 [01:00<00:07,  1.78it/s]

[I 2026-06-16 17:34:00,894] Trial 104 finished with value: 0.9632188346807122 and parameters: {'solver': 'lsqr', 'shrinkage': 0.95737597427182, 'weight_class_0': 11.46015437994065, 'weight_class_1': 59.48189005185111, 'weight_class_2': 82.73860633187996}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 77. Best value: 0.963548:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 108/120 [01:00<00:06,  1.77it/s]

[I 2026-06-16 17:34:01,491] Trial 106 finished with value: 0.9634220409743184 and parameters: {'solver': 'lsqr', 'shrinkage': 0.881481366855042, 'weight_class_0': 0.5305744686250138, 'weight_class_1': 60.46134601944252, 'weight_class_2': 71.29162557420304}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:34:01,530] Trial 105 finished with value: 0.9634277445960464 and parameters: {'solver': 'lsqr', 'shrinkage': 0.883588943229203, 'weight_class_0': 0.6697967636449081, 'weight_class_1': 59.64215093375426, 'weight_class_2': 85.64400543173993}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:34:01,667] Trial 109 finished with value: 0.9634845563768579 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9353291953452754, 'weight_class_0': 0.4312665388364467, 'weight_class_1': 32.013585509158936, 'weight_class_2': 86.84183844471535}. Best is trial 77 with value: 0.9635480568613104.

[I 2026-06-16 17:34:01,673] Trial 108 finished with value: 0.9633225521743997 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8894625157129676, 'weight_class_0': 1.1802242758403312, 'weight_class_1': 59.883637224061886, 'weight_class_2': 85.39248488451254}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:34:01,959] Trial 107 finished with value: 0.9635003943617028 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9433376575014408, 'weight_class_0': 0.2328718613292525, 'weight_class_1': 35.324147570347606, 'weight_class_2': 70.65474864861534}. Best is trial 77 with value: 0.9635480568613104.

Best trial: 110. Best value: 0.963558:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 113/120 [01:01<00:01,  5.34it/s]

[I 2026-06-16 17:34:02,032] Trial 111 finished with value: 0.9634146614272264 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8808462211369955, 'weight_class_0': 0.7172160267612806, 'weight_class_1': 59.86272125555327, 'weight_class_2': 84.941025392838}. Best is trial 77 with value: 0.9635480568613104.
[I 2026-06-16 17:34:02,090] Trial 110 finished with value: 0.9635581897489761 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8816069104818597, 'weight_class_0': 0.13032685601422409, 'weight_class_1': 60.29193495547739, 'weight_class_2': 85.9716417473798}. Best is trial 110 with value: 0.9635581897489761.

Best trial: 110. Best value: 0.963558:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 114/120 [01:02<00:02,  2.81it/s]

[I 2026-06-16 17:34:03,115] Trial 113 finished with value: 0.9634762895360994 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8895773875263054, 'weight_class_0': 0.2697152508254304, 'weight_class_1': 59.875785280800095, 'weight_class_2': 86.68901835277569}. Best is trial 110 with value: 0.9635581897489761.

Best trial: 110. Best value: 0.963558:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 115/120 [01:02<00:01,  2.54it/s]

[I 2026-06-16 17:34:03,646] Trial 115 finished with value: 0.9635073286110443 and parameters: {'solver': 'lsqr', 'shrinkage': 0.883575926532279, 'weight_class_0': 0.2473133663114584, 'weight_class_1': 66.19593691261416, 'weight_class_2': 86.67158368876105}. Best is trial 110 with value: 0.9635581897489761.
[I 2026-06-16 17:34:03,697] Trial 114 finished with value: 0.9634857276449713 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8825489417961426, 'weight_class_0': 0.2965184820070414, 'weight_class_1': 34.34869426305818, 'weight_class_2': 85.24861141026179}. Best is trial 110 with value: 0.9635581897489761.

Best trial: 110. Best value: 0.963558:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 117/120 [01:03<00:00,  3.43it/s]

[I 2026-06-16 17:34:03,910] Trial 116 finished with value: 0.9631744819202481 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8858925310799832, 'weight_class_0': 1.0883971522790499, 'weight_class_1': 0.20534227315229714, 'weight_class_2': 96.50583232353307}. Best is trial 110 with value: 0.9635581897489761.

Best trial: 110. Best value: 0.963558:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 118/120 [01:03<00:00,  3.31it/s]

[I 2026-06-16 17:34:04,250] Trial 117 finished with value: 0.9635359419252927 and parameters: {'solver': 'lsqr', 'shrinkage': 0.8836404689853112, 'weight_class_0': 0.189629138145367, 'weight_class_1': 66.74251351601525, 'weight_class_2': 86.26385364245772}. Best is trial 110 with value: 0.9635581897489761.
[I 2026-06-16 17:34:04,451] Trial 119 finished with value: 0.9634876247517801 and parameters: {'solver': 'eigen', 'shrinkage': 0.9307526979744185, 'weight_class_0': 0.3269547256106984, 'weight_class_1': 34.629705029148994, 'weight_class_2': 87.89806419225596}. Best is trial 110 with value: 0.9635581897489761.

Best trial: 110. Best value: 0.963558: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [01:03<00:00,  1.89it/s]

[I 2026-06-16 17:34:04,458] Trial 118 finished with value: 0.9635243818357366 and parameters: {'solver': 'lsqr', 'shrinkage': 0.9333429374411465, 'weight_class_0': 0.20455783452251236, 'weight_class_1': 30.833369036484832, 'weight_class_2': 74.77551594417292}. Best is trial 110 with value: 0.9635581897489761.
Best trial score:
0.9635581897489761

Best params:
{'solver': 'lsqr', 'shrinkage': 0.8816069104818597, 'weight_class_0': 0.13032685601422409, 'weight_class_1': 60.29193495547739, 'weight_class_2': 85.9716417473798}

In [14]:
lda_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

model = LinearDiscriminantAnalysis(**lda_params).fit(X_train, y_train.class_encoded)

test_proba = model.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [15]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [16]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lda.csv', index=False)

In [17]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [18]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'hist_0', 'hist_1', 'hist_2', 'rf_0', 'rf_1', 'rf_2',
       'extra_0', 'extra_1', 'extra_2'],
      dtype='str')