# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle
from xgboost import XGBClassifier

from sklearn.metrics import log_loss, balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/X_train_stacking_layer_three.parquet')
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_three.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.999778,0.000212,0.000009,0.999787,0.000174,0.000040,0.999864,0.000121,0.000016,0.999733,0.000264,2.459617e-06,0.999775,0.000225,2.616556e-08,0.998912,0.000955,0.000133
1,0.994627,0.000176,0.005197,0.995247,0.000365,0.004388,0.992235,0.000199,0.007566,0.973059,0.000137,2.680453e-02,0.994737,0.000047,5.216709e-03,0.976808,0.000850,0.022342
2,0.000048,0.999944,0.000008,0.000483,0.999485,0.000032,0.000169,0.999822,0.000009,0.000015,0.999984,1.319155e-06,0.000011,0.999989,9.836632e-08,0.000068,0.999897,0.000035
3,0.999915,0.000081,0.000005,0.999745,0.000217,0.000039,0.999858,0.000127,0.000014,0.999960,0.000040,6.602657e-07,0.999793,0.000207,3.828407e-08,0.998919,0.000947,0.000134
4,0.998164,0.001812,0.000024,0.998143,0.001764,0.000093,0.998504,0.001459,0.000037,0.986426,0.013556,1.806930e-05,0.998227,0.001769,3.566911e-06,0.994430,0.005248,0.000322

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.998177,0.001784,0.000039,0.997654,0.002153,0.000193,0.998108,0.001843,0.000049,0.997980,0.002008,0.000012,0.998183,0.001800,0.000017,0.993598,0.005832,0.000569
1,0.997269,0.002710,0.000021,0.997945,0.001978,0.000077,0.997185,0.002778,0.000037,0.994660,0.005324,0.000015,0.997905,0.002092,0.000003,0.993669,0.005970,0.000361
2,0.996089,0.000609,0.003303,0.997698,0.000711,0.001592,0.997502,0.000382,0.002115,0.997295,0.001499,0.001207,0.997506,0.000715,0.001780,0.988872,0.002584,0.008544
3,0.000643,0.000107,0.999250,0.001658,0.000165,0.998177,0.000730,0.000132,0.999138,0.000139,0.000020,0.999841,0.000541,0.000023,0.999436,0.000378,0.000214,0.999409
4,0.999631,0.000357,0.000012,0.999578,0.000365,0.000058,0.999737,0.000245,0.000018,0.999526,0.000469,0.000005,0.999785,0.000205,0.000010,0.998670,0.001116,0.000214

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx, :]
        X_valid_fold = X.iloc[valid_idx, :]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        model = XGBClassifier(
            objective='multi:softprob',
            num_class=len(np.unique(y)),
            random_state=42,
            n_jobs=1,
            n_estimators=trial.suggest_int('n_estimators', 50, 500),
            learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
            max_depth=trial.suggest_int('max_depth', 2, 8),
            min_child_weight=trial.suggest_int('min_child_weight', 1, 20),
            gamma=trial.suggest_float('gamma', 0, 10),
            subsample=trial.suggest_float('subsample', 0.6, 1.0),
            colsample_bytree=trial.suggest_float('colsample_bytree', 0.6, 1.0),
            reg_alpha=trial.suggest_float('reg_alpha', 1e-5, 10, log=True),
            reg_lambda=trial.suggest_float('reg_lambda', 1e-5, 10, log=True),
            eval_metric='mlogloss'
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)

        w0 = trial.suggest_float('weight_class_0', 0.1, 2.0)
        w1 = trial.suggest_float('weight_class_1', 0.1, 2.0)
        w2 = trial.suggest_float('weight_class_2', 0.1, 2.0)

        weighted_probas = proba * np.array([w0, w1, w2])

        pred = np.argmax(weighted_probas, axis=1)

        score = balanced_accuracy_score(y_valid_fold, pred)

        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=60, n_jobs=-1, show_progress_bar=True)

print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-18 11:08:30,287] A new study created in memory with name: no-name-5a0dd625-0a1f-41a3-8870-78863b9f5b88
Best trial: 5. Best value: 0.960732:   2%|██▎                                                                                                                                     | 1/60 [03:10<3:07:04, 190.25s/it]

[I 2026-06-18 11:11:40,524] Trial 5 finished with value: 0.9607315870670836 and parameters: {'n_estimators': 224, 'learning_rate': 0.22521094116193066, 'max_depth': 8, 'min_child_weight': 7, 'gamma': 2.24831537039333, 'subsample': 0.7134768081733256, 'colsample_bytree': 0.6990877331228785, 'reg_alpha': 0.0028507607164606026, 'reg_lambda': 2.7733432614101884e-05, 'weight_class_0': 0.8409983621843435, 'weight_class_1': 0.5231612023943638, 'weight_class_2': 1.808966311077602}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:   3%|████▌                                                                                                                                    | 2/60 [03:10<1:15:52, 78.49s/it]

[I 2026-06-18 11:11:40,779] Trial 1 finished with value: 0.9421088763253993 and parameters: {'n_estimators': 177, 'learning_rate': 0.05877561790082838, 'max_depth': 4, 'min_child_weight': 13, 'gamma': 5.973589618905523, 'subsample': 0.7501305941654245, 'colsample_bytree': 0.9349688350459817, 'reg_alpha': 0.0006511864552189196, 'reg_lambda': 3.709764390617972, 'weight_class_0': 1.6536056885915276, 'weight_class_1': 0.8279337472043805, 'weight_class_2': 0.5875819148653673}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:   5%|██████▉                                                                                                                                    | 3/60 [03:43<54:52, 57.76s/it]

[I 2026-06-18 11:12:13,884] Trial 7 finished with value: 0.9563498949763712 and parameters: {'n_estimators': 220, 'learning_rate': 0.06209056178909081, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 2.9601983884506335, 'subsample': 0.6217908749501272, 'colsample_bytree': 0.719288358927118, 'reg_alpha': 0.003570217315804315, 'reg_lambda': 0.020178649503954035, 'weight_class_0': 0.7980072441957282, 'weight_class_1': 1.46988816679132, 'weight_class_2': 0.6542495128438257}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:   7%|█████████▎                                                                                                                                 | 4/60 [03:54<36:40, 39.30s/it]

[I 2026-06-18 11:12:24,878] Trial 2 finished with value: 0.9545633801533219 and parameters: {'n_estimators': 357, 'learning_rate': 0.12879271890663058, 'max_depth': 3, 'min_child_weight': 9, 'gamma': 7.254746711484273, 'subsample': 0.8533890055188706, 'colsample_bytree': 0.6528609891338794, 'reg_alpha': 0.02365095401205202, 'reg_lambda': 0.001610262845211245, 'weight_class_0': 0.1265443885210929, 'weight_class_1': 1.8056750361901004, 'weight_class_2': 0.21446538755482233}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:   8%|███████████▌                                                                                                                               | 5/60 [04:40<38:12, 41.69s/it]

[I 2026-06-18 11:13:10,806] Trial 8 finished with value: 0.9560990879266154 and parameters: {'n_estimators': 262, 'learning_rate': 0.011944197321307356, 'max_depth': 3, 'min_child_weight': 9, 'gamma': 2.110828739941921, 'subsample': 0.8156351243367808, 'colsample_bytree': 0.6410689008608818, 'reg_alpha': 0.9984447714515641, 'reg_lambda': 0.0021178149688014358, 'weight_class_0': 0.4160111918703836, 'weight_class_1': 0.3538677135651349, 'weight_class_2': 0.45499464457654715}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:  10%|█████████████▉                                                                                                                             | 6/60 [04:41<25:04, 27.86s/it]

[I 2026-06-18 11:13:11,796] Trial 4 pruned.

Best trial: 5. Best value: 0.960732:  12%|████████████████▏                                                                                                                          | 7/60 [04:52<19:45, 22.36s/it]

[I 2026-06-18 11:13:22,869] Trial 11 pruned.

Best trial: 5. Best value: 0.960732:  13%|██████████████████▌                                                                                                                        | 8/60 [04:56<14:09, 16.35s/it]

[I 2026-06-18 11:13:26,320] Trial 3 pruned.

Best trial: 5. Best value: 0.960732:  15%|████████████████████▊                                                                                                                      | 9/60 [04:59<10:26, 12.28s/it]

[I 2026-06-18 11:13:29,641] Trial 0 pruned.

Best trial: 5. Best value: 0.960732:  17%|███████████████████████                                                                                                                   | 10/60 [05:16<11:21, 13.63s/it]

[I 2026-06-18 11:13:46,309] Trial 6 pruned.

Best trial: 5. Best value: 0.960732:  18%|█████████████████████████▎                                                                                                                | 11/60 [05:33<12:12, 14.95s/it]

[I 2026-06-18 11:14:04,232] Trial 16 pruned.

Best trial: 5. Best value: 0.960732:  20%|███████████████████████████▌                                                                                                              | 12/60 [05:35<08:48, 11.01s/it]

[I 2026-06-18 11:14:06,251] Trial 9 finished with value: 0.9578190358686804 and parameters: {'n_estimators': 452, 'learning_rate': 0.06572115062517947, 'max_depth': 3, 'min_child_weight': 2, 'gamma': 3.1278745524757645, 'subsample': 0.825244090450628, 'colsample_bytree': 0.6070634406111267, 'reg_alpha': 0.25638616192385766, 'reg_lambda': 7.987947463791985, 'weight_class_0': 1.6972080126923588, 'weight_class_1': 1.9519987280587758, 'weight_class_2': 1.7986992778605881}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:  22%|█████████████████████████████▉                                                                                                            | 13/60 [05:59<11:40, 14.90s/it]

[I 2026-06-18 11:14:30,111] Trial 13 pruned.

Best trial: 5. Best value: 0.960732:  23%|████████████████████████████████▏                                                                                                         | 14/60 [06:26<14:11, 18.50s/it]

[I 2026-06-18 11:14:56,927] Trial 23 pruned.

Best trial: 5. Best value: 0.960732:  25%|██████████████████████████████████▌                                                                                                       | 15/60 [06:34<11:25, 15.24s/it]

[I 2026-06-18 11:15:04,628] Trial 15 pruned.

Best trial: 5. Best value: 0.960732:  27%|████████████████████████████████████▊                                                                                                     | 16/60 [07:26<19:15, 26.26s/it]

[I 2026-06-18 11:15:56,481] Trial 24 finished with value: 0.9581376850155646 and parameters: {'n_estimators': 76, 'learning_rate': 0.1482611112176703, 'max_depth': 6, 'min_child_weight': 5, 'gamma': 9.72468915536382, 'subsample': 0.7386395115125712, 'colsample_bytree': 0.7883128332977525, 'reg_alpha': 9.248783207575325, 'reg_lambda': 3.016304787998788e-05, 'weight_class_0': 1.3048974147206787, 'weight_class_1': 1.094479498977107, 'weight_class_2': 1.5132351252316396}. Best is trial 5 with value: 0.9607315870670836.

Best trial: 5. Best value: 0.960732:  28%|███████████████████████████████████████                                                                                                   | 17/60 [07:26<13:13, 18.45s/it]

[I 2026-06-18 11:15:56,748] Trial 20 pruned.

Best trial: 21. Best value: 0.963571:  30%|█████████████████████████████████████████                                                                                                | 18/60 [07:48<13:42, 19.59s/it]

[I 2026-06-18 11:16:19,007] Trial 21 finished with value: 0.9635712815403018 and parameters: {'n_estimators': 117, 'learning_rate': 0.031037852657060685, 'max_depth': 5, 'min_child_weight': 20, 'gamma': 9.835168295379027, 'subsample': 0.992883453873308, 'colsample_bytree': 0.8458506582906595, 'reg_alpha': 1.1108817552578903e-05, 'reg_lambda': 1.2246166458332548e-05, 'weight_class_0': 0.6464560024114381, 'weight_class_1': 1.1664856577589386, 'weight_class_2': 1.2059858191009862}. Best is trial 21 with value: 0.9635712815403018.

Best trial: 21. Best value: 0.963571:  32%|███████████████████████████████████████████▍                                                                                             | 19/60 [07:57<11:14, 16.44s/it]

[I 2026-06-18 11:16:28,122] Trial 19 pruned.

Best trial: 21. Best value: 0.963571:  33%|█████████████████████████████████████████████▋                                                                                           | 20/60 [08:11<10:21, 15.54s/it]

[I 2026-06-18 11:16:41,559] Trial 17 finished with value: 0.9600556500152114 and parameters: {'n_estimators': 174, 'learning_rate': 0.04855439675839896, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 5.33748593793883, 'subsample': 0.6843321515252487, 'colsample_bytree': 0.607793970869308, 'reg_alpha': 0.48646425167802887, 'reg_lambda': 0.000853550405080404, 'weight_class_0': 1.2554984050761, 'weight_class_1': 1.1330092522000008, 'weight_class_2': 1.679157107556944}. Best is trial 21 with value: 0.9635712815403018.

Best trial: 21. Best value: 0.963571:  35%|███████████████████████████████████████████████▉                                                                                         | 21/60 [08:53<15:18, 23.56s/it]

[I 2026-06-18 11:17:23,802] Trial 27 pruned.

Best trial: 21. Best value: 0.963571:  37%|██████████████████████████████████████████████████▏                                                                                      | 22/60 [09:22<15:56, 25.18s/it]

[I 2026-06-18 11:17:52,772] Trial 10 finished with value: 0.962720218229314 and parameters: {'n_estimators': 442, 'learning_rate': 0.03246758813351942, 'max_depth': 4, 'min_child_weight': 7, 'gamma': 0.07934000435136479, 'subsample': 0.7907021577020592, 'colsample_bytree': 0.8393775269128461, 'reg_alpha': 3.929285658812069, 'reg_lambda': 3.2850399574848983, 'weight_class_0': 0.8905607533045724, 'weight_class_1': 1.0889123131000702, 'weight_class_2': 1.6671264841442874}. Best is trial 21 with value: 0.9635712815403018.

Best trial: 21. Best value: 0.963571:  38%|████████████████████████████████████████████████████▌                                                                                    | 23/60 [09:36<13:31, 21.92s/it]

[I 2026-06-18 11:18:07,087] Trial 28 pruned.

Best trial: 21. Best value: 0.963571:  40%|██████████████████████████████████████████████████████▊                                                                                  | 24/60 [09:55<12:38, 21.06s/it]

[I 2026-06-18 11:18:26,148] Trial 18 pruned.

Best trial: 14. Best value: 0.963624:  42%|█████████████████████████████████████████████████████████                                                                                | 25/60 [10:15<12:07, 20.77s/it]

[I 2026-06-18 11:18:46,250] Trial 14 finished with value: 0.9636238813288213 and parameters: {'n_estimators': 323, 'learning_rate': 0.013045052678483956, 'max_depth': 7, 'min_child_weight': 2, 'gamma': 8.74095782844726, 'subsample': 0.787400452358784, 'colsample_bytree': 0.9284209622182149, 'reg_alpha': 0.7171944615144573, 'reg_lambda': 2.5546942881595082e-05, 'weight_class_0': 0.9900087825417412, 'weight_class_1': 1.7601092193078163, 'weight_class_2': 1.9551341226564956}. Best is trial 14 with value: 0.9636238813288213.

Best trial: 26. Best value: 0.966183:  43%|███████████████████████████████████████████████████████████▎                                                                             | 26/60 [10:21<09:06, 16.06s/it]

[I 2026-06-18 11:18:51,327] Trial 26 finished with value: 0.9661834921144722 and parameters: {'n_estimators': 136, 'learning_rate': 0.12753890298492707, 'max_depth': 6, 'min_child_weight': 4, 'gamma': 0.0939304006273054, 'subsample': 0.7034864012968873, 'colsample_bytree': 0.8159478603976016, 'reg_alpha': 7.680270202717012, 'reg_lambda': 7.425164231402944, 'weight_class_0': 0.421809593555486, 'weight_class_1': 1.0814117552830795, 'weight_class_2': 1.5893226791894162}. Best is trial 26 with value: 0.9661834921144722.

Best trial: 26. Best value: 0.966183:  45%|█████████████████████████████████████████████████████████████▋                                                                           | 27/60 [11:23<16:26, 29.89s/it]

[I 2026-06-18 11:19:53,490] Trial 30 finished with value: 0.9650864189899668 and parameters: {'n_estimators': 121, 'learning_rate': 0.022800068435980064, 'max_depth': 6, 'min_child_weight': 18, 'gamma': 0.7624374946024717, 'subsample': 0.9977975195140297, 'colsample_bytree': 0.8207026832429886, 'reg_alpha': 6.229392542823529e-05, 'reg_lambda': 1.0133731444422564e-05, 'weight_class_0': 0.4229479393599155, 'weight_class_1': 0.9970690118780298, 'weight_class_2': 1.123673768919677}. Best is trial 26 with value: 0.9661834921144722.

Best trial: 26. Best value: 0.966183:  47%|███████████████████████████████████████████████████████████████▉                                                                         | 28/60 [11:36<13:21, 25.05s/it]

[I 2026-06-18 11:20:07,241] Trial 32 finished with value: 0.9646447910646522 and parameters: {'n_estimators': 123, 'learning_rate': 0.02644351175386661, 'max_depth': 8, 'min_child_weight': 17, 'gamma': 5.587756163029362, 'subsample': 0.9779959588980424, 'colsample_bytree': 0.8768406266624915, 'reg_alpha': 5.084644681080544e-05, 'reg_lambda': 8.587980319651597e-05, 'weight_class_0': 0.500056853595845, 'weight_class_1': 0.9400297101203685, 'weight_class_2': 1.2034334565874452}. Best is trial 26 with value: 0.9661834921144722.

Best trial: 26. Best value: 0.966183:  48%|██████████████████████████████████████████████████████████████████▏                                                                      | 29/60 [11:39<09:23, 18.19s/it]

[I 2026-06-18 11:20:09,413] Trial 29 finished with value: 0.9653933317705258 and parameters: {'n_estimators': 132, 'learning_rate': 0.023711534276936622, 'max_depth': 6, 'min_child_weight': 18, 'gamma': 0.6346838260056966, 'subsample': 0.9274225090999606, 'colsample_bytree': 0.8355275597813981, 'reg_alpha': 7.413694053048713e-05, 'reg_lambda': 1.1352940558341027e-05, 'weight_class_0': 0.43466253549798806, 'weight_class_1': 1.0065071270731152, 'weight_class_2': 1.2361949556564666}. Best is trial 26 with value: 0.9661834921144722.
[I 2026-06-18 11:20:09,611] Trial 31 finished with value: 0.9655807529183023 and parameters: {'n_estimators': 121, 'learning_rate': 0.024843679256819688, 'max_depth': 6, 'min_child_weight': 17, 'gamma': 0.7550967465491407, 'subsample': 0.9961212124812824, 'colsample_bytree': 0.8376322224936824, 'reg_alpha': 6.32364860263754e-05, 'reg_lambda': 6.792907236024378e-05, 'weight_class_0': 0.41365852038178985, 'weight_class_1': 0.9092581747615893, 'weight_class_2': 1.2509647376778985}. Best is trial 26 with value: 0.9661834921144722.

Best trial: 26. Best value: 0.966183:  52%|██████████████████████████████████████████████████████████████████████▊                                                                  | 31/60 [11:45<05:15, 10.88s/it]

[I 2026-06-18 11:20:16,046] Trial 35 pruned.

Best trial: 26. Best value: 0.966183:  53%|█████████████████████████████████████████████████████████████████████████                                                                | 32/60 [11:54<04:50, 10.37s/it]

[I 2026-06-18 11:20:25,230] Trial 33 pruned.

Best trial: 26. Best value: 0.966183:  55%|███████████████████████████████████████████████████████████████████████████▎                                                             | 33/60 [12:11<05:28, 12.17s/it]

[I 2026-06-18 11:20:41,594] Trial 22 finished with value: 0.9618688623456004 and parameters: {'n_estimators': 257, 'learning_rate': 0.04722440682050628, 'max_depth': 5, 'min_child_weight': 6, 'gamma': 0.41256710332382385, 'subsample': 0.7056080782915605, 'colsample_bytree': 0.7617310171037774, 'reg_alpha': 1.8381705300756e-05, 'reg_lambda': 2.9437691734082872e-05, 'weight_class_0': 0.8371547037659356, 'weight_class_1': 1.4151272341571046, 'weight_class_2': 1.1833830634979394}. Best is trial 26 with value: 0.9661834921144722.

Best trial: 12. Best value: 0.966228:  57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 34/60 [13:04<10:37, 24.52s/it]

[I 2026-06-18 11:21:34,925] Trial 12 finished with value: 0.9662284804590525 and parameters: {'n_estimators': 321, 'learning_rate': 0.08344604063700627, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 0.8520872892194686, 'subsample': 0.6788161418996086, 'colsample_bytree': 0.6549991297932997, 'reg_alpha': 4.173706232556804e-05, 'reg_lambda': 2.5343770478971637, 'weight_class_0': 0.39592052168945513, 'weight_class_1': 1.1294172727413168, 'weight_class_2': 1.5779511307549516}. Best is trial 12 with value: 0.9662284804590525.

Best trial: 12. Best value: 0.966228:  58%|███████████████████████████████████████████████████████████████████████████████▉                                                         | 35/60 [13:05<07:15, 17.44s/it]

[I 2026-06-18 11:21:35,848] Trial 37 finished with value: 0.9632572530142127 and parameters: {'n_estimators': 125, 'learning_rate': 0.020009214531722545, 'max_depth': 5, 'min_child_weight': 17, 'gamma': 7.853427634419171, 'subsample': 0.9180732505356326, 'colsample_bytree': 0.9048635068838866, 'reg_alpha': 7.182010046690994e-05, 'reg_lambda': 7.842841987415044e-05, 'weight_class_0': 0.5337559553871065, 'weight_class_1': 1.6439266041160994, 'weight_class_2': 1.0862280884959556}. Best is trial 12 with value: 0.9662284804590525.

Best trial: 12. Best value: 0.966228:  60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 36/60 [13:14<05:53, 14.74s/it]

[I 2026-06-18 11:21:44,289] Trial 41 finished with value: 0.9655364536580663 and parameters: {'n_estimators': 52, 'learning_rate': 0.08733707569827777, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 1.1067487161663978, 'subsample': 0.9201050384648549, 'colsample_bytree': 0.8973585725771791, 'reg_alpha': 0.00017850353162064662, 'reg_lambda': 0.009619921314722843, 'weight_class_0': 0.12819583237700194, 'weight_class_1': 0.8102908270702875, 'weight_class_2': 1.0114537239161945}. Best is trial 12 with value: 0.9662284804590525.

Best trial: 12. Best value: 0.966228:  62%|████████████████████████████████████████████████████████████████████████████████████▍                                                    | 37/60 [13:20<04:44, 12.36s/it]

[I 2026-06-18 11:21:51,086] Trial 25 pruned.

Best trial: 12. Best value: 0.966228:  63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 38/60 [14:30<10:48, 29.49s/it]

[I 2026-06-18 11:23:00,534] Trial 34 pruned.

Best trial: 12. Best value: 0.966228:  65%|█████████████████████████████████████████████████████████████████████████████████████████                                                | 39/60 [14:57<10:04, 28.77s/it]

[I 2026-06-18 11:23:27,637] Trial 47 finished with value: 0.9656527743662393 and parameters: {'n_estimators': 54, 'learning_rate': 0.08220093622147868, 'max_depth': 7, 'min_child_weight': 12, 'gamma': 1.5155554939556417, 'subsample': 0.8966478258159435, 'colsample_bytree': 0.9536830541715949, 'reg_alpha': 0.0005579139573943104, 'reg_lambda': 0.0077298297089073405, 'weight_class_0': 0.12240970186970862, 'weight_class_1': 0.7882337727677374, 'weight_class_2': 0.9204956534947698}. Best is trial 12 with value: 0.9662284804590525.

Best trial: 12. Best value: 0.966228:  67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 40/60 [14:59<06:54, 20.74s/it]

[I 2026-06-18 11:23:29,629] Trial 36 pruned.

Best trial: 12. Best value: 0.966228:  68%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 41/60 [15:19<06:31, 20.62s/it]

[I 2026-06-18 11:23:49,993] Trial 38 finished with value: 0.9647707479037484 and parameters: {'n_estimators': 147, 'learning_rate': 0.017082981121677172, 'max_depth': 5, 'min_child_weight': 17, 'gamma': 0.915777201611513, 'subsample': 0.899298219162448, 'colsample_bytree': 0.8746276591808615, 'reg_alpha': 0.01410555692791841, 'reg_lambda': 9.198508448316881e-05, 'weight_class_0': 0.4453915253778899, 'weight_class_1': 1.6020495918106064, 'weight_class_2': 1.1558806663055332}. Best is trial 12 with value: 0.9662284804590525.

Best trial: 42. Best value: 0.966426:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 42/60 [15:33<05:33, 18.51s/it]

[I 2026-06-18 11:24:03,588] Trial 42 finished with value: 0.9664257783027257 and parameters: {'n_estimators': 150, 'learning_rate': 0.018281363104812196, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 1.2193635390634783, 'subsample': 0.9341096878043558, 'colsample_bytree': 0.8862931718794089, 'reg_alpha': 0.00017476068007125998, 'reg_lambda': 7.207022435716313e-05, 'weight_class_0': 0.24288695521117556, 'weight_class_1': 0.8191214133200619, 'weight_class_2': 1.0241755953697351}. Best is trial 42 with value: 0.9664257783027257.

Best trial: 42. Best value: 0.966426:  72%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 43/60 [15:34<03:46, 13.31s/it]

[I 2026-06-18 11:24:04,744] Trial 39 finished with value: 0.9647962975235537 and parameters: {'n_estimators': 150, 'learning_rate': 0.020712963206120052, 'max_depth': 5, 'min_child_weight': 17, 'gamma': 1.1029342815245815, 'subsample': 0.9252611071011259, 'colsample_bytree': 0.886208118892702, 'reg_alpha': 8.967057945939095e-05, 'reg_lambda': 0.000113318034668461, 'weight_class_0': 0.4709942235702025, 'weight_class_1': 0.8751054241579439, 'weight_class_2': 1.1745626821520614}. Best is trial 42 with value: 0.9664257783027257.

Best trial: 42. Best value: 0.966426:  73%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 44/60 [15:38<02:50, 10.63s/it]

[I 2026-06-18 11:24:09,104] Trial 40 finished with value: 0.9663387026043806 and parameters: {'n_estimators': 154, 'learning_rate': 0.01885879708877121, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 1.2451482156062306, 'subsample': 0.933266381578238, 'colsample_bytree': 0.8959002158903664, 'reg_alpha': 0.00015981095575640208, 'reg_lambda': 0.008781321252965641, 'weight_class_0': 0.16635621775411716, 'weight_class_1': 0.8718464482967773, 'weight_class_2': 1.041159272198986}. Best is trial 42 with value: 0.9664257783027257.

Best trial: 42. Best value: 0.966426:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 45/60 [15:46<02:28,  9.87s/it]

[I 2026-06-18 11:24:17,218] Trial 48 finished with value: 0.9653404208983163 and parameters: {'n_estimators': 85, 'learning_rate': 0.08917539877046872, 'max_depth': 7, 'min_child_weight': 12, 'gamma': 1.4737529594627228, 'subsample': 0.89146573999747, 'colsample_bytree': 0.9726581767450724, 'reg_alpha': 0.000434890979522976, 'reg_lambda': 1.221263013964195, 'weight_class_0': 0.12075622060396957, 'weight_class_1': 0.8006764048822004, 'weight_class_2': 0.9210399183610896}. Best is trial 42 with value: 0.9664257783027257.

Best trial: 42. Best value: 0.966426:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 46/60 [16:04<02:49, 12.12s/it]

[I 2026-06-18 11:24:34,598] Trial 49 finished with value: 0.9645338054498506 and parameters: {'n_estimators': 53, 'learning_rate': 0.08174032366329316, 'max_depth': 7, 'min_child_weight': 11, 'gamma': 1.6698924551554457, 'subsample': 0.8870469270018474, 'colsample_bytree': 0.995312292299631, 'reg_alpha': 0.00039207666138108986, 'reg_lambda': 1.5361645842955118, 'weight_class_0': 0.1282273260530329, 'weight_class_1': 1.2646367052766376, 'weight_class_2': 0.9114339347869613}. Best is trial 42 with value: 0.9664257783027257.

Best trial: 43. Best value: 0.966455:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 47/60 [16:13<02:25, 11.16s/it]

[I 2026-06-18 11:24:43,523] Trial 43 finished with value: 0.9664552616525155 and parameters: {'n_estimators': 158, 'learning_rate': 0.01984170688781394, 'max_depth': 6, 'min_child_weight': 16, 'gamma': 1.3382056143627181, 'subsample': 0.932750143000414, 'colsample_bytree': 0.7865877091043509, 'reg_alpha': 0.00024307656295547938, 'reg_lambda': 0.01538631782677991, 'weight_class_0': 0.19020754781253635, 'weight_class_1': 0.8360460311543438, 'weight_class_2': 0.9956026282725565}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 48/60 [16:34<02:51, 14.31s/it]

[I 2026-06-18 11:25:05,192] Trial 45 pruned.

Best trial: 43. Best value: 0.966455:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 49/60 [16:41<02:12, 12.03s/it]

[I 2026-06-18 11:25:11,884] Trial 44 finished with value: 0.9660163192366318 and parameters: {'n_estimators': 155, 'learning_rate': 0.02004749794117388, 'max_depth': 6, 'min_child_weight': 16, 'gamma': 1.299713441427189, 'subsample': 0.9360102056709054, 'colsample_bytree': 0.9029491880787863, 'reg_alpha': 0.00025170012821946184, 'reg_lambda': 0.018264948676183515, 'weight_class_0': 0.1384061199704183, 'weight_class_1': 0.7866997070933109, 'weight_class_2': 1.0153752842805361}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 50/60 [16:46<01:38,  9.88s/it]

[I 2026-06-18 11:25:16,741] Trial 46 finished with value: 0.9655486048297304 and parameters: {'n_estimators': 156, 'learning_rate': 0.08298465732798099, 'max_depth': 7, 'min_child_weight': 12, 'gamma': 1.4245319163653343, 'subsample': 0.9424987581385025, 'colsample_bytree': 0.6847203502713365, 'reg_alpha': 0.0005784468109216184, 'reg_lambda': 1.2555578057294359, 'weight_class_0': 0.18539657703066859, 'weight_class_1': 0.8009404857862247, 'weight_class_2': 1.4817482845552663}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 51/60 [16:53<01:21,  9.09s/it]

[I 2026-06-18 11:25:23,990] Trial 50 pruned.

Best trial: 43. Best value: 0.966455:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 52/60 [17:04<01:17,  9.74s/it]

[I 2026-06-18 11:25:35,253] Trial 52 finished with value: 0.9651243165926999 and parameters: {'n_estimators': 63, 'learning_rate': 0.08693053188441582, 'max_depth': 7, 'min_child_weight': 12, 'gamma': 1.5916318224470531, 'subsample': 0.953731493605151, 'colsample_bytree': 0.9838191555978533, 'reg_alpha': 0.00047118750950807096, 'reg_lambda': 1.233730777702495, 'weight_class_0': 0.10987727398622235, 'weight_class_1': 0.7805650968697789, 'weight_class_2': 0.905907887625628}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 53/60 [17:27<01:35, 13.71s/it]

[I 2026-06-18 11:25:58,216] Trial 57 pruned.

Best trial: 43. Best value: 0.966455:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 54/60 [17:40<01:19, 13.28s/it]

[I 2026-06-18 11:26:10,514] Trial 54 finished with value: 0.966204535894903 and parameters: {'n_estimators': 89, 'learning_rate': 0.08180847543448168, 'max_depth': 7, 'min_child_weight': 12, 'gamma': 1.6000501339177025, 'subsample': 0.953747237439099, 'colsample_bytree': 0.9458315918308546, 'reg_alpha': 0.0007421932790409379, 'reg_lambda': 1.4701957439642732, 'weight_class_0': 0.23887023854198294, 'weight_class_1': 0.7718841620767265, 'weight_class_2': 0.8304230924546226}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 55/60 [18:03<01:21, 16.30s/it]

[I 2026-06-18 11:26:33,838] Trial 51 finished with value: 0.9660100330451729 and parameters: {'n_estimators': 155, 'learning_rate': 0.08380556582472717, 'max_depth': 7, 'min_child_weight': 11, 'gamma': 1.4244693419266483, 'subsample': 0.8850183391004465, 'colsample_bytree': 0.9636279312191841, 'reg_alpha': 0.0003474182620280661, 'reg_lambda': 1.4715701513341053, 'weight_class_0': 0.24747634686885486, 'weight_class_1': 0.8497970190003671, 'weight_class_2': 0.8159518193919986}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 56/60 [18:11<00:55, 13.83s/it]

[I 2026-06-18 11:26:41,924] Trial 59 pruned.

Best trial: 43. Best value: 0.966455:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 57/60 [18:18<00:35, 11.80s/it]

[I 2026-06-18 11:26:48,979] Trial 53 finished with value: 0.9662155942702517 and parameters: {'n_estimators': 199, 'learning_rate': 0.08296372958297553, 'max_depth': 7, 'min_child_weight': 11, 'gamma': 1.7221715440058127, 'subsample': 0.9467601557368631, 'colsample_bytree': 0.9860808795521361, 'reg_alpha': 0.000619352171257957, 'reg_lambda': 1.7142291489584307, 'weight_class_0': 0.24967776462748728, 'weight_class_1': 0.758683276824726, 'weight_class_2': 0.8581210074656807}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 58/60 [18:20<00:17,  8.69s/it]

[I 2026-06-18 11:26:50,413] Trial 56 finished with value: 0.9659712299623262 and parameters: {'n_estimators': 208, 'learning_rate': 0.08136104775012606, 'max_depth': 8, 'min_child_weight': 15, 'gamma': 2.5630252305740404, 'subsample': 0.9537146361391414, 'colsample_bytree': 0.9976356705136931, 'reg_alpha': 0.0007975797053193805, 'reg_lambda': 1.2933546735460966, 'weight_class_0': 0.24075207391881165, 'weight_class_1': 0.4414136438892312, 'weight_class_2': 0.8333749787669058}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 59/60 [18:23<00:07,  7.09s/it]

[I 2026-06-18 11:26:53,784] Trial 55 finished with value: 0.9660709781009856 and parameters: {'n_estimators': 201, 'learning_rate': 0.07849806913528629, 'max_depth': 7, 'min_child_weight': 11, 'gamma': 1.6769777010022135, 'subsample': 0.8917550056442071, 'colsample_bytree': 0.9833762509685984, 'reg_alpha': 0.0006117260861332508, 'reg_lambda': 1.7983937678611819, 'weight_class_0': 0.25573122941141085, 'weight_class_1': 0.749484224565127, 'weight_class_2': 0.8561175719159196}. Best is trial 43 with value: 0.9664552616525155.

Best trial: 43. Best value: 0.966455: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [18:30<00:00, 18.51s/it]

[I 2026-06-18 11:27:00,677] Trial 58 finished with value: 0.9651587235262434 and parameters: {'n_estimators': 198, 'learning_rate': 0.01010421961774935, 'max_depth': 4, 'min_child_weight': 15, 'gamma': 2.6272740636438927, 'subsample': 0.9534464955231017, 'colsample_bytree': 0.6751163998580703, 'reg_alpha': 0.0009033520505399793, 'reg_lambda': 0.037293837479703225, 'weight_class_0': 0.26702682713470505, 'weight_class_1': 0.6961526937105991, 'weight_class_2': 0.77239030195707}. Best is trial 43 with value: 0.9664552616525155.
Best trial score:
0.9664552616525155

Best params:
{'n_estimators': 158, 'learning_rate': 0.01984170688781394, 'max_depth': 6, 'min_child_weight': 16, 'gamma': 1.3382056143627181, 'subsample': 0.932750143000414, 'colsample_bytree': 0.7865877091043509, 'reg_alpha': 0.00024307656295547938, 'reg_lambda': 0.01538631782677991, 'weight_class_0': 0.19020754781253635, 'weight_class_1': 0.8360460311543438, 'weight_class_2': 0.9956026282725565}

In [19]:
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=60, n_jobs=-1, show_progress_bar=True)

Best trial: 105. Best value: 0.966562:   2%|██▎                                                                                                                                    | 1/60 [01:27<1:25:59, 87.46s/it]

[I 2026-06-18 14:29:17,339] Trial 125 finished with value: 0.9652497460235324 and parameters: {'n_estimators': 88, 'learning_rate': 0.010583183806081309, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.922689857485631, 'subsample': 0.7124992373435034, 'colsample_bytree': 0.6934580469618686, 'reg_alpha': 0.2710136085428937, 'reg_lambda': 0.002196057815042488, 'weight_class_0': 0.2957567632084959, 'weight_class_1': 1.7117684980760144, 'weight_class_2': 1.7797466488756442}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:   3%|████▌                                                                                                                                    | 2/60 [01:41<43:01, 44.51s/it]

[I 2026-06-18 14:29:31,786] Trial 124 pruned.

Best trial: 105. Best value: 0.966562:   5%|██████▊                                                                                                                                  | 3/60 [01:59<30:41, 32.30s/it]

[I 2026-06-18 14:29:49,575] Trial 131 finished with value: 0.9657771329492728 and parameters: {'n_estimators': 127, 'learning_rate': 0.01563644061103149, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.349729187756678, 'subsample': 0.7253984930248707, 'colsample_bytree': 0.6959852701730406, 'reg_alpha': 0.01425515564937575, 'reg_lambda': 0.00303969730254427, 'weight_class_0': 0.5489519760702428, 'weight_class_1': 1.7304830788837513, 'weight_class_2': 1.7780422959922162}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:   7%|█████████▏                                                                                                                               | 4/60 [02:22<26:43, 28.64s/it]

[I 2026-06-18 14:30:12,594] Trial 126 finished with value: 0.9661309428791656 and parameters: {'n_estimators': 178, 'learning_rate': 0.09493331526225796, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 5.860678550429866, 'subsample': 0.7373972566601962, 'colsample_bytree': 0.6665652698541836, 'reg_alpha': 0.010848012035937223, 'reg_lambda': 0.0023236625894424187, 'weight_class_0': 0.29557114414528707, 'weight_class_1': 1.7164904550101716, 'weight_class_2': 1.693285120895725}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:   8%|███████████▍                                                                                                                             | 5/60 [02:29<19:02, 20.77s/it]

[I 2026-06-18 14:30:19,403] Trial 120 finished with value: 0.9656838467733598 and parameters: {'n_estimators': 165, 'learning_rate': 0.010842966506572271, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.251770913662542, 'subsample': 0.7300200566156706, 'colsample_bytree': 0.6975367780619522, 'reg_alpha': 0.32094494847171096, 'reg_lambda': 0.002457215059975046, 'weight_class_0': 0.5593525922891776, 'weight_class_1': 1.7125526503210597, 'weight_class_2': 1.7798980276804892}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  10%|█████████████▋                                                                                                                           | 6/60 [02:44<16:58, 18.87s/it]

[I 2026-06-18 14:30:34,595] Trial 129 finished with value: 0.9658623480445468 and parameters: {'n_estimators': 182, 'learning_rate': 0.010582469176857255, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 7.231436662908018, 'subsample': 0.6944175396971729, 'colsample_bytree': 0.7160140738921423, 'reg_alpha': 0.012291002698255896, 'reg_lambda': 0.0031249193582640455, 'weight_class_0': 0.30053237563609964, 'weight_class_1': 1.6851105051538244, 'weight_class_2': 1.8857315553529446}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  12%|███████████████▉                                                                                                                         | 7/60 [02:45<11:32, 13.06s/it]

[I 2026-06-18 14:30:35,693] Trial 128 finished with value: 0.9657360461960804 and parameters: {'n_estimators': 183, 'learning_rate': 0.010258369953984254, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.361265606427597, 'subsample': 0.719599825782021, 'colsample_bytree': 0.6671956605833659, 'reg_alpha': 0.27959933277854837, 'reg_lambda': 0.0033721885204646518, 'weight_class_0': 0.5513159793248061, 'weight_class_1': 1.853522543742407, 'weight_class_2': 1.7965071781225863}. Best is trial 105 with value: 0.9665620964645611.
[I 2026-06-18 14:30:35,742] Trial 127 finished with value: 0.9657591249860029 and parameters: {'n_estimators': 184, 'learning_rate': 0.010348481326147423, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.793805833281966, 'subsample': 0.7194861785754382, 'colsample_bytree': 0.7142673558257038, 'reg_alpha': 0.010283229495446035, 'reg_lambda': 0.0023089628197968887, 'weight_class_0': 0.5513064316974786, 'weight_class_1': 1.7215686467638887, 'weight_class_2': 1.7894817300425825}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  15%|████████████████████▌                                                                                                                    | 9/60 [02:47<06:01,  7.10s/it]

[I 2026-06-18 14:30:37,104] Trial 122 finished with value: 0.9663054219434525 and parameters: {'n_estimators': 178, 'learning_rate': 0.028628110682622214, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 7.526488105926445, 'subsample': 0.7152914077719931, 'colsample_bytree': 0.668383308908128, 'reg_alpha': 0.20910852288410467, 'reg_lambda': 0.003163827142020304, 'weight_class_0': 0.5586890745545474, 'weight_class_1': 1.6878098910108146, 'weight_class_2': 1.8891468054284468}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  17%|██████████████████████▋                                                                                                                 | 10/60 [02:50<05:02,  6.04s/it]

[I 2026-06-18 14:30:40,088] Trial 130 finished with value: 0.9658844685236463 and parameters: {'n_estimators': 183, 'learning_rate': 0.015709065662585873, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.64259064148256, 'subsample': 0.7120171271666165, 'colsample_bytree': 0.6716313595409584, 'reg_alpha': 0.009310674180389807, 'reg_lambda': 0.0028521627888788686, 'weight_class_0': 0.29787544506805674, 'weight_class_1': 1.6972521949781938, 'weight_class_2': 1.7898559569311394}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  18%|████████████████████████▉                                                                                                               | 11/60 [02:53<04:19,  5.30s/it]

[I 2026-06-18 14:30:43,368] Trial 121 finished with value: 0.9663278713282611 and parameters: {'n_estimators': 186, 'learning_rate': 0.015737686173371374, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 4.799227794598284, 'subsample': 0.694144188304695, 'colsample_bytree': 0.8264706628539339, 'reg_alpha': 0.010536361682401203, 'reg_lambda': 0.0020334053549382336, 'weight_class_0': 0.5430483699804676, 'weight_class_1': 1.7037418203418935, 'weight_class_2': 1.8873421304581999}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  20%|███████████████████████████▏                                                                                                            | 12/60 [02:54<03:17,  4.12s/it]

[I 2026-06-18 14:30:44,417] Trial 123 finished with value: 0.9656690248415997 and parameters: {'n_estimators': 191, 'learning_rate': 0.010541235592887397, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 6.955331278312539, 'subsample': 0.6128870592724439, 'colsample_bytree': 0.6952823761281489, 'reg_alpha': 0.012191726904418962, 'reg_lambda': 0.0024439916979775993, 'weight_class_0': 0.5582312305047423, 'weight_class_1': 1.2390284990945508, 'weight_class_2': 1.786334897965003}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  22%|█████████████████████████████▍                                                                                                          | 13/60 [03:40<12:37, 16.11s/it]

[I 2026-06-18 14:31:30,826] Trial 133 finished with value: 0.9657379406089124 and parameters: {'n_estimators': 128, 'learning_rate': 0.011677161354629461, 'max_depth': 2, 'min_child_weight': 6, 'gamma': 1.7963315606123933, 'subsample': 0.6738437092734566, 'colsample_bytree': 0.6934996131112896, 'reg_alpha': 0.012643029451217654, 'reg_lambda': 0.00040392041053133516, 'weight_class_0': 0.5627325001183944, 'weight_class_1': 1.6992191563462995, 'weight_class_2': 1.9185189893911014}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  23%|███████████████████████████████▋                                                                                                        | 14/60 [03:54<11:43, 15.29s/it]

[I 2026-06-18 14:31:44,092] Trial 142 finished with value: 0.9664602115032166 and parameters: {'n_estimators': 50, 'learning_rate': 0.014312129533189957, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.792886231356917, 'subsample': 0.7716516516947186, 'colsample_bytree': 0.6432354171881657, 'reg_alpha': 0.04250896204946777, 'reg_lambda': 4.734542702803676e-05, 'weight_class_0': 0.35696861617893927, 'weight_class_1': 1.4467066716812917, 'weight_class_2': 1.944101984717231}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  25%|██████████████████████████████████                                                                                                      | 15/60 [04:02<09:53, 13.19s/it]

[I 2026-06-18 14:31:52,166] Trial 132 finished with value: 0.9658882768686571 and parameters: {'n_estimators': 165, 'learning_rate': 0.011833912124170488, 'max_depth': 2, 'min_child_weight': 2, 'gamma': 4.938814408197496, 'subsample': 0.6953484162878962, 'colsample_bytree': 0.7156963510287618, 'reg_alpha': 0.012946367241321569, 'reg_lambda': 0.003388025747448617, 'weight_class_0': 0.5598196437850853, 'weight_class_1': 1.6813482240903688, 'weight_class_2': 1.8988705405117439}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  27%|████████████████████████████████████▎                                                                                                   | 16/60 [04:29<12:44, 17.39s/it]

[I 2026-06-18 14:32:19,635] Trial 134 finished with value: 0.9663359121622538 and parameters: {'n_estimators': 164, 'learning_rate': 0.011981527134916951, 'max_depth': 2, 'min_child_weight': 7, 'gamma': 1.7063507661531692, 'subsample': 0.6959514197111691, 'colsample_bytree': 0.6639556978728397, 'reg_alpha': 0.04107622567058754, 'reg_lambda': 0.0004668209345925239, 'weight_class_0': 0.453125198889925, 'weight_class_1': 1.2349536102100283, 'weight_class_2': 1.8880149274442175}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  28%|██████████████████████████████████████▌                                                                                                 | 17/60 [04:33<09:33, 13.33s/it]

[I 2026-06-18 14:32:23,312] Trial 137 finished with value: 0.9663792430155344 and parameters: {'n_estimators': 117, 'learning_rate': 0.011935101043323341, 'max_depth': 2, 'min_child_weight': 6, 'gamma': 1.8266102199805387, 'subsample': 0.6322590210458854, 'colsample_bytree': 0.8304639285694895, 'reg_alpha': 0.04401803172678722, 'reg_lambda': 0.0003405190058266085, 'weight_class_0': 0.45170219180459514, 'weight_class_1': 1.3753513909883521, 'weight_class_2': 1.9057912410748705}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  30%|████████████████████████████████████████▊                                                                                               | 18/60 [04:37<07:27, 10.66s/it]

[I 2026-06-18 14:32:27,648] Trial 143 finished with value: 0.9665094606199924 and parameters: {'n_estimators': 91, 'learning_rate': 0.01133689039383537, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 1.7702873385086577, 'subsample': 0.6326780578455136, 'colsample_bytree': 0.6201438578822417, 'reg_alpha': 0.03738597069405348, 'reg_lambda': 0.0004568780690294363, 'weight_class_0': 0.375205966706569, 'weight_class_1': 1.4518650757762521, 'weight_class_2': 1.9195595359838507}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  32%|███████████████████████████████████████████                                                                                             | 19/60 [04:54<08:34, 12.54s/it]

[I 2026-06-18 14:32:44,616] Trial 139 finished with value: 0.966356072973247 and parameters: {'n_estimators': 119, 'learning_rate': 0.01228272610374552, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 1.8262294846976923, 'subsample': 0.6150931566563889, 'colsample_bytree': 0.9091752483082266, 'reg_alpha': 0.036568712088439946, 'reg_lambda': 0.0003593660624045849, 'weight_class_0': 0.4488036058026172, 'weight_class_1': 1.2423487447352144, 'weight_class_2': 1.8879316793924217}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  33%|█████████████████████████████████████████████▎                                                                                          | 20/60 [04:57<06:28,  9.72s/it]

[I 2026-06-18 14:32:47,731] Trial 141 finished with value: 0.9664707408397085 and parameters: {'n_estimators': 116, 'learning_rate': 0.011767751925535372, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.785610134660011, 'subsample': 0.6370216390173665, 'colsample_bytree': 0.6428403167152377, 'reg_alpha': 0.040098607448475106, 'reg_lambda': 4.90024227725006e-05, 'weight_class_0': 0.36286784697362634, 'weight_class_1': 1.2516818946259982, 'weight_class_2': 1.933057396359736}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  35%|███████████████████████████████████████████████▌                                                                                        | 21/60 [04:58<04:33,  7.01s/it]

[I 2026-06-18 14:32:48,376] Trial 140 finished with value: 0.966317051313135 and parameters: {'n_estimators': 118, 'learning_rate': 0.01192804101749226, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 1.8554918199480561, 'subsample': 0.6342231936543514, 'colsample_bytree': 0.8250692911327617, 'reg_alpha': 0.00023724173783577193, 'reg_lambda': 0.00034665882328952874, 'weight_class_0': 0.4513914352873091, 'weight_class_1': 1.2468010783934924, 'weight_class_2': 1.9399627413479328}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  37%|█████████████████████████████████████████████████▊                                                                                      | 22/60 [05:14<06:04,  9.58s/it]

[I 2026-06-18 14:33:03,986] Trial 135 finished with value: 0.9664219346233629 and parameters: {'n_estimators': 189, 'learning_rate': 0.011676705448600621, 'max_depth': 2, 'min_child_weight': 6, 'gamma': 1.8268265097380305, 'subsample': 0.6345203069354248, 'colsample_bytree': 0.6460527221542863, 'reg_alpha': 0.038679389565378176, 'reg_lambda': 0.00035227995466527093, 'weight_class_0': 0.44943735100243637, 'weight_class_1': 1.2384893741610712, 'weight_class_2': 1.8950090388272487}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  38%|████████████████████████████████████████████████████▏                                                                                   | 23/60 [05:16<04:36,  7.49s/it]

[I 2026-06-18 14:33:06,559] Trial 136 finished with value: 0.9665413855854041 and parameters: {'n_estimators': 188, 'learning_rate': 0.012080988990461837, 'max_depth': 2, 'min_child_weight': 6, 'gamma': 8.230877423124847, 'subsample': 0.6926022973979569, 'colsample_bytree': 0.6439806269671347, 'reg_alpha': 0.20765355520525358, 'reg_lambda': 4.825625811114649e-05, 'weight_class_0': 0.36693942145440506, 'weight_class_1': 1.3771969398152688, 'weight_class_2': 1.8639530253549303}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  40%|██████████████████████████████████████████████████████▍                                                                                 | 24/60 [05:34<06:17, 10.48s/it]

[I 2026-06-18 14:33:24,029] Trial 145 finished with value: 0.9664863997921238 and parameters: {'n_estimators': 90, 'learning_rate': 0.012240059099383178, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 1.781648380622396, 'subsample': 0.6369485949906591, 'colsample_bytree': 0.652629959955858, 'reg_alpha': 0.04000735956212741, 'reg_lambda': 0.08861445412603804, 'weight_class_0': 0.363167468882658, 'weight_class_1': 1.5615407178889626, 'weight_class_2': 1.9448159644939782}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  42%|████████████████████████████████████████████████████████▋                                                                               | 25/60 [05:37<04:51,  8.34s/it]

[I 2026-06-18 14:33:27,390] Trial 149 pruned.

Best trial: 105. Best value: 0.966562:  43%|██████████████████████████████████████████████████████████▉                                                                             | 26/60 [05:53<06:01, 10.62s/it]

[I 2026-06-18 14:33:43,325] Trial 144 finished with value: 0.9665048949860541 and parameters: {'n_estimators': 115, 'learning_rate': 0.021297444033495306, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.8996250050122534, 'subsample': 0.6340038226534526, 'colsample_bytree': 0.6206883819911124, 'reg_alpha': 0.04944826969534631, 'reg_lambda': 0.09567898117524153, 'weight_class_0': 0.36805845077506, 'weight_class_1': 1.4517765984809317, 'weight_class_2': 1.937539503939794}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  45%|█████████████████████████████████████████████████████████████▏                                                                          | 27/60 [06:11<07:07, 12.95s/it]

[I 2026-06-18 14:34:01,724] Trial 148 finished with value: 0.9664263918132254 and parameters: {'n_estimators': 88, 'learning_rate': 0.014152454013417276, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.3491311948460867, 'subsample': 0.7824452237985763, 'colsample_bytree': 0.6540165661235805, 'reg_alpha': 0.0356398988296038, 'reg_lambda': 0.0002752022333806449, 'weight_class_0': 0.36068107239239056, 'weight_class_1': 1.5765093630633609, 'weight_class_2': 1.9377954013627874}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  47%|███████████████████████████████████████████████████████████████▍                                                                        | 28/60 [06:12<04:52,  9.13s/it]

[I 2026-06-18 14:34:01,938] Trial 138 finished with value: 0.966440182143755 and parameters: {'n_estimators': 193, 'learning_rate': 0.012212071578105967, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 1.8005114661908004, 'subsample': 0.6334223602498069, 'colsample_bytree': 0.9115119633499457, 'reg_alpha': 0.0011026643088010754, 'reg_lambda': 0.00037990884500048287, 'weight_class_0': 0.44984471530559245, 'weight_class_1': 1.374058830071364, 'weight_class_2': 1.8909756622881972}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  48%|█████████████████████████████████████████████████████████████████▋                                                                      | 29/60 [06:16<03:59,  7.74s/it]

[I 2026-06-18 14:34:06,436] Trial 146 finished with value: 0.966508071558273 and parameters: {'n_estimators': 121, 'learning_rate': 0.014041149800547024, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.4533319712114485, 'subsample': 0.7747464877045332, 'colsample_bytree': 0.6597095542500534, 'reg_alpha': 0.03829595239346943, 'reg_lambda': 4.818523358710187e-05, 'weight_class_0': 0.367697974623482, 'weight_class_1': 1.4439341826092102, 'weight_class_2': 1.9438464553462482}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  50%|████████████████████████████████████████████████████████████████████                                                                    | 30/60 [06:31<05:01, 10.04s/it]

[I 2026-06-18 14:34:21,835] Trial 147 finished with value: 0.9665420781930306 and parameters: {'n_estimators': 115, 'learning_rate': 0.014209655019771873, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.405622215050866, 'subsample': 0.7686756357349568, 'colsample_bytree': 0.6471555639610682, 'reg_alpha': 0.0002805634267861386, 'reg_lambda': 0.12111350674964584, 'weight_class_0': 0.3633625802034193, 'weight_class_1': 1.3787782319494206, 'weight_class_2': 1.952740379666332}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  52%|██████████████████████████████████████████████████████████████████████▎                                                                 | 31/60 [06:34<03:42,  7.69s/it]

[I 2026-06-18 14:34:24,039] Trial 150 finished with value: 0.9664576125874034 and parameters: {'n_estimators': 89, 'learning_rate': 0.021985687348655768, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 8.588796353977159, 'subsample': 0.7518908941989382, 'colsample_bytree': 0.6473306043345409, 'reg_alpha': 0.03302533699993495, 'reg_lambda': 0.0010193591777350709, 'weight_class_0': 0.365814764330236, 'weight_class_1': 1.6129243891692497, 'weight_class_2': 1.940661179710032}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  53%|████████████████████████████████████████████████████████████████████████▌                                                               | 32/60 [06:36<02:49,  6.04s/it]

[I 2026-06-18 14:34:26,228] Trial 151 finished with value: 0.9664590060466731 and parameters: {'n_estimators': 86, 'learning_rate': 0.014233578332775028, 'max_depth': 3, 'min_child_weight': 19, 'gamma': 1.5375094206505928, 'subsample': 0.7548530163628943, 'colsample_bytree': 0.6460893828241995, 'reg_alpha': 0.0002527629428364272, 'reg_lambda': 0.17156700215032672, 'weight_class_0': 0.33851883816531164, 'weight_class_1': 1.1385002967529858, 'weight_class_2': 1.9475274648978167}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  55%|██████████████████████████████████████████████████████████████████████████▊                                                             | 33/60 [06:41<02:36,  5.81s/it]

[I 2026-06-18 14:34:31,521] Trial 152 finished with value: 0.9664962740265028 and parameters: {'n_estimators': 93, 'learning_rate': 0.017317725808605845, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.3979884103938722, 'subsample': 0.8419554630438718, 'colsample_bytree': 0.6502150947548583, 'reg_alpha': 0.032695469717336896, 'reg_lambda': 5.5494587404718075e-05, 'weight_class_0': 0.3532298173429582, 'weight_class_1': 1.4329566335248451, 'weight_class_2': 1.9461158903108493}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  57%|█████████████████████████████████████████████████████████████████████████████                                                           | 34/60 [06:52<03:14,  7.47s/it]

[I 2026-06-18 14:34:42,844] Trial 153 finished with value: 0.9664747242290982 and parameters: {'n_estimators': 89, 'learning_rate': 0.014239466503876938, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.495015224144184, 'subsample': 0.6557858010341889, 'colsample_bytree': 0.6192136525709827, 'reg_alpha': 0.031320787276202904, 'reg_lambda': 4.3564807098934505e-05, 'weight_class_0': 0.37054471316231824, 'weight_class_1': 1.5603064320105131, 'weight_class_2': 1.9587547116747204}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  58%|███████████████████████████████████████████████████████████████████████████████▎                                                        | 35/60 [06:56<02:33,  6.15s/it]

[I 2026-06-18 14:34:45,934] Trial 154 finished with value: 0.9665386809412082 and parameters: {'n_estimators': 89, 'learning_rate': 0.014134477481304577, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.3944163911444694, 'subsample': 0.7644560779378029, 'colsample_bytree': 0.6225671074461119, 'reg_alpha': 0.1746024990206925, 'reg_lambda': 4.448272294250864e-05, 'weight_class_0': 0.36277531665548673, 'weight_class_1': 1.4364601777500436, 'weight_class_2': 1.953206529807514}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  60%|█████████████████████████████████████████████████████████████████████████████████▌                                                      | 36/60 [07:07<03:08,  7.84s/it]

[I 2026-06-18 14:34:57,698] Trial 155 finished with value: 0.9664255535940744 and parameters: {'n_estimators': 86, 'learning_rate': 0.014527331036315953, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.6605804699778532, 'subsample': 0.8319829525047211, 'colsample_bytree': 0.6257801176193297, 'reg_alpha': 1.0103709926309141, 'reg_lambda': 5.006348554328428e-05, 'weight_class_0': 0.349643973109489, 'weight_class_1': 1.1472925454108718, 'weight_class_2': 1.9549482529157494}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  62%|███████████████████████████████████████████████████████████████████████████████████▊                                                    | 37/60 [07:14<02:54,  7.58s/it]

[I 2026-06-18 14:35:04,673] Trial 163 pruned.

Best trial: 105. Best value: 0.966562:  63%|██████████████████████████████████████████████████████████████████████████████████████▏                                                 | 38/60 [07:20<02:35,  7.06s/it]

[I 2026-06-18 14:35:10,537] Trial 156 finished with value: 0.9664344177118782 and parameters: {'n_estimators': 91, 'learning_rate': 0.014529194266784343, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 9.382228523312296, 'subsample': 0.7814050833132344, 'colsample_bytree': 0.6550840702614953, 'reg_alpha': 0.0014400156168649797, 'reg_lambda': 5.393375963269542e-05, 'weight_class_0': 0.3396809712209281, 'weight_class_1': 1.0668589995151196, 'weight_class_2': 1.9507880478568835}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  65%|████████████████████████████████████████████████████████████████████████████████████████▍                                               | 39/60 [07:36<03:26,  9.84s/it]

[I 2026-06-18 14:35:26,854] Trial 157 finished with value: 0.966450972270471 and parameters: {'n_estimators': 92, 'learning_rate': 0.014057142457342438, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 9.551713508302194, 'subsample': 0.6534897991457844, 'colsample_bytree': 0.6543602504427978, 'reg_alpha': 0.06885626718396301, 'reg_lambda': 4.166115993571329e-05, 'weight_class_0': 0.3499761569946372, 'weight_class_1': 1.1416483215455366, 'weight_class_2': 1.9446873916164102}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  67%|██████████████████████████████████████████████████████████████████████████████████████████▋                                             | 40/60 [07:55<04:09, 12.50s/it]

[I 2026-06-18 14:35:45,557] Trial 159 finished with value: 0.9664530051710221 and parameters: {'n_estimators': 92, 'learning_rate': 0.014590852454017159, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 2.6923949384606294, 'subsample': 0.6528221810325538, 'colsample_bytree': 0.6289498390379537, 'reg_alpha': 0.06845664893373508, 'reg_lambda': 3.5768056482772805e-05, 'weight_class_0': 0.3549389168524592, 'weight_class_1': 1.1882003708870845, 'weight_class_2': 1.9995854642949598}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  68%|████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 41/60 [08:02<03:23, 10.72s/it]

[I 2026-06-18 14:35:52,117] Trial 158 finished with value: 0.9664605621003289 and parameters: {'n_estimators': 94, 'learning_rate': 0.03257648862039928, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 1.5500345305506436, 'subsample': 0.6532600451141172, 'colsample_bytree': 0.6427179545543712, 'reg_alpha': 0.06876718173308664, 'reg_lambda': 1.9171226316990183e-05, 'weight_class_0': 0.3551736353944722, 'weight_class_1': 1.0527338961302046, 'weight_class_2': 1.9515663994914965}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 42/60 [08:22<04:04, 13.59s/it]

[I 2026-06-18 14:36:12,406] Trial 160 finished with value: 0.9664624964212969 and parameters: {'n_estimators': 111, 'learning_rate': 0.02134562903967052, 'max_depth': 3, 'min_child_weight': 3, 'gamma': 8.137323040340558, 'subsample': 0.7656774293649847, 'colsample_bytree': 0.641012741508061, 'reg_alpha': 0.06929275830210803, 'reg_lambda': 4.8126609678290586e-05, 'weight_class_0': 0.35062679146741305, 'weight_class_1': 1.1476992106690591, 'weight_class_2': 1.949454129748051}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  72%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 43/60 [08:28<03:14, 11.46s/it]

[I 2026-06-18 14:36:18,886] Trial 164 finished with value: 0.9660293265815895 and parameters: {'n_estimators': 98, 'learning_rate': 0.017412643951883723, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.4627941578471617, 'subsample': 0.8292161474389479, 'colsample_bytree': 0.6324594394021126, 'reg_alpha': 0.0500651235557565, 'reg_lambda': 3.742285222347149e-05, 'weight_class_0': 0.27026680705961825, 'weight_class_1': 1.2862904846059864, 'weight_class_2': 1.993615568002033}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  73%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 44/60 [08:34<02:36,  9.78s/it]

[I 2026-06-18 14:36:24,740] Trial 169 pruned.

Best trial: 105. Best value: 0.966562:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 45/60 [08:40<02:06,  8.45s/it]

[I 2026-06-18 14:36:30,091] Trial 165 finished with value: 0.9656866383868546 and parameters: {'n_estimators': 99, 'learning_rate': 0.015139670572834682, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 3.8884608569347545, 'subsample': 0.8185667550040285, 'colsample_bytree': 0.6279676505727171, 'reg_alpha': 0.05380941734602031, 'reg_lambda': 0.06053585090302407, 'weight_class_0': 0.2671665332532271, 'weight_class_1': 1.5668406069473262, 'weight_class_2': 1.995686800639078}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 46/60 [08:53<02:18,  9.93s/it]

[I 2026-06-18 14:36:43,471] Trial 166 finished with value: 0.9658497468539858 and parameters: {'n_estimators': 109, 'learning_rate': 0.016697038287337138, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.0383109891055486, 'subsample': 0.8179971313242934, 'colsample_bytree': 0.6290190234531127, 'reg_alpha': 0.07057517617777603, 'reg_lambda': 0.05785183530739626, 'weight_class_0': 0.2721213073452893, 'weight_class_1': 1.5741463018102608, 'weight_class_2': 1.998414062087848}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 47/60 [09:35<04:13, 19.50s/it]

[I 2026-06-18 14:37:25,304] Trial 170 finished with value: 0.9660118743618288 and parameters: {'n_estimators': 106, 'learning_rate': 0.01787371298728931, 'max_depth': 3, 'min_child_weight': 8, 'gamma': 0.6318293697951933, 'subsample': 0.6128776957247002, 'colsample_bytree': 0.6179563402440162, 'reg_alpha': 0.1638583817155403, 'reg_lambda': 2.177251916751973e-05, 'weight_class_0': 0.2733928365802736, 'weight_class_1': 1.4209881916325113, 'weight_class_2': 1.9983619121361034}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 48/60 [09:40<03:01, 15.09s/it]

[I 2026-06-18 14:37:30,103] Trial 168 pruned.

Best trial: 105. Best value: 0.966562:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 49/60 [09:54<02:43, 14.87s/it]

[I 2026-06-18 14:37:44,482] Trial 171 finished with value: 0.9655379195289608 and parameters: {'n_estimators': 105, 'learning_rate': 0.01774186965688449, 'max_depth': 3, 'min_child_weight': 6, 'gamma': 0.6174204186498737, 'subsample': 0.614693278257342, 'colsample_bytree': 0.6148672823455837, 'reg_alpha': 0.1699440366115106, 'reg_lambda': 0.0818945451986457, 'weight_class_0': 0.2477241896089667, 'weight_class_1': 1.5687975627982265, 'weight_class_2': 1.865833171883837}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 50/60 [10:14<02:43, 16.36s/it]

[I 2026-06-18 14:38:04,299] Trial 173 finished with value: 0.9656553795099928 and parameters: {'n_estimators': 104, 'learning_rate': 0.017515864921885185, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9974737540829572, 'subsample': 0.8038744133041098, 'colsample_bytree': 0.6178459216292301, 'reg_alpha': 0.018763029856786604, 'reg_lambda': 0.00012900679137709092, 'weight_class_0': 0.25029483867644037, 'weight_class_1': 1.566928839366828, 'weight_class_2': 1.8706602323568593}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 51/60 [10:27<02:19, 15.51s/it]

[I 2026-06-18 14:38:17,822] Trial 177 finished with value: 0.9664299192643601 and parameters: {'n_estimators': 78, 'learning_rate': 0.050365802952509225, 'max_depth': 3, 'min_child_weight': 9, 'gamma': 0.5664906369028253, 'subsample': 0.6855996313801266, 'colsample_bytree': 0.6154778924658661, 'reg_alpha': 0.16844624140024458, 'reg_lambda': 0.00012670766002795557, 'weight_class_0': 0.3183225788468107, 'weight_class_1': 1.4227962644337062, 'weight_class_2': 1.8671428492842537}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 52/60 [10:35<01:45, 13.20s/it]

[I 2026-06-18 14:38:25,652] Trial 161 finished with value: 0.9660421887958156 and parameters: {'n_estimators': 218, 'learning_rate': 0.022550184994310662, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.5117137777318732, 'subsample': 0.6546396305384131, 'colsample_bytree': 0.6331649689199663, 'reg_alpha': 0.06917617323291426, 'reg_lambda': 2.06633057787333e-05, 'weight_class_0': 0.26308304701121477, 'weight_class_1': 1.1309611846987975, 'weight_class_2': 1.9579902221270507}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 53/60 [10:45<01:24, 12.13s/it]

[I 2026-06-18 14:38:35,280] Trial 176 finished with value: 0.9664622035862085 and parameters: {'n_estimators': 131, 'learning_rate': 0.017659522189974235, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 1.0069152866062663, 'subsample': 0.6843219306411359, 'colsample_bytree': 0.6157577403230261, 'reg_alpha': 0.021064376257326684, 'reg_lambda': 0.00010062116760158247, 'weight_class_0': 0.3112798335962929, 'weight_class_1': 1.438515466472161, 'weight_class_2': 1.870559839124235}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 54/60 [10:52<01:04, 10.72s/it]

[I 2026-06-18 14:38:42,700] Trial 167 finished with value: 0.9659878278913983 and parameters: {'n_estimators': 214, 'learning_rate': 0.01730912611061772, 'max_depth': 3, 'min_child_weight': 8, 'gamma': 9.230187838795068, 'subsample': 0.7766337879162188, 'colsample_bytree': 0.6347533387931347, 'reg_alpha': 0.41445270447260474, 'reg_lambda': 1.608384280065003e-05, 'weight_class_0': 0.26956794425660185, 'weight_class_1': 1.4168769814909967, 'weight_class_2': 1.998903700385765}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 55/60 [10:53<00:38,  7.74s/it]

[I 2026-06-18 14:38:43,502] Trial 179 finished with value: 0.9665156160028434 and parameters: {'n_estimators': 75, 'learning_rate': 0.020101719915299802, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 2.060621178964481, 'subsample': 0.7431891900360303, 'colsample_bytree': 0.6803071412464075, 'reg_alpha': 0.473025864381785, 'reg_lambda': 0.00014957237235107258, 'weight_class_0': 0.31230508390734224, 'weight_class_1': 1.3762147851761068, 'weight_class_2': 1.8750383341124879}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 56/60 [11:13<00:45, 11.27s/it]

[I 2026-06-18 14:39:03,012] Trial 172 finished with value: 0.9656285720041998 and parameters: {'n_estimators': 215, 'learning_rate': 0.01772030275903168, 'max_depth': 3, 'min_child_weight': 9, 'gamma': 0.6733399962497498, 'subsample': 0.7938128670700538, 'colsample_bytree': 0.6188736229586278, 'reg_alpha': 0.42921699393127866, 'reg_lambda': 0.06705516376978651, 'weight_class_0': 0.24732479154331022, 'weight_class_1': 1.562732375649596, 'weight_class_2': 1.8654159731492053}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 57/60 [11:14<00:24,  8.24s/it]

[I 2026-06-18 14:39:04,169] Trial 178 pruned.

Best trial: 105. Best value: 0.966562:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 58/60 [11:24<00:17,  8.69s/it]

[I 2026-06-18 14:39:13,913] Trial 174 finished with value: 0.9664650204663532 and parameters: {'n_estimators': 220, 'learning_rate': 0.017574095319734112, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 3.771084157475358, 'subsample': 0.7923860357345857, 'colsample_bytree': 0.6134420379930517, 'reg_alpha': 0.017703385589318266, 'reg_lambda': 0.077105964503766, 'weight_class_0': 0.3192411249959975, 'weight_class_1': 1.4226420701004745, 'weight_class_2': 1.829096495393345}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 59/60 [11:32<00:08,  8.73s/it]

[I 2026-06-18 14:39:22,734] Trial 175 finished with value: 0.9663647533996773 and parameters: {'n_estimators': 210, 'learning_rate': 0.01726825185342794, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9896322552721957, 'subsample': 0.6652749412517006, 'colsample_bytree': 0.6792365334487718, 'reg_alpha': 0.017934414163542155, 'reg_lambda': 0.00013294399769766415, 'weight_class_0': 0.29393367832695083, 'weight_class_1': 1.4197091826529022, 'weight_class_2': 1.8763038108188155}. Best is trial 105 with value: 0.9665620964645611.

Best trial: 105. Best value: 0.966562: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [12:18<00:00, 12.31s/it]

[I 2026-06-18 14:40:08,397] Trial 162 finished with value: 0.9664271738032311 and parameters: {'n_estimators': 466, 'learning_rate': 0.014385708378549225, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.5451503514541343, 'subsample': 0.7681544490170222, 'colsample_bytree': 0.6350802409209809, 'reg_alpha': 0.05160734481760502, 'reg_lambda': 3.200265374372273e-05, 'weight_class_0': 0.3278220997226016, 'weight_class_1': 1.2931850974460883, 'weight_class_2': 1.9583199498222164}. Best is trial 105 with value: 0.9665620964645611.

In [20]:
xgb_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

xgb = XGBClassifier(
    **xgb_params,
    objective='multi:softprob',
    num_class=3,
    random_state=42,
    n_jobs=-1,
    eval_metric='mlogloss'
).fit(X_train, y_train.class_encoded)

test_proba = xgb.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [21]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [22]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_xgb.csv', index=False)

In [23]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [24]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'hist_0', 'hist_1', 'hist_2', 'rf_0', 'rf_1', 'rf_2',
       'extra_0', 'extra_1', 'extra_2'],
      dtype='str')