# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle
from lightgbm import LGBMClassifier

from sklearn.metrics import log_loss, balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/X_train_stacking_layer_three.parquet')
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_three.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.999778,0.000212,0.000009,0.999787,0.000174,0.000040,0.999864,0.000121,0.000016,0.999733,0.000264,2.459617e-06,0.999775,0.000225,2.616556e-08,0.998912,0.000955,0.000133
1,0.994627,0.000176,0.005197,0.995247,0.000365,0.004388,0.992235,0.000199,0.007566,0.973059,0.000137,2.680453e-02,0.994737,0.000047,5.216709e-03,0.976808,0.000850,0.022342
2,0.000048,0.999944,0.000008,0.000483,0.999485,0.000032,0.000169,0.999822,0.000009,0.000015,0.999984,1.319155e-06,0.000011,0.999989,9.836632e-08,0.000068,0.999897,0.000035
3,0.999915,0.000081,0.000005,0.999745,0.000217,0.000039,0.999858,0.000127,0.000014,0.999960,0.000040,6.602657e-07,0.999793,0.000207,3.828407e-08,0.998919,0.000947,0.000134
4,0.998164,0.001812,0.000024,0.998143,0.001764,0.000093,0.998504,0.001459,0.000037,0.986426,0.013556,1.806930e-05,0.998227,0.001769,3.566911e-06,0.994430,0.005248,0.000322

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,hist_0,hist_1,hist_2,rf_0,rf_1,rf_2,extra_0,extra_1,extra_2
0,0.998177,0.001784,0.000039,0.997654,0.002153,0.000193,0.998108,0.001843,0.000049,0.997980,0.002008,0.000012,0.998183,0.001800,0.000017,0.993598,0.005832,0.000569
1,0.997269,0.002710,0.000021,0.997945,0.001978,0.000077,0.997185,0.002778,0.000037,0.994660,0.005324,0.000015,0.997905,0.002092,0.000003,0.993669,0.005970,0.000361
2,0.996089,0.000609,0.003303,0.997698,0.000711,0.001592,0.997502,0.000382,0.002115,0.997295,0.001499,0.001207,0.997506,0.000715,0.001780,0.988872,0.002584,0.008544
3,0.000643,0.000107,0.999250,0.001658,0.000165,0.998177,0.000730,0.000132,0.999138,0.000139,0.000020,0.999841,0.000541,0.000023,0.999436,0.000378,0.000214,0.999409
4,0.999631,0.000357,0.000012,0.999578,0.000365,0.000058,0.999737,0.000245,0.000018,0.999526,0.000469,0.000005,0.999785,0.000205,0.000010,0.998670,0.001116,0.000214

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx, :]
        X_valid_fold = X.iloc[valid_idx, :]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        model = model = LGBMClassifier(
            objective='multiclass',
            metric='multi_logloss',
            boosting_type='gbdt',
            verbosity=-1,
            random_state=42,
            n_jobs=1,
            n_estimators=trial.suggest_int('n_estimators', 50, 500),
            learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
            num_leaves=trial.suggest_int('num_leaves', 2, 32),
            max_depth=trial.suggest_int('max_depth', 1, 6),
            min_child_samples=trial.suggest_int('min_child_samples', 5, 100),
            lambda_l1=trial.suggest_float('lambda_l1', 1e-5, 10.0, log=True),
            lambda_l2=trial.suggest_float('lambda_l2', 1e-5, 10.0, log=True),
            feature_fraction=trial.suggest_float('feature_fraction', 0.7, 1.0),
            bagging_fraction=trial.suggest_float('bagging_fraction', 0.7, 1.0),
            bagging_freq=trial.suggest_int('bagging_freq', 1, 5),
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)

        w0 = trial.suggest_float('weight_class_0', 0.1, 2.0)
        w1 = trial.suggest_float('weight_class_1', 0.1, 2.0)
        w2 = trial.suggest_float('weight_class_2', 0.1, 2.0)

        weighted_probas = proba * np.array([w0, w1, w2])

        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=60, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-06-18 15:05:46,241] A new study created in memory with name: no-name-405e4455-e2a5-42d9-a92d-8ea75a3ab31c
Best trial: 1. Best value: 0.951342:   2%|██▎                                                                                                                                        | 1/60 [00:36<35:52, 36.48s/it]

[I 2026-06-18 15:06:22,722] Trial 1 finished with value: 0.9513424390358345 and parameters: {'n_estimators': 68, 'learning_rate': 0.2112075956127585, 'num_leaves': 2, 'max_depth': 3, 'min_child_samples': 99, 'lambda_l1': 0.010096595800012756, 'lambda_l2': 0.007033843714582129, 'feature_fraction': 0.7809207419147921, 'bagging_fraction': 0.7936875031290453, 'bagging_freq': 1, 'weight_class_0': 1.945284331981904, 'weight_class_1': 1.6598249293411205, 'weight_class_2': 1.0335848111484525}. Best is trial 1 with value: 0.9513424390358345.

Best trial: 1. Best value: 0.951342:   3%|████▋                                                                                                                                      | 2/60 [01:20<39:47, 41.17s/it]

[I 2026-06-18 15:07:07,173] Trial 5 finished with value: 0.9123742554601068 and parameters: {'n_estimators': 112, 'learning_rate': 0.015273323381813753, 'num_leaves': 9, 'max_depth': 3, 'min_child_samples': 41, 'lambda_l1': 0.08837170918538327, 'lambda_l2': 0.15954364044901326, 'feature_fraction': 0.9978902474865221, 'bagging_fraction': 0.7735702233514751, 'bagging_freq': 4, 'weight_class_0': 1.4453039703489543, 'weight_class_1': 1.1110714797560481, 'weight_class_2': 0.2628112957828161}. Best is trial 1 with value: 0.9513424390358345.

Best trial: 8. Best value: 0.960259:   5%|██████▉                                                                                                                                    | 3/60 [01:37<28:17, 29.78s/it]

[I 2026-06-18 15:07:23,404] Trial 8 finished with value: 0.9602586765670225 and parameters: {'n_estimators': 114, 'learning_rate': 0.030025406304374006, 'num_leaves': 7, 'max_depth': 6, 'min_child_samples': 6, 'lambda_l1': 0.00302339447593168, 'lambda_l2': 4.466721225576024e-05, 'feature_fraction': 0.9058715509680656, 'bagging_fraction': 0.931872637361393, 'bagging_freq': 5, 'weight_class_0': 0.9579063387601587, 'weight_class_1': 0.8185615371221181, 'weight_class_2': 1.4330829389479247}. Best is trial 8 with value: 0.9602586765670225.

Best trial: 8. Best value: 0.960259:   7%|█████████▎                                                                                                                                 | 4/60 [02:04<26:48, 28.73s/it]

[I 2026-06-18 15:07:50,520] Trial 7 finished with value: 0.9460190145716707 and parameters: {'n_estimators': 264, 'learning_rate': 0.12701420834443453, 'num_leaves': 5, 'max_depth': 1, 'min_child_samples': 82, 'lambda_l1': 4.074962405510863e-05, 'lambda_l2': 0.00010945034127563078, 'feature_fraction': 0.7302020123772995, 'bagging_fraction': 0.9106027519016175, 'bagging_freq': 2, 'weight_class_0': 1.7080338564287734, 'weight_class_1': 0.5793741399806913, 'weight_class_2': 0.9918214645941952}. Best is trial 8 with value: 0.9602586765670225.

Best trial: 8. Best value: 0.960259:   8%|███████████▌                                                                                                                               | 5/60 [02:11<19:20, 21.10s/it]

[I 2026-06-18 15:07:58,084] Trial 0 finished with value: 0.9352967215083929 and parameters: {'n_estimators': 152, 'learning_rate': 0.2643808021683223, 'num_leaves': 12, 'max_depth': 4, 'min_child_samples': 53, 'lambda_l1': 2.1125250254976327e-05, 'lambda_l2': 0.0003262762924055562, 'feature_fraction': 0.9248949377575147, 'bagging_fraction': 0.7334323112983554, 'bagging_freq': 1, 'weight_class_0': 1.5580954739252957, 'weight_class_1': 1.4710358441859999, 'weight_class_2': 0.6913603613955208}. Best is trial 8 with value: 0.9602586765670225.

Best trial: 8. Best value: 0.960259:  10%|█████████████▉                                                                                                                             | 6/60 [02:28<17:35, 19.55s/it]

[I 2026-06-18 15:08:14,613] Trial 14 pruned.

Best trial: 8. Best value: 0.960259:  12%|████████████████▏                                                                                                                          | 7/60 [02:41<15:16, 17.30s/it]

[I 2026-06-18 15:08:27,297] Trial 16 pruned.

Best trial: 8. Best value: 0.960259:  13%|██████████████████▌                                                                                                                        | 8/60 [03:06<17:14, 19.89s/it]

[I 2026-06-18 15:08:52,732] Trial 15 finished with value: 0.9580362382845229 and parameters: {'n_estimators': 136, 'learning_rate': 0.04483554853092766, 'num_leaves': 29, 'max_depth': 1, 'min_child_samples': 87, 'lambda_l1': 0.003363128979782055, 'lambda_l2': 0.0012013826628368824, 'feature_fraction': 0.7138762784414756, 'bagging_fraction': 0.7620525754441474, 'bagging_freq': 3, 'weight_class_0': 1.478348804196849, 'weight_class_1': 1.1574310520736033, 'weight_class_2': 1.7920728718167003}. Best is trial 8 with value: 0.9602586765670225.

Best trial: 8. Best value: 0.960259:  15%|████████████████████▊                                                                                                                      | 9/60 [03:14<13:37, 16.03s/it]

[I 2026-06-18 15:09:00,252] Trial 4 finished with value: 0.9494663538625133 and parameters: {'n_estimators': 298, 'learning_rate': 0.10292987637752983, 'num_leaves': 4, 'max_depth': 5, 'min_child_samples': 24, 'lambda_l1': 0.008849548854056127, 'lambda_l2': 3.153772893037215, 'feature_fraction': 0.7072108240744857, 'bagging_fraction': 0.8914488984342892, 'bagging_freq': 1, 'weight_class_0': 1.9242376037459465, 'weight_class_1': 0.595811282119946, 'weight_class_2': 1.6767643027049948}. Best is trial 8 with value: 0.9602586765670225.

Best trial: 6. Best value: 0.965423:  17%|███████████████████████                                                                                                                   | 10/60 [03:20<10:46, 12.94s/it]

[I 2026-06-18 15:09:06,294] Trial 6 finished with value: 0.9654230885535797 and parameters: {'n_estimators': 343, 'learning_rate': 0.14186437491286336, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 97, 'lambda_l1': 2.1869174455637474e-05, 'lambda_l2': 0.04841917423798459, 'feature_fraction': 0.7660012696948617, 'bagging_fraction': 0.853347545379779, 'bagging_freq': 4, 'weight_class_0': 0.35489520720769074, 'weight_class_1': 0.5443035296229239, 'weight_class_2': 1.3134826914800402}. Best is trial 6 with value: 0.9654230885535797.

Best trial: 6. Best value: 0.965423:  18%|█████████████████████████▎                                                                                                                | 11/60 [03:31<10:04, 12.34s/it]

[I 2026-06-18 15:09:17,285] Trial 9 finished with value: 0.9558798850347024 and parameters: {'n_estimators': 185, 'learning_rate': 0.023903664863277514, 'num_leaves': 19, 'max_depth': 4, 'min_child_samples': 77, 'lambda_l1': 0.02688584676188601, 'lambda_l2': 6.023406448688236e-05, 'feature_fraction': 0.9430281688869211, 'bagging_fraction': 0.9263807679754474, 'bagging_freq': 4, 'weight_class_0': 1.3470580880867729, 'weight_class_1': 0.7768948919327907, 'weight_class_2': 1.5743356587165018}. Best is trial 6 with value: 0.9654230885535797.

Best trial: 6. Best value: 0.965423:  20%|███████████████████████████▌                                                                                                              | 12/60 [03:43<09:55, 12.41s/it]

[I 2026-06-18 15:09:29,855] Trial 17 pruned.

Best trial: 6. Best value: 0.965423:  22%|█████████████████████████████▉                                                                                                            | 13/60 [03:50<08:20, 10.64s/it]

[I 2026-06-18 15:09:36,428] Trial 3 pruned.

Best trial: 10. Best value: 0.965896:  23%|███████████████████████████████▉                                                                                                         | 14/60 [04:06<09:25, 12.28s/it]

[I 2026-06-18 15:09:52,491] Trial 10 finished with value: 0.9658962444525903 and parameters: {'n_estimators': 341, 'learning_rate': 0.06087195382573311, 'num_leaves': 5, 'max_depth': 3, 'min_child_samples': 24, 'lambda_l1': 0.0035821591448307244, 'lambda_l2': 0.544943300980015, 'feature_fraction': 0.9317723493736599, 'bagging_fraction': 0.8730825998355726, 'bagging_freq': 3, 'weight_class_0': 0.25842368516760017, 'weight_class_1': 0.621725080406992, 'weight_class_2': 0.7773493772438632}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  25%|██████████████████████████████████▎                                                                                                      | 15/60 [04:26<10:56, 14.59s/it]

[I 2026-06-18 15:10:12,439] Trial 13 finished with value: 0.9620226591216177 and parameters: {'n_estimators': 314, 'learning_rate': 0.031052291477724876, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 61, 'lambda_l1': 0.07986105480999789, 'lambda_l2': 0.0006481860226442634, 'feature_fraction': 0.7677279244494839, 'bagging_fraction': 0.7477700519547206, 'bagging_freq': 5, 'weight_class_0': 0.6210240029442121, 'weight_class_1': 0.6797908770867477, 'weight_class_2': 1.0167701781449265}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  27%|████████████████████████████████████▌                                                                                                    | 16/60 [04:35<09:27, 12.89s/it]

[I 2026-06-18 15:10:21,379] Trial 18 pruned.

Best trial: 10. Best value: 0.965896:  28%|██████████████████████████████████████▊                                                                                                  | 17/60 [05:51<22:50, 31.87s/it]

[I 2026-06-18 15:11:37,379] Trial 12 finished with value: 0.9614636871155536 and parameters: {'n_estimators': 302, 'learning_rate': 0.12170033264379955, 'num_leaves': 25, 'max_depth': 6, 'min_child_samples': 13, 'lambda_l1': 0.0918260474268501, 'lambda_l2': 0.2880218833886456, 'feature_fraction': 0.7271726537666439, 'bagging_fraction': 0.7851212151679358, 'bagging_freq': 3, 'weight_class_0': 0.8233830561315064, 'weight_class_1': 0.6926860320816697, 'weight_class_2': 1.6708323636958642}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  30%|█████████████████████████████████████████                                                                                                | 18/60 [07:14<33:07, 47.32s/it]

[I 2026-06-18 15:13:00,672] Trial 2 pruned.

Best trial: 10. Best value: 0.965896:  32%|███████████████████████████████████████████▍                                                                                             | 19/60 [07:42<28:26, 41.62s/it]

[I 2026-06-18 15:13:29,001] Trial 20 finished with value: 0.9625724071272093 and parameters: {'n_estimators': 425, 'learning_rate': 0.08480692913511875, 'num_leaves': 22, 'max_depth': 2, 'min_child_samples': 92, 'lambda_l1': 0.01499650854248955, 'lambda_l2': 0.00015699395759638773, 'feature_fraction': 0.7037382166730014, 'bagging_fraction': 0.9176740322874766, 'bagging_freq': 2, 'weight_class_0': 0.9502593565279384, 'weight_class_1': 1.4082059263932147, 'weight_class_2': 1.5382417083168793}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  33%|█████████████████████████████████████████████▋                                                                                           | 20/60 [08:23<27:39, 41.50s/it]

[I 2026-06-18 15:14:10,222] Trial 23 pruned.

Best trial: 10. Best value: 0.965896:  35%|███████████████████████████████████████████████▉                                                                                         | 21/60 [08:30<20:13, 31.12s/it]

[I 2026-06-18 15:14:17,143] Trial 22 pruned.

Best trial: 10. Best value: 0.965896:  37%|██████████████████████████████████████████████████▏                                                                                      | 22/60 [08:53<18:05, 28.58s/it]

[I 2026-06-18 15:14:39,796] Trial 24 pruned.

Best trial: 10. Best value: 0.965896:  38%|████████████████████████████████████████████████████▌                                                                                    | 23/60 [09:46<22:03, 35.78s/it]

[I 2026-06-18 15:15:32,367] Trial 11 finished with value: 0.9605551322446987 and parameters: {'n_estimators': 474, 'learning_rate': 0.07409549109804997, 'num_leaves': 27, 'max_depth': 5, 'min_child_samples': 90, 'lambda_l1': 0.0004309189477433714, 'lambda_l2': 0.0022578647704992456, 'feature_fraction': 0.9381253179266112, 'bagging_fraction': 0.8991450131950977, 'bagging_freq': 3, 'weight_class_0': 1.029693838327132, 'weight_class_1': 1.7180166250264746, 'weight_class_2': 1.3729869171384605}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  40%|██████████████████████████████████████████████████████▊                                                                                  | 24/60 [10:31<23:09, 38.59s/it]

[I 2026-06-18 15:16:17,502] Trial 19 finished with value: 0.9647877722618713 and parameters: {'n_estimators': 440, 'learning_rate': 0.010997320680723005, 'num_leaves': 19, 'max_depth': 4, 'min_child_samples': 54, 'lambda_l1': 0.00018660557110233055, 'lambda_l2': 0.3917559527640071, 'feature_fraction': 0.9240234921607131, 'bagging_fraction': 0.7591204450685214, 'bagging_freq': 3, 'weight_class_0': 0.47072943047415683, 'weight_class_1': 1.5633050310793999, 'weight_class_2': 1.097870158580213}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  42%|█████████████████████████████████████████████████████████                                                                                | 25/60 [10:52<19:32, 33.49s/it]

[I 2026-06-18 15:16:39,108] Trial 26 finished with value: 0.961852995446882 and parameters: {'n_estimators': 441, 'learning_rate': 0.07714092418395657, 'num_leaves': 14, 'max_depth': 6, 'min_child_samples': 39, 'lambda_l1': 0.00025063000888588194, 'lambda_l2': 0.16256557222705278, 'feature_fraction': 0.858404917719116, 'bagging_fraction': 0.8384280640236191, 'bagging_freq': 3, 'weight_class_0': 0.11105338864543629, 'weight_class_1': 0.1533163224668584, 'weight_class_2': 1.2715327426148606}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  43%|███████████████████████████████████████████████████████████▎                                                                             | 26/60 [10:59<14:24, 25.42s/it]

[I 2026-06-18 15:16:45,702] Trial 25 finished with value: 0.9618102342539908 and parameters: {'n_estimators': 448, 'learning_rate': 0.07935991552379983, 'num_leaves': 12, 'max_depth': 6, 'min_child_samples': 66, 'lambda_l1': 0.00034421075406441406, 'lambda_l2': 0.15216347412804723, 'feature_fraction': 0.8376116236906735, 'bagging_fraction': 0.9948101468399895, 'bagging_freq': 3, 'weight_class_0': 0.29762856977980495, 'weight_class_1': 0.1815810121684338, 'weight_class_2': 1.24996139835778}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  45%|█████████████████████████████████████████████████████████████▋                                                                           | 27/60 [11:29<14:41, 26.70s/it]

[I 2026-06-18 15:17:15,399] Trial 33 pruned.

Best trial: 10. Best value: 0.965896:  47%|███████████████████████████████████████████████████████████████▉                                                                         | 28/60 [11:38<11:31, 21.60s/it]

[I 2026-06-18 15:17:25,089] Trial 28 finished with value: 0.9623611860017902 and parameters: {'n_estimators': 435, 'learning_rate': 0.06864991619641042, 'num_leaves': 13, 'max_depth': 3, 'min_child_samples': 41, 'lambda_l1': 0.00015472247363531664, 'lambda_l2': 0.01363869089995392, 'feature_fraction': 0.8504970057978648, 'bagging_fraction': 0.8443437247846985, 'bagging_freq': 2, 'weight_class_0': 0.11546185383853749, 'weight_class_1': 0.1695330900864111, 'weight_class_2': 1.2755164533876793}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  48%|██████████████████████████████████████████████████████████████████▏                                                                      | 29/60 [11:40<08:04, 15.63s/it]

[I 2026-06-18 15:17:26,783] Trial 34 pruned.

Best trial: 10. Best value: 0.965896:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 30/60 [11:48<06:42, 13.42s/it]

[I 2026-06-18 15:17:35,066] Trial 27 finished with value: 0.9610947115768006 and parameters: {'n_estimators': 433, 'learning_rate': 0.08018795112831964, 'num_leaves': 14, 'max_depth': 6, 'min_child_samples': 5, 'lambda_l1': 9.145615338342195, 'lambda_l2': 0.2461032456197866, 'feature_fraction': 0.8515617245178698, 'bagging_fraction': 0.842366735219455, 'bagging_freq': 3, 'weight_class_0': 0.10722035034884358, 'weight_class_1': 0.13131317815158433, 'weight_class_2': 1.2960590204522575}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  52%|██████████████████████████████████████████████████████████████████████▊                                                                  | 31/60 [12:00<06:11, 12.81s/it]

[I 2026-06-18 15:17:46,431] Trial 32 pruned.

Best trial: 10. Best value: 0.965896:  53%|█████████████████████████████████████████████████████████████████████████                                                                | 32/60 [12:04<04:43, 10.14s/it]

[I 2026-06-18 15:17:50,330] Trial 21 finished with value: 0.9614948451568864 and parameters: {'n_estimators': 471, 'learning_rate': 0.05733669865577319, 'num_leaves': 16, 'max_depth': 6, 'min_child_samples': 71, 'lambda_l1': 9.726627982539876, 'lambda_l2': 8.513372138283396, 'feature_fraction': 0.8403317134918172, 'bagging_fraction': 0.9949327859519665, 'bagging_freq': 5, 'weight_class_0': 0.1318306654636453, 'weight_class_1': 0.1419452379323899, 'weight_class_2': 1.3499005033947649}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  55%|███████████████████████████████████████████████████████████████████████████▎                                                             | 33/60 [12:55<10:07, 22.51s/it]

[I 2026-06-18 15:18:41,733] Trial 29 finished with value: 0.9637732200752598 and parameters: {'n_estimators': 411, 'learning_rate': 0.07384249821064318, 'num_leaves': 15, 'max_depth': 3, 'min_child_samples': 70, 'lambda_l1': 5.7937079437429215, 'lambda_l2': 0.011397418144434622, 'feature_fraction': 0.8346494297002588, 'bagging_fraction': 0.8373946216690169, 'bagging_freq': 2, 'weight_class_0': 0.11000489235736788, 'weight_class_1': 0.33055049433967865, 'weight_class_2': 1.2959145894711122}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 34/60 [13:00<07:26, 17.18s/it]

[I 2026-06-18 15:18:46,460] Trial 31 finished with value: 0.961536704863987 and parameters: {'n_estimators': 353, 'learning_rate': 0.06879501673546773, 'num_leaves': 16, 'max_depth': 3, 'min_child_samples': 72, 'lambda_l1': 0.7076753787992534, 'lambda_l2': 1.1108805059805467, 'feature_fraction': 0.8212192185602512, 'bagging_fraction': 0.8229614464532954, 'bagging_freq': 4, 'weight_class_0': 0.2250307057130843, 'weight_class_1': 0.20608178203873828, 'weight_class_2': 1.972285327109231}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  58%|███████████████████████████████████████████████████████████████████████████████▉                                                         | 35/60 [13:09<06:12, 14.91s/it]

[I 2026-06-18 15:18:56,073] Trial 38 pruned.

Best trial: 10. Best value: 0.965896:  60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 36/60 [13:16<04:58, 12.45s/it]

[I 2026-06-18 15:19:02,793] Trial 39 pruned.

Best trial: 10. Best value: 0.965896:  62%|████████████████████████████████████████████████████████████████████████████████████▍                                                    | 37/60 [13:23<04:10, 10.91s/it]

[I 2026-06-18 15:19:10,107] Trial 30 finished with value: 0.96237811737104 and parameters: {'n_estimators': 358, 'learning_rate': 0.06728852575045985, 'num_leaves': 15, 'max_depth': 4, 'min_child_samples': 72, 'lambda_l1': 0.768083291831854, 'lambda_l2': 0.03176893334787091, 'feature_fraction': 0.8438897599031996, 'bagging_fraction': 0.8347527115717852, 'bagging_freq': 4, 'weight_class_0': 0.126485047113429, 'weight_class_1': 0.13710331388180258, 'weight_class_2': 1.1271835986267196}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 38/60 [14:16<08:37, 23.50s/it]

[I 2026-06-18 15:20:02,995] Trial 43 pruned.

Best trial: 10. Best value: 0.965896:  65%|█████████████████████████████████████████████████████████████████████████████████████████                                                | 39/60 [14:33<07:28, 21.36s/it]

[I 2026-06-18 15:20:19,370] Trial 42 pruned.

Best trial: 10. Best value: 0.965896:  67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 40/60 [14:44<06:09, 18.49s/it]

[I 2026-06-18 15:20:31,127] Trial 40 pruned.

Best trial: 10. Best value: 0.965896:  68%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 41/60 [14:53<04:57, 15.64s/it]

[I 2026-06-18 15:20:40,128] Trial 41 pruned.

Best trial: 10. Best value: 0.965896:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 42/60 [15:20<05:38, 18.81s/it]

[I 2026-06-18 15:21:06,351] Trial 35 finished with value: 0.9624138056485505 and parameters: {'n_estimators': 378, 'learning_rate': 0.1598611452823453, 'num_leaves': 16, 'max_depth': 3, 'min_child_samples': 71, 'lambda_l1': 1.3390449983812482e-05, 'lambda_l2': 0.5757355000785161, 'feature_fraction': 0.8146502047926372, 'bagging_fraction': 0.827704152454934, 'bagging_freq': 2, 'weight_class_0': 0.14407556207337938, 'weight_class_1': 1.8512216045680439, 'weight_class_2': 1.1705990540156253}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  72%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 43/60 [16:14<08:22, 29.54s/it]

[I 2026-06-18 15:22:00,916] Trial 48 finished with value: 0.957444650020989 and parameters: {'n_estimators': 262, 'learning_rate': 0.28479332176536426, 'num_leaves': 5, 'max_depth': 3, 'min_child_samples': 49, 'lambda_l1': 6.41584172012579e-05, 'lambda_l2': 0.061929577465337386, 'feature_fraction': 0.8944041219526851, 'bagging_fraction': 0.8049415608957036, 'bagging_freq': 3, 'weight_class_0': 0.36256482133474843, 'weight_class_1': 0.32145252581149303, 'weight_class_2': 1.1325457467519342}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  73%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 44/60 [16:18<05:50, 21.89s/it]

[I 2026-06-18 15:22:04,946] Trial 49 pruned.

Best trial: 10. Best value: 0.965896:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 45/60 [16:20<03:57, 15.86s/it]

[I 2026-06-18 15:22:06,720] Trial 46 finished with value: 0.9532067136241235 and parameters: {'n_estimators': 256, 'learning_rate': 0.29840919643697067, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 48, 'lambda_l1': 4.6663074804044513e-05, 'lambda_l2': 0.04943279275193172, 'feature_fraction': 0.8848129641669273, 'bagging_fraction': 0.8070564387277157, 'bagging_freq': 4, 'weight_class_0': 0.38957674643802603, 'weight_class_1': 0.3713806101427467, 'weight_class_2': 1.1575818088600955}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 10. Best value: 0.965896:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 46/60 [16:35<03:39, 15.66s/it]

[I 2026-06-18 15:22:21,926] Trial 47 finished with value: 0.9620176206796096 and parameters: {'n_estimators': 256, 'learning_rate': 0.2841116061177312, 'num_leaves': 9, 'max_depth': 3, 'min_child_samples': 47, 'lambda_l1': 5.861558061759523e-05, 'lambda_l2': 0.04950261401744578, 'feature_fraction': 0.8869254707158383, 'bagging_fraction': 0.861668768641949, 'bagging_freq': 3, 'weight_class_0': 0.3919662911022949, 'weight_class_1': 0.30174213604164785, 'weight_class_2': 1.1008462089667783}. Best is trial 10 with value: 0.9658962444525903.

Best trial: 36. Best value: 0.965998:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 47/60 [16:45<03:00, 13.89s/it]

[I 2026-06-18 15:22:31,697] Trial 36 finished with value: 0.965998268745912 and parameters: {'n_estimators': 376, 'learning_rate': 0.010690716167433436, 'num_leaves': 16, 'max_depth': 4, 'min_child_samples': 65, 'lambda_l1': 1.4490262591579405e-05, 'lambda_l2': 1.1413925120664241, 'feature_fraction': 0.8132897311787317, 'bagging_fraction': 0.8181588807412384, 'bagging_freq': 2, 'weight_class_0': 0.3217071180748454, 'weight_class_1': 1.9776394769102306, 'weight_class_2': 1.9671735608024097}. Best is trial 36 with value: 0.965998268745912.
[I 2026-06-18 15:22:31,741] Trial 37 finished with value: 0.965433193411469 and parameters: {'n_estimators': 369, 'learning_rate': 0.13897157230135543, 'num_leaves': 16, 'max_depth': 4, 'min_child_samples': 73, 'lambda_l1': 7.94600876884093e-05, 'lambda_l2': 0.9464239407844935, 'feature_fraction': 0.8201876019442971, 'bagging_fraction': 0.8245132261813477, 'bagging_freq': 2, 'weight_class_0': 0.7130633611206834, 'weight_class_1': 1.8448546471049652, 'weight_class_2': 1.967983886975508}. Best is trial 36 with value: 0.965998268745912.

Best trial: 36. Best value: 0.965998:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 49/60 [16:47<01:27,  7.95s/it]

[I 2026-06-18 15:22:33,724] Trial 45 pruned.

Best trial: 36. Best value: 0.965998:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 50/60 [17:20<02:22, 14.28s/it]

[I 2026-06-18 15:23:07,201] Trial 50 finished with value: 0.962883426993739 and parameters: {'n_estimators': 258, 'learning_rate': 0.10166002679699832, 'num_leaves': 4, 'max_depth': 3, 'min_child_samples': 32, 'lambda_l1': 5.761011066951983e-05, 'lambda_l2': 0.0033859966608142046, 'feature_fraction': 0.8904045213918231, 'bagging_fraction': 0.803216447385468, 'bagging_freq': 1, 'weight_class_0': 0.3786219585433658, 'weight_class_1': 0.2975495988618043, 'weight_class_2': 1.163476356108351}. Best is trial 36 with value: 0.965998268745912.

Best trial: 36. Best value: 0.965998:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 51/60 [17:24<01:42, 11.44s/it]

[I 2026-06-18 15:23:10,632] Trial 44 finished with value: 0.95849409719914 and parameters: {'n_estimators': 350, 'learning_rate': 0.2665176101660057, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 31, 'lambda_l1': 1.0238103401388198e-05, 'lambda_l2': 0.040096808594232244, 'feature_fraction': 0.8921369398149699, 'bagging_fraction': 0.7231873264046835, 'bagging_freq': 4, 'weight_class_0': 0.3367151987652297, 'weight_class_1': 0.3705608490618404, 'weight_class_2': 0.7680268827595127}. Best is trial 36 with value: 0.965998268745912.

Best trial: 36. Best value: 0.965998:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 52/60 [17:41<01:43, 12.98s/it]

[I 2026-06-18 15:23:27,743] Trial 52 finished with value: 0.9656394611005542 and parameters: {'n_estimators': 266, 'learning_rate': 0.10798429274452175, 'num_leaves': 4, 'max_depth': 3, 'min_child_samples': 95, 'lambda_l1': 8.315886556502793e-05, 'lambda_l2': 2.0719375744551987, 'feature_fraction': 0.7507918815129816, 'bagging_fraction': 0.8737743928332454, 'bagging_freq': 2, 'weight_class_0': 0.3355165281034366, 'weight_class_1': 1.594039711814887, 'weight_class_2': 1.1371367670197465}. Best is trial 36 with value: 0.965998268745912.

Best trial: 36. Best value: 0.965998:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 53/60 [17:42<01:06,  9.52s/it]

[I 2026-06-18 15:23:28,339] Trial 51 finished with value: 0.9633752389855305 and parameters: {'n_estimators': 238, 'learning_rate': 0.1024799448389527, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 81, 'lambda_l1': 8.293021041844643e-05, 'lambda_l2': 0.004612735508129582, 'feature_fraction': 0.8829255925603564, 'bagging_fraction': 0.8019515025134106, 'bagging_freq': 1, 'weight_class_0': 0.3664394297109315, 'weight_class_1': 0.32185904658658704, 'weight_class_2': 1.1225849586091328}. Best is trial 36 with value: 0.965998268745912.

Best trial: 54. Best value: 0.966012:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 54/60 [18:18<01:43, 17.18s/it]

[I 2026-06-18 15:24:04,677] Trial 54 finished with value: 0.9660115740009152 and parameters: {'n_estimators': 261, 'learning_rate': 0.09903659059028726, 'num_leaves': 22, 'max_depth': 1, 'min_child_samples': 94, 'lambda_l1': 6.569553828599881e-05, 'lambda_l2': 0.003788040443916899, 'feature_fraction': 0.7590364337185407, 'bagging_fraction': 0.8658051475996701, 'bagging_freq': 1, 'weight_class_0': 0.4544162386527272, 'weight_class_1': 1.5949001051307539, 'weight_class_2': 1.500655520466775}. Best is trial 54 with value: 0.9660115740009152.

Best trial: 54. Best value: 0.966012:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 55/60 [18:26<01:12, 14.43s/it]

[I 2026-06-18 15:24:12,384] Trial 53 finished with value: 0.9658026443035338 and parameters: {'n_estimators': 255, 'learning_rate': 0.10873023441217751, 'num_leaves': 22, 'max_depth': 3, 'min_child_samples': 95, 'lambda_l1': 0.0009168548579702073, 'lambda_l2': 0.004908684912529386, 'feature_fraction': 0.8843087697964948, 'bagging_fraction': 0.8676949755665867, 'bagging_freq': 1, 'weight_class_0': 0.392706203032959, 'weight_class_1': 1.6291594605987652, 'weight_class_2': 1.5076819396091343}. Best is trial 54 with value: 0.9660115740009152.

Best trial: 56. Best value: 0.966072:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 56/60 [18:41<00:58, 14.64s/it]

[I 2026-06-18 15:24:27,518] Trial 56 finished with value: 0.9660721332121811 and parameters: {'n_estimators': 413, 'learning_rate': 0.10710489288644891, 'num_leaves': 22, 'max_depth': 1, 'min_child_samples': 95, 'lambda_l1': 0.0009444444419897858, 'lambda_l2': 2.624097576059962, 'feature_fraction': 0.7542572256209854, 'bagging_fraction': 0.8617937173210679, 'bagging_freq': 2, 'weight_class_0': 0.25638415553594995, 'weight_class_1': 0.5558775959723516, 'weight_class_2': 1.5326100445071382}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 57/60 [18:52<00:40, 13.62s/it]

[I 2026-06-18 15:24:38,712] Trial 57 finished with value: 0.963035011057484 and parameters: {'n_estimators': 417, 'learning_rate': 0.12260392686744222, 'num_leaves': 22, 'max_depth': 1, 'min_child_samples': 94, 'lambda_l1': 0.03134452803478829, 'lambda_l2': 0.00014728841628030087, 'feature_fraction': 0.7424924086878377, 'bagging_fraction': 0.8850624289847479, 'bagging_freq': 2, 'weight_class_0': 0.8894369598742137, 'weight_class_1': 1.5855993225204006, 'weight_class_2': 1.5024082648344113}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 58/60 [18:52<00:19,  9.65s/it]

[I 2026-06-18 15:24:38,932] Trial 55 finished with value: 0.9639316501763598 and parameters: {'n_estimators': 422, 'learning_rate': 0.09622801708419597, 'num_leaves': 21, 'max_depth': 1, 'min_child_samples': 80, 'lambda_l1': 0.0009801494909942032, 'lambda_l2': 0.00022483973641609098, 'feature_fraction': 0.7522698014557753, 'bagging_fraction': 0.8678331838879346, 'bagging_freq': 2, 'weight_class_0': 0.49309835487558873, 'weight_class_1': 0.5117346162129203, 'weight_class_2': 1.5236044920805272}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 59/60 [19:57<00:26, 26.09s/it]

[I 2026-06-18 15:25:43,864] Trial 58 finished with value: 0.9633612022017264 and parameters: {'n_estimators': 320, 'learning_rate': 0.10723274321932065, 'num_leaves': 18, 'max_depth': 5, 'min_child_samples': 79, 'lambda_l1': 0.00011589054763669146, 'lambda_l2': 2.5402965093386674, 'feature_fraction': 0.7558500747498834, 'bagging_fraction': 0.8842133465299639, 'bagging_freq': 1, 'weight_class_0': 0.47801378645144676, 'weight_class_1': 1.5584946378805118, 'weight_class_2': 0.9456920553897927}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [19:59<00:00, 19.99s/it]

[I 2026-06-18 15:25:45,839] Trial 59 finished with value: 0.966059648476878 and parameters: {'n_estimators': 320, 'learning_rate': 0.017995893512805426, 'num_leaves': 18, 'max_depth': 5, 'min_child_samples': 81, 'lambda_l1': 0.0001203526717084888, 'lambda_l2': 2.2329434297224835, 'feature_fraction': 0.7567590223750145, 'bagging_fraction': 0.8873488868931302, 'bagging_freq': 1, 'weight_class_0': 0.5399354599403758, 'weight_class_1': 1.5889596096599146, 'weight_class_2': 1.7708332247091554}. Best is trial 56 with value: 0.9660721332121811.
Best trial score:
0.9660721332121811

Best params:
{'n_estimators': 413, 'learning_rate': 0.10710489288644891, 'num_leaves': 22, 'max_depth': 1, 'min_child_samples': 95, 'lambda_l1': 0.0009444444419897858, 'lambda_l2': 2.624097576059962, 'feature_fraction': 0.7542572256209854, 'bagging_fraction': 0.8617937173210679, 'bagging_freq': 2, 'weight_class_0': 0.25638415553594995, 'weight_class_1': 0.5558775959723516, 'weight_class_2': 1.5326100445071382}

In [18]:
study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=30, n_jobs=-1, show_progress_bar=True)

Best trial: 56. Best value: 0.966072:   3%|████▌                                                                                                                                  | 1/30 [02:11<1:03:41, 131.79s/it]

[I 2026-06-18 15:31:11,035] Trial 61 finished with value: 0.9658128185813194 and parameters: {'n_estimators': 202, 'learning_rate': 0.019349873436356732, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.0034247402388475263, 'lambda_l2': 4.67961054609198, 'feature_fraction': 0.7840703383098341, 'bagging_fraction': 0.8966498596469881, 'bagging_freq': 1, 'weight_class_0': 0.26564807318508576, 'weight_class_1': 1.7121371367661486, 'weight_class_2': 1.6896154296926642}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:   7%|█████████▏                                                                                                                                | 2/30 [02:13<25:41, 55.05s/it]

[I 2026-06-18 15:31:12,369] Trial 70 finished with value: 0.9650177600204923 and parameters: {'n_estimators': 205, 'learning_rate': 0.017528748961664065, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.0009791842774026212, 'lambda_l2': 4.253523578830545, 'feature_fraction': 0.7903085021277989, 'bagging_fraction': 0.856306831310187, 'bagging_freq': 1, 'weight_class_0': 0.2279900133084261, 'weight_class_1': 1.751603307713158, 'weight_class_2': 1.6922084593285576}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  10%|█████████████▊                                                                                                                            | 3/30 [02:14<13:41, 30.42s/it]

[I 2026-06-18 15:31:13,501] Trial 69 finished with value: 0.9643672126893245 and parameters: {'n_estimators': 205, 'learning_rate': 0.017680018519666635, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 88, 'lambda_l1': 0.0007033187727856177, 'lambda_l2': 4.013245477343041, 'feature_fraction': 0.7767805328359196, 'bagging_fraction': 0.8960208356960536, 'bagging_freq': 1, 'weight_class_0': 0.20832160004158767, 'weight_class_1': 1.7430684503405955, 'weight_class_2': 1.6502567081476194}. Best is trial 56 with value: 0.9660721332121811.
[I 2026-06-18 15:31:13,694] Trial 63 finished with value: 0.9651583741196672 and parameters: {'n_estimators': 208, 'learning_rate': 0.018806410486789264, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.0007563923719360031, 'lambda_l2': 3.9074657842127425, 'feature_fraction': 0.7881625836563321, 'bagging_fraction': 0.8966778201618633, 'bagging_freq': 1, 'weight_class_0': 0.23623734657092352, 'weight_class_1': 1.7321293349785445, 'weight_class_2': 1.6829033456225448}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  17%|███████████████████████                                                                                                                   | 5/30 [02:16<05:09, 12.40s/it]

[I 2026-06-18 15:31:15,291] Trial 65 finished with value: 0.9654606096804329 and parameters: {'n_estimators': 196, 'learning_rate': 0.01755906459061798, 'num_leaves': 28, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.0038758556441042397, 'lambda_l2': 3.935838651746423, 'feature_fraction': 0.7920826509480849, 'bagging_fraction': 0.9000290307393708, 'bagging_freq': 1, 'weight_class_0': 0.24294796301401442, 'weight_class_1': 1.7052676914226352, 'weight_class_2': 1.68436364687083}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  20%|███████████████████████████▌                                                                                                              | 6/30 [02:16<03:20,  8.34s/it]

[I 2026-06-18 15:31:15,761] Trial 64 finished with value: 0.9649252724195593 and parameters: {'n_estimators': 203, 'learning_rate': 0.018889591266661742, 'num_leaves': 29, 'max_depth': 1, 'min_child_samples': 85, 'lambda_l1': 0.000733071479231822, 'lambda_l2': 4.191219602043648, 'feature_fraction': 0.7868278051561468, 'bagging_fraction': 0.8969145197111278, 'bagging_freq': 1, 'weight_class_0': 0.2285451968885574, 'weight_class_1': 1.7093583662831635, 'weight_class_2': 1.6877446714829527}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  23%|████████████████████████████████▏                                                                                                         | 7/30 [02:17<02:13,  5.79s/it]

[I 2026-06-18 15:31:16,293] Trial 62 finished with value: 0.9654415971805671 and parameters: {'n_estimators': 198, 'learning_rate': 0.017941162608381172, 'num_leaves': 28, 'max_depth': 1, 'min_child_samples': 85, 'lambda_l1': 0.003124354826837157, 'lambda_l2': 3.694360144328064, 'feature_fraction': 0.7892493207506666, 'bagging_fraction': 0.9036940059386913, 'bagging_freq': 1, 'weight_class_0': 0.24486418745629032, 'weight_class_1': 1.7323201774685264, 'weight_class_2': 1.7109677949824573}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  27%|████████████████████████████████████▊                                                                                                     | 8/30 [02:20<01:49,  4.97s/it]

[I 2026-06-18 15:31:19,503] Trial 71 finished with value: 0.9646021162102564 and parameters: {'n_estimators': 218, 'learning_rate': 0.0180975292314127, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.00327163017459394, 'lambda_l2': 3.757766517629057, 'feature_fraction': 0.7918441572140621, 'bagging_fraction': 0.8994918836849458, 'bagging_freq': 1, 'weight_class_0': 0.21872095705744812, 'weight_class_1': 1.7168452341027947, 'weight_class_2': 1.7087678770354604}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  30%|█████████████████████████████████████████▍                                                                                                | 9/30 [02:25<01:46,  5.05s/it]

[I 2026-06-18 15:31:24,733] Trial 67 finished with value: 0.9648366583905151 and parameters: {'n_estimators': 213, 'learning_rate': 0.017582035096497427, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 87, 'lambda_l1': 0.0028272468631773363, 'lambda_l2': 0.0009318893524475785, 'feature_fraction': 0.7883711034242442, 'bagging_fraction': 0.9026209633814996, 'bagging_freq': 1, 'weight_class_0': 0.22696626210967996, 'weight_class_1': 1.7288574213593644, 'weight_class_2': 1.7722630758033102}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  33%|█████████████████████████████████████████████▋                                                                                           | 10/30 [03:11<05:55, 17.75s/it]

[I 2026-06-18 15:32:10,938] Trial 66 finished with value: 0.9649616418381317 and parameters: {'n_estimators': 289, 'learning_rate': 0.016943143334125034, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 87, 'lambda_l1': 0.0010771738934786587, 'lambda_l2': 4.033268910632804, 'feature_fraction': 0.7937777525640828, 'bagging_fraction': 0.906819494036824, 'bagging_freq': 1, 'weight_class_0': 0.23780290637527446, 'weight_class_1': 1.7160818922038796, 'weight_class_2': 1.8163850061175233}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  37%|██████████████████████████████████████████████████▏                                                                                      | 11/30 [03:12<03:59, 12.62s/it]

[I 2026-06-18 15:32:11,915] Trial 60 finished with value: 0.9649046720370167 and parameters: {'n_estimators': 287, 'learning_rate': 0.01791612788143386, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 84, 'lambda_l1': 0.000742980268491758, 'lambda_l2': 0.0006229624508496816, 'feature_fraction': 0.7873030665308888, 'bagging_fraction': 0.9021272171603194, 'bagging_freq': 1, 'weight_class_0': 0.22658054394695293, 'weight_class_1': 1.7252272784606413, 'weight_class_2': 1.697028161435249}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  40%|██████████████████████████████████████████████████████▊                                                                                  | 12/30 [03:16<02:59,  9.99s/it]

[I 2026-06-18 15:32:15,892] Trial 68 finished with value: 0.9651282760213483 and parameters: {'n_estimators': 290, 'learning_rate': 0.017723763452615966, 'num_leaves': 27, 'max_depth': 1, 'min_child_samples': 88, 'lambda_l1': 0.0031157527788143436, 'lambda_l2': 1.5608448451398569, 'feature_fraction': 0.7870270635154765, 'bagging_fraction': 0.9018660978958801, 'bagging_freq': 1, 'weight_class_0': 0.23259706065681568, 'weight_class_1': 1.7498559102864535, 'weight_class_2': 1.664314540627971}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  43%|███████████████████████████████████████████████████████████▎                                                                             | 13/30 [04:23<07:41, 27.15s/it]

[I 2026-06-18 15:33:22,530] Trial 72 finished with value: 0.9657773451551342 and parameters: {'n_estimators': 186, 'learning_rate': 0.02293401794265017, 'num_leaves': 26, 'max_depth': 1, 'min_child_samples': 86, 'lambda_l1': 0.0031299332559301288, 'lambda_l2': 3.5588673123525303, 'feature_fraction': 0.794529991178996, 'bagging_fraction': 0.9053257583012236, 'bagging_freq': 1, 'weight_class_0': 0.26398256800773745, 'weight_class_1': 1.7338323489090917, 'weight_class_2': 1.6558735508757518}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  47%|███████████████████████████████████████████████████████████████▉                                                                         | 14/30 [05:00<08:03, 30.25s/it]

[I 2026-06-18 15:33:59,932] Trial 79 finished with value: 0.9648111634515283 and parameters: {'n_estimators': 179, 'learning_rate': 0.028638451695435732, 'num_leaves': 31, 'max_depth': 2, 'min_child_samples': 91, 'lambda_l1': 2.7125158733588765e-05, 'lambda_l2': 1.857192558726294, 'feature_fraction': 0.7299112000023414, 'bagging_fraction': 0.9383837456167368, 'bagging_freq': 1, 'weight_class_0': 0.5887533239832446, 'weight_class_1': 0.7753990967431115, 'weight_class_2': 1.8218221910776407}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 15/30 [05:12<06:09, 24.66s/it]

[I 2026-06-18 15:34:11,648] Trial 82 finished with value: 0.9650380016828487 and parameters: {'n_estimators': 154, 'learning_rate': 0.012759375632601502, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 92, 'lambda_l1': 0.006871906009016073, 'lambda_l2': 1.6246107345238245, 'feature_fraction': 0.7304424475293333, 'bagging_fraction': 0.8753694824594335, 'bagging_freq': 2, 'weight_class_0': 0.6065674134584589, 'weight_class_1': 1.521090067617502, 'weight_class_2': 1.6171111253195598}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  53%|█████████████████████████████████████████████████████████████████████████                                                                | 16/30 [05:32<05:27, 23.42s/it]

[I 2026-06-18 15:34:32,195] Trial 74 finished with value: 0.9657993863716234 and parameters: {'n_estimators': 304, 'learning_rate': 0.026698732791861836, 'num_leaves': 29, 'max_depth': 1, 'min_child_samples': 91, 'lambda_l1': 0.002766733725526384, 'lambda_l2': 1.5845492857861851, 'feature_fraction': 0.734337662001994, 'bagging_fraction': 0.883620326538372, 'bagging_freq': 1, 'weight_class_0': 0.5997984246296111, 'weight_class_1': 1.6492558482667934, 'weight_class_2': 1.8091202115399185}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  57%|█████████████████████████████████████████████████████████████████████████████▋                                                           | 17/30 [05:37<03:49, 17.63s/it]

[I 2026-06-18 15:34:36,347] Trial 83 finished with value: 0.9647665441284687 and parameters: {'n_estimators': 172, 'learning_rate': 0.02937546537022075, 'num_leaves': 23, 'max_depth': 2, 'min_child_samples': 94, 'lambda_l1': 2.5068267895058782e-05, 'lambda_l2': 1.5796232762664435, 'feature_fraction': 0.7202779765515627, 'bagging_fraction': 0.875831130763779, 'bagging_freq': 2, 'weight_class_0': 0.6139013809443299, 'weight_class_1': 1.623655522506414, 'weight_class_2': 1.4444696909772756}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  60%|██████████████████████████████████████████████████████████████████████████████████▏                                                      | 18/30 [05:38<02:33, 12.76s/it]

[I 2026-06-18 15:34:37,780] Trial 73 finished with value: 0.9654754210291131 and parameters: {'n_estimators': 299, 'learning_rate': 0.026146144690197007, 'num_leaves': 29, 'max_depth': 1, 'min_child_samples': 84, 'lambda_l1': 0.004706185197490897, 'lambda_l2': 1.457610927196469, 'feature_fraction': 0.7970239472126125, 'bagging_fraction': 0.8971210203195026, 'bagging_freq': 1, 'weight_class_0': 0.6041994528187686, 'weight_class_1': 1.7323338024166917, 'weight_class_2': 1.651210725820125}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  63%|██████████████████████████████████████████████████████████████████████████████████████▊                                                  | 19/30 [05:39<01:40,  9.16s/it]

[I 2026-06-18 15:34:38,533] Trial 75 finished with value: 0.9659070360008979 and parameters: {'n_estimators': 307, 'learning_rate': 0.03309136482884955, 'num_leaves': 31, 'max_depth': 1, 'min_child_samples': 91, 'lambda_l1': 0.0027923154916565563, 'lambda_l2': 1.383897995802177, 'feature_fraction': 0.7249173729704248, 'bagging_fraction': 0.9075025686754323, 'bagging_freq': 1, 'weight_class_0': 0.5764075900524033, 'weight_class_1': 1.6669927599544254, 'weight_class_2': 1.7978912725660954}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  67%|███████████████████████████████████████████████████████████████████████████████████████████▎                                             | 20/30 [06:10<02:38, 15.90s/it]

[I 2026-06-18 15:35:10,148] Trial 76 finished with value: 0.9643525458786272 and parameters: {'n_estimators': 284, 'learning_rate': 0.02915157666278781, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 76, 'lambda_l1': 0.0018672802182782488, 'lambda_l2': 1.554634316144658, 'feature_fraction': 0.7266971450939426, 'bagging_fraction': 0.9111397858523449, 'bagging_freq': 1, 'weight_class_0': 0.6032770974257624, 'weight_class_1': 0.6880292420694293, 'weight_class_2': 1.74207889466058}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  70%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                         | 21/30 [06:12<01:45, 11.70s/it]

[I 2026-06-18 15:35:12,073] Trial 77 finished with value: 0.9660084543610401 and parameters: {'n_estimators': 290, 'learning_rate': 0.02748527672564711, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 94, 'lambda_l1': 0.002214494016259643, 'lambda_l2': 1.965953816794244, 'feature_fraction': 0.7268844281394465, 'bagging_fraction': 0.9086949993475122, 'bagging_freq': 1, 'weight_class_0': 0.5512416151297026, 'weight_class_1': 1.255262709363382, 'weight_class_2': 1.796283325231211}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  73%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 22/30 [06:23<01:30, 11.35s/it]

[I 2026-06-18 15:35:22,615] Trial 80 pruned.

Best trial: 56. Best value: 0.966072:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 23/30 [06:31<01:13, 10.50s/it]

[I 2026-06-18 15:35:31,138] Trial 78 finished with value: 0.9660138968121943 and parameters: {'n_estimators': 169, 'learning_rate': 0.025876357091744788, 'num_leaves': 31, 'max_depth': 5, 'min_child_samples': 92, 'lambda_l1': 0.0020772372635357163, 'lambda_l2': 1.6737364584746255, 'feature_fraction': 0.7193392807957502, 'bagging_fraction': 0.944862149221398, 'bagging_freq': 1, 'weight_class_0': 0.5689127690041175, 'weight_class_1': 1.2635270648254457, 'weight_class_2': 1.8512845283803687}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 24/30 [06:36<00:52,  8.77s/it]

[I 2026-06-18 15:35:35,855] Trial 84 finished with value: 0.9655937722558686 and parameters: {'n_estimators': 183, 'learning_rate': 0.02658364674941769, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 91, 'lambda_l1': 0.005525205481386624, 'lambda_l2': 6.720469001066976, 'feature_fraction': 0.73517741499628, 'bagging_fraction': 0.9214034560940506, 'bagging_freq': 1, 'weight_class_0': 0.5716330629373103, 'weight_class_1': 1.5073850469832912, 'weight_class_2': 1.5903700848605444}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 25/30 [06:40<00:36,  7.27s/it]

[I 2026-06-18 15:35:39,622] Trial 81 finished with value: 0.9658359398186676 and parameters: {'n_estimators': 283, 'learning_rate': 0.03233986934654558, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 92, 'lambda_l1': 2.2075698397705415e-05, 'lambda_l2': 2.2456525674450103, 'feature_fraction': 0.7237735450603958, 'bagging_fraction': 0.8827860332040641, 'bagging_freq': 1, 'weight_class_0': 0.5309125435510765, 'weight_class_1': 1.5096298732106612, 'weight_class_2': 1.5955786103412573}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 26/30 [06:52<00:34,  8.68s/it]

[I 2026-06-18 15:35:51,614] Trial 86 pruned.

Best trial: 56. Best value: 0.966072:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 27/30 [07:28<00:50, 16.98s/it]

[I 2026-06-18 15:36:27,958] Trial 85 finished with value: 0.9658506764650712 and parameters: {'n_estimators': 174, 'learning_rate': 0.022289470709714362, 'num_leaves': 22, 'max_depth': 5, 'min_child_samples': 98, 'lambda_l1': 0.0066955343099193675, 'lambda_l2': 6.925295567286622, 'feature_fraction': 0.7653182359275581, 'bagging_fraction': 0.945415280589607, 'bagging_freq': 1, 'weight_class_0': 0.5122988395002821, 'weight_class_1': 1.4937461654285014, 'weight_class_2': 1.5942621509270598}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 56. Best value: 0.966072:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 28/30 [07:49<00:36, 18.05s/it]

[I 2026-06-18 15:36:48,498] Trial 88 pruned.

Best trial: 56. Best value: 0.966072:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 29/30 [08:51<00:31, 31.25s/it]

[I 2026-06-18 15:37:50,547] Trial 87 finished with value: 0.9656569248277039 and parameters: {'n_estimators': 307, 'learning_rate': 0.03336556663915791, 'num_leaves': 23, 'max_depth': 5, 'min_child_samples': 99, 'lambda_l1': 0.0018899393503089127, 'lambda_l2': 6.757634330733043, 'feature_fraction': 0.7670337732396626, 'bagging_fraction': 0.8862055912633388, 'bagging_freq': 1, 'weight_class_0': 0.5284334956457066, 'weight_class_1': 1.2806818467814254, 'weight_class_2': 1.4633632172238862}. Best is trial 56 with value: 0.9660721332121811.

Best trial: 89. Best value: 0.966166: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [09:00<00:00, 18.00s/it]

[I 2026-06-18 15:37:59,413] Trial 89 finished with value: 0.9661655016712585 and parameters: {'n_estimators': 328, 'learning_rate': 0.03392891219249922, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 99, 'lambda_l1': 0.0017874228948738, 'lambda_l2': 0.3693642730472445, 'feature_fraction': 0.7650996115316755, 'bagging_fraction': 0.9175761063210657, 'bagging_freq': 1, 'weight_class_0': 0.5111464241626329, 'weight_class_1': 1.819479559256786, 'weight_class_2': 1.8620126135307478}. Best is trial 89 with value: 0.9661655016712585.

In [13]:
lgbm_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lgbm = LGBMClassifier(
    **lgbm_params,
    objective='multiclass',
    metric='multi_logloss',
    boosting_type='gbdt',
    verbosity=-1,
    random_state=42,
    n_jobs=1,
).fit(X_train, y_train.class_encoded)

test_proba = lgbm.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [14]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [15]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lgbm.csv', index=False)

In [16]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [17]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'hist_0', 'hist_1', 'hist_2', 'rf_0', 'rf_1', 'rf_2',
       'extra_0', 'extra_1', 'extra_2'],
      dtype='str')